// regex_diff.cpp
// Differential test: micron::regex vs glibc POSIX regexec ground truth
// (regex_expected.hpp, generated by oracle_posix.c over regex_corpus.hpp).
//
// The whole-match span (group 0) MUST agree -- that is POSIX leftmost-longest
// correctness and a mismatch is a hard failure. Sub-group capture differences
// are surfaced as INFO (micron uses greedy disambiguation, which can diverge
// from strict-POSIX subexpression rules on ambiguous patterns).
//
// snowball convention: exit 1 == success; judge by the banner.

#include "../../src/regex.hpp"

#include "../snowball/snowball.hpp"

#include "regex_corpus.hpp"
#include "regex_expected.hpp"

using sb::print;
using sb::require_true;

namespace mc = micron;
namespace io = micron::io;

#define NG 10

int
main()
{
  print("=== REGEX DIFFERENTIAL TEST (vs glibc POSIX regexec) ===");

  int g0_fail = 0;
  int sub_diff = 0;
  int compared = 0;
  int skipped = 0;

  for ( int i = 0; i < REGEX_CORPUS_N; ++i ) {
    const long *E = REGEX_EXPECTED[i];
    if ( E[0] == -2 ) {      // glibc rejected the pattern; not comparable
      ++skipped;
      continue;
    }
    ++compared;

    const char *pat = REGEX_CORPUS[i].pat;
    const char *in = REGEX_CORPUS[i].in;

    mc::regex re(pat);
    mc::rmatch m = re.match(in);

    int gm = m.has_match() ? 1 : 0;
    long got[1 + 2 * NG];
    got[0] = gm;
    for ( int g = 0; g < NG; ++g ) {
      got[1 + 2 * g] = gm ? (long)m.group_start((usize)g) : -1;
      got[1 + 2 * g + 1] = gm ? (long)m.group_end((usize)g) : -1;
    }

    // group-0 / matched flag: hard invariant
    if ( got[0] != E[0] || got[1] != E[1] || got[2] != E[2] ) {
      ++g0_fail;
      io::print("  G0 FAIL [", i, "] pat=`", pat, "` in=`", in, "`  exp(m=", E[0], " [", E[1], ",", E[2], "])  got(m=", got[0], " [",
                got[1], ",", got[2], "])\n");
      continue;
    }

    // sub-groups: informational
    for ( int g = 1; g < NG; ++g ) {
      if ( got[1 + 2 * g] != E[1 + 2 * g] || got[2 + 2 * g] != E[2 + 2 * g] ) {
        ++sub_diff;
        io::print("  ~ subgroup ", g, " diff [", i, "] pat=`", pat, "` in=`", in, "`  exp[", E[1 + 2 * g], ",", E[2 + 2 * g], "] got[",
                  got[1 + 2 * g], ",", got[2 + 2 * g], "]\n");
        break;
      }
    }
  }

  io::print("compared=", compared, " skipped=", skipped, " group0_failures=", g0_fail, " subgroup_diffs=", sub_diff, "\n");

  require_true(g0_fail == 0);

  print("=== REGEX DIFFERENTIAL TEST PASSED (group-0 leftmost-longest matches glibc) ===");
  return 1;
}
