// regex_fuzz_gen.c
// Randomized differential fuzzer GENERATOR. Emits a C++ header of N random
// POSIX-ERE (pattern, input) pairs together with glibc's regexec ground truth,
// which regex_fuzz.cpp (micron) then asserts against. Patterns are drawn from a
// restricted grammar that is unambiguously POSIX ERE (no '\' escapes, no GNU
// extensions, only complete {m,n} intervals, simple bracket classes) so glibc
// and micron interpret them identically.
//
//   gcc -O2 tests/rigor/regex_fuzz_gen.c -o /tmp/fuzzgen
//   /tmp/fuzzgen 20000 12345 > tests/rigor/regex_fuzz.hpp
#include <regex.h>
#include <setjmp.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

// glibc's regexec is a BACKTRACKING matcher and goes exponential on some
// patterns. Guard each call with a 1s alarm + siglongjmp so the oracle never
// hangs; timed-out cases are marked skipped (out[0] = -2). (micron's Pike VM is
// linear and needs no such guard -- that contrast is the point.)
static sigjmp_buf JB;

static void
on_alrm(int s)
{
  (void)s;
  siglongjmp(JB, 1);
}

static unsigned int RNG;

static unsigned int
xr(void)
{
  RNG ^= RNG << 13;
  RNG ^= RNG >> 17;
  RNG ^= RNG << 5;
  return RNG;
}

static unsigned int
rr(unsigned int n)
{
  return xr() % n;
}

static char buf[256];
static int blen;

static void
emit(char c)
{
  if ( blen < 240 ) buf[blen++] = c;
}

static char
rletter(void)
{
  return "abc"[rr(3)];
}

static void gen_alt(int depth);

static void
gen_atom(int depth)
{
  unsigned int r = rr(100);
  if ( depth > 0 && r < 18 && blen < 200 ) {
    emit('(');
    gen_alt(depth - 1);
    emit(')');
  } else if ( r < 33 ) {
    emit('[');
    if ( rr(3) == 0 ) emit('^');
    int m = 1 + rr(3);
    for ( int i = 0; i < m; ++i ) {
      if ( rr(2) ) {
        emit('a' + rr(2));      // a or b
        emit('-');
        emit('b' + rr(2));      // b or c  (lo<=hi)
      } else {
        emit(rletter());
      }
    }
    emit(']');
  } else if ( r < 42 ) {
    emit('.');
  } else {
    emit(rletter());
  }
}

static void
gen_piece(int depth)
{
  gen_atom(depth);
  unsigned int r = rr(100);
  if ( r < 14 )
    emit('*');
  else if ( r < 24 )
    emit('+');
  else if ( r < 34 )
    emit('?');
  else if ( r < 41 ) {
    int m = rr(4);
    emit('{');
    emit('0' + m);
    if ( rr(2) ) {
      emit(',');
      if ( rr(2) ) {
        int n = m + rr(3);
        emit('0' + n);
      }
    }
    emit('}');
  }
}

static void
gen_seq(int depth)
{
  int n = 1 + rr(4);
  for ( int i = 0; i < n && blen < 220; ++i ) gen_piece(depth);
}

static void
gen_alt(int depth)
{
  gen_seq(depth);
  while ( rr(100) < 22 && blen < 220 ) {
    emit('|');
    gen_seq(depth);
  }
}

static void
gen_pattern(void)
{
  blen = 0;
  int anch_s = rr(4) == 0;
  int anch_e = rr(4) == 0;
  if ( anch_s ) emit('^');
  gen_alt(2);
  if ( anch_e ) emit('$');
  buf[blen] = 0;
}

static char inbuf[32];

static void
gen_input(void)
{
  int n = rr(9);
  for ( int i = 0; i < n; ++i ) inbuf[i] = "abc"[rr(3)];
  inbuf[n] = 0;
}

#define NG 10

int
main(int argc, char **argv)
{
  int N = (argc > 1) ? atoi(argv[1]) : 20000;
  RNG = (argc > 2) ? (unsigned int)strtoul(argv[2], 0, 10) : 1u;
  if ( !RNG ) RNG = 1;
  signal(SIGALRM, on_alrm);

  printf("// auto-generated by regex_fuzz_gen.c -- do not edit\n#pragma once\n");
  printf("static const regex_case REGEX_FUZZ[] = {\n");
  // we must keep cases and expected aligned; buffer both, print together.
  // (simplest: regenerate deterministically in a second pass.)
  unsigned int seed = RNG;
  int emitted = 0;
  for ( int i = 0; i < N; ++i ) {
    gen_pattern();
    gen_input();
    regex_t re;
    if ( regcomp(&re, buf, REG_EXTENDED) != 0 ) continue;      // skip rejected
    regfree(&re);
    printf("  {\"%s\",\"%s\"},\n", buf, inbuf);
    ++emitted;
  }
  printf("};\n");

  // second pass, same seed -> identical sequence -> expected aligned with cases
  RNG = seed;
  printf("static const long REGEX_FUZZ_EXPECTED[][1+2*%d] = {\n", NG);
  for ( int i = 0; i < N; ++i ) {
    gen_pattern();
    gen_input();
    regex_t re;
    if ( regcomp(&re, buf, REG_EXTENDED) != 0 ) continue;
    regmatch_t pm[NG];
    long out[1 + 2 * NG];
    for ( int k = 0; k < 1 + 2 * NG; ++k ) out[k] = -1;
    int rc_exec = -1;
    if ( sigsetjmp(JB, 1) == 0 ) {
      alarm(1);
      rc_exec = regexec(&re, inbuf, NG, pm, 0);
      alarm(0);
    } else {
      alarm(0);
      out[0] = -2;      // glibc regexec exceeded the time budget -> skip
    }
    if ( out[0] != -2 ) {
      if ( rc_exec == 0 ) {
        out[0] = 1;
        for ( int g = 0; g < NG; ++g ) {
          out[1 + 2 * g] = (long)pm[g].rm_so;
          out[1 + 2 * g + 1] = (long)pm[g].rm_eo;
        }
      } else {
        out[0] = 0;
      }
    }
    regfree(&re);
    printf("  {");
    for ( int k = 0; k < 1 + 2 * NG; ++k ) printf("%ld%s", out[k], (k + 1 < 1 + 2 * NG) ? "," : "");
    printf("},\n");
  }
  printf("};\n");
  printf("static const int REGEX_FUZZ_N = %d;\n", emitted);
  return 0;
}
