//  Copyright (c) 2024- David Lucius Severus
//
//  Distributed under the Boost Software License, Version 1.0.
//  See accompanying file LICENSE_1_0.txt or copy at
//  http://www.boost.org/LICENSE_1_0.txt
#pragma once

#include "../../../types.hpp"
#include "__gl_types.hpp"

// not autogenerated, yet
namespace micron
{
namespace gfx
{
namespace gl
{

inline constexpr unsigned int KHRONOS_FALSE = 0;
inline constexpr unsigned int KHRONOS_TRUE = 1;
inline constexpr unsigned int KHRONOS_MAX_ENUM = 0x7FFFFFFF;

using EGLBoolean = unsigned int;
using EGLint = i32;
using EGLenum = u32;
using EGLAttrib = intptr_t;
using EGLTime = u64;
using EGLuint64KHR = u64;
using EGLnsecsANDROID = i64;

struct __EGLDisplayOpaque;
struct __EGLContextOpaque;
struct __EGLSurfaceOpaque;
struct __EGLConfigOpaque;
struct __EGLClientBufferOpaque;
struct __EGLSyncOpaque;
struct __EGLImageOpaque;

using EGLDisplay = __EGLDisplayOpaque *;
using EGLContext = __EGLContextOpaque *;
using EGLSurface = __EGLSurfaceOpaque *;
using EGLConfig = __EGLConfigOpaque *;
using EGLClientBuffer = __EGLClientBufferOpaque *;
using EGLSync = __EGLSyncOpaque *;
using EGLImage = __EGLImageOpaque *;

using EGLNativeDisplayType = void *;
using EGLNativeWindowType = void *;
using EGLNativePixmapType = void *;

inline constexpr EGLBoolean EGL_FALSE = 0;
inline constexpr EGLBoolean EGL_TRUE = 1;

inline constexpr EGLDisplay EGL_NO_DISPLAY = nullptr;
inline constexpr EGLContext EGL_NO_CONTEXT = nullptr;
inline constexpr EGLSurface EGL_NO_SURFACE = nullptr;

inline constexpr EGLint EGL_NONE = 0x3038;
inline constexpr EGLint EGL_DEFAULT_DISPLAY = 0;

inline constexpr EGLint EGL_BUFFER_SIZE = 0x3020;
inline constexpr EGLint EGL_ALPHA_SIZE = 0x3021;
inline constexpr EGLint EGL_BLUE_SIZE = 0x3022;
inline constexpr EGLint EGL_GREEN_SIZE = 0x3023;
inline constexpr EGLint EGL_RED_SIZE = 0x3024;
inline constexpr EGLint EGL_DEPTH_SIZE = 0x3025;
inline constexpr EGLint EGL_STENCIL_SIZE = 0x3026;
inline constexpr EGLint EGL_SAMPLES = 0x3031;
inline constexpr EGLint EGL_SAMPLE_BUFFERS = 0x3032;
inline constexpr EGLint EGL_SURFACE_TYPE = 0x3033;
inline constexpr EGLint EGL_RENDERABLE_TYPE = 0x3040;
inline constexpr EGLint EGL_CONFORMANT = 0x3042;
inline constexpr EGLint EGL_COLOR_BUFFER_TYPE = 0x303F;
inline constexpr EGLint EGL_RGB_BUFFER = 0x308E;

inline constexpr EGLint EGL_WINDOW_BIT = 0x0004;
inline constexpr EGLint EGL_PBUFFER_BIT = 0x0001;
inline constexpr EGLint EGL_PIXMAP_BIT = 0x0002;

inline constexpr EGLint EGL_OPENGL_ES_BIT = 0x0001;
inline constexpr EGLint EGL_OPENVG_BIT = 0x0002;
inline constexpr EGLint EGL_OPENGL_ES2_BIT = 0x0004;
inline constexpr EGLint EGL_OPENGL_BIT = 0x0008;
inline constexpr EGLint EGL_OPENGL_ES3_BIT = 0x00000040;

inline constexpr EGLenum EGL_OPENGL_ES_API = 0x30A0;
inline constexpr EGLenum EGL_OPENVG_API = 0x30A1;
inline constexpr EGLenum EGL_OPENGL_API = 0x30A2;

inline constexpr EGLint EGL_CONTEXT_CLIENT_VERSION = 0x3098;
inline constexpr EGLint EGL_CONTEXT_MAJOR_VERSION = 0x3098;
inline constexpr EGLint EGL_CONTEXT_MINOR_VERSION = 0x30FB;
inline constexpr EGLint EGL_CONTEXT_OPENGL_PROFILE_MASK = 0x30FD;
inline constexpr EGLint EGL_CONTEXT_OPENGL_PROFILE_MASK_KHR = 0x30FD;
inline constexpr EGLint EGL_CONTEXT_OPENGL_CORE_PROFILE_BIT = 0x00000001;
inline constexpr EGLint EGL_CONTEXT_OPENGL_CORE_PROFILE_BIT_KHR = 0x00000001;
inline constexpr EGLint EGL_CONTEXT_OPENGL_COMPATIBILITY_PROFILE_BIT = 0x00000002;
inline constexpr EGLint EGL_CONTEXT_OPENGL_DEBUG = 0x31B0;
inline constexpr EGLint EGL_CONTEXT_OPENGL_FORWARD_COMPATIBLE = 0x31B1;
inline constexpr EGLint EGL_CONTEXT_OPENGL_ROBUST_ACCESS = 0x31B2;
inline constexpr EGLint EGL_CONTEXT_FLAGS_KHR = 0x30FC;
inline constexpr EGLint EGL_CONTEXT_OPENGL_DEBUG_BIT_KHR = 0x00000001;
inline constexpr EGLint EGL_CONTEXT_OPENGL_FORWARD_COMPATIBLE_BIT_KHR = 0x00000002;

inline constexpr EGLint EGL_VENDOR = 0x3053;
inline constexpr EGLint EGL_VERSION = 0x3054;
inline constexpr EGLint EGL_EXTENSIONS = 0x3055;
inline constexpr EGLint EGL_CLIENT_APIS = 0x308D;

inline constexpr EGLenum EGL_PLATFORM_X11_EXT = 0x31D5;
inline constexpr EGLenum EGL_PLATFORM_X11_KHR = 0x31D5;
inline constexpr EGLenum EGL_PLATFORM_WAYLAND_EXT = 0x31D8;
inline constexpr EGLenum EGL_PLATFORM_WAYLAND_KHR = 0x31D8;
inline constexpr EGLenum EGL_PLATFORM_GBM_KHR = 0x31D7;
inline constexpr EGLenum EGL_PLATFORM_SURFACELESS_MESA = 0x31DD;
inline constexpr EGLenum EGL_PLATFORM_DEVICE_EXT = 0x313F;

inline constexpr EGLint EGL_SUCCESS = 0x3000;
inline constexpr EGLint EGL_NOT_INITIALIZED = 0x3001;
inline constexpr EGLint EGL_BAD_ACCESS = 0x3002;
inline constexpr EGLint EGL_BAD_ALLOC = 0x3003;
inline constexpr EGLint EGL_BAD_ATTRIBUTE = 0x3004;
inline constexpr EGLint EGL_BAD_CONFIG = 0x3005;
inline constexpr EGLint EGL_BAD_CONTEXT = 0x3006;
inline constexpr EGLint EGL_BAD_DISPLAY = 0x3008;
inline constexpr EGLint EGL_BAD_MATCH = 0x3009;
inline constexpr EGLint EGL_BAD_NATIVE_WINDOW = 0x300B;
inline constexpr EGLint EGL_BAD_SURFACE = 0x300D;

using PFN_eglGetDisplay = EGLDisplay (*)(EGLNativeDisplayType display_id);
using PFN_eglGetPlatformDisplay = EGLDisplay (*)(EGLenum platform, void *native_display, const EGLAttrib *attrib_list);
using PFN_eglGetPlatformDisplayEXT = EGLDisplay (*)(EGLenum platform, void *native_display, const EGLint *attrib_list);
using PFN_eglInitialize = EGLBoolean (*)(EGLDisplay dpy, EGLint *major, EGLint *minor);
using PFN_eglTerminate = EGLBoolean (*)(EGLDisplay dpy);
using PFN_eglBindAPI = EGLBoolean (*)(EGLenum api);
using PFN_eglQueryString = const char *(*)(EGLDisplay dpy, EGLint name);
using PFN_eglChooseConfig
    = EGLBoolean (*)(EGLDisplay dpy, const EGLint *attrib_list, EGLConfig *configs, EGLint config_size, EGLint *num_config);
using PFN_eglGetConfigAttrib = EGLBoolean (*)(EGLDisplay dpy, EGLConfig config, EGLint attribute, EGLint *value);
using PFN_eglCreateContext = EGLContext (*)(EGLDisplay dpy, EGLConfig config, EGLContext share_context, const EGLint *attrib_list);
using PFN_eglDestroyContext = EGLBoolean (*)(EGLDisplay dpy, EGLContext ctx);
using PFN_eglCreateWindowSurface = EGLSurface (*)(EGLDisplay dpy, EGLConfig config, EGLNativeWindowType win, const EGLint *attrib_list);
using PFN_eglCreatePlatformWindowSurface
    = EGLSurface (*)(EGLDisplay dpy, EGLConfig config, void *native_window, const EGLAttrib *attrib_list);
using PFN_eglCreatePlatformWindowSurfaceEXT
    = EGLSurface (*)(EGLDisplay dpy, EGLConfig config, void *native_window, const EGLint *attrib_list);
using PFN_eglDestroySurface = EGLBoolean (*)(EGLDisplay dpy, EGLSurface surface);
using PFN_eglMakeCurrent = EGLBoolean (*)(EGLDisplay dpy, EGLSurface draw, EGLSurface read, EGLContext ctx);
using PFN_eglSwapBuffers = EGLBoolean (*)(EGLDisplay dpy, EGLSurface surface);
using PFN_eglSwapInterval = EGLBoolean (*)(EGLDisplay dpy, EGLint interval);
using PFN_eglGetProcAddress = void (*(*)(const char *procname))();
using PFN_eglGetCurrentContext = EGLContext (*)(void);
using PFN_eglGetCurrentSurface = EGLSurface (*)(EGLint readdraw);
using PFN_eglGetError = EGLint (*)(void);

using PFN_eglCreatePbufferSurface = EGLSurface (*)(EGLDisplay dpy, EGLConfig config, const EGLint *attrib_list);

inline constexpr EGLint EGL_WIDTH = 0x3057;
inline constexpr EGLint EGL_HEIGHT = 0x3056;
inline constexpr EGLint EGL_TEXTURE_FORMAT = 0x3080;
inline constexpr EGLint EGL_TEXTURE_TARGET = 0x3081;
inline constexpr EGLint EGL_MIPMAP_TEXTURE = 0x3082;
inline constexpr EGLint EGL_NO_TEXTURE = 0x305C;

};      // namespace gl
};      // namespace gfx
};      // namespace micron
