//  Copyright (c) 2024- David Lucius Severus
//
//  Distributed under the Boost Software License, Version 1.0.
//  See accompanying file LICENSE_1_0.txt or copy at
//  http://www.boost.org/LICENSE_1_0.txt
#pragma once

#include "../../platform/__bits/__x11_types.hpp"
#include "__gl_types.hpp"

// not autogenerated, yet

namespace micron
{
namespace gfx
{
namespace gl
{

struct __GLXContextOpaque;
struct __GLXFBConfigOpaque;

using GLXContext = __GLXContextOpaque *;
using GLXFBConfig = __GLXFBConfigOpaque *;
using GLXDrawable = XID;
using GLXWindow = XID;
using GLXPbuffer = XID;
using GLXPixmap = XID;

inline constexpr int GLX_USE_GL = 1;
inline constexpr int GLX_BUFFER_SIZE = 2;
inline constexpr int GLX_LEVEL = 3;
inline constexpr int GLX_RGBA = 4;
inline constexpr int GLX_DOUBLEBUFFER = 5;
inline constexpr int GLX_STEREO = 6;
inline constexpr int GLX_AUX_BUFFERS = 7;
inline constexpr int GLX_RED_SIZE = 8;
inline constexpr int GLX_GREEN_SIZE = 9;
inline constexpr int GLX_BLUE_SIZE = 10;
inline constexpr int GLX_ALPHA_SIZE = 11;
inline constexpr int GLX_DEPTH_SIZE = 12;
inline constexpr int GLX_STENCIL_SIZE = 13;
inline constexpr int GLX_ACCUM_RED_SIZE = 14;
inline constexpr int GLX_ACCUM_GREEN_SIZE = 15;
inline constexpr int GLX_ACCUM_BLUE_SIZE = 16;
inline constexpr int GLX_ACCUM_ALPHA_SIZE = 17;
inline constexpr int GLX_SAMPLE_BUFFERS = 0x186a0;
inline constexpr int GLX_SAMPLES = 0x186a1;

inline constexpr int GLX_X_VISUAL_TYPE = 0x22;
inline constexpr int GLX_CONFIG_CAVEAT = 0x20;
inline constexpr int GLX_DRAWABLE_TYPE = 0x8010;
inline constexpr int GLX_RENDER_TYPE = 0x8011;
inline constexpr int GLX_X_RENDERABLE = 0x8012;
inline constexpr int GLX_FBCONFIG_ID = 0x8013;
inline constexpr int GLX_RGBA_BIT = 0x00000001;
inline constexpr int GLX_WINDOW_BIT = 0x00000001;
inline constexpr int GLX_PBUFFER_BIT = 0x00000004;
inline constexpr int GLX_TRUE_COLOR = 0x8002;

inline constexpr int GLX_CONTEXT_MAJOR_VERSION_ARB = 0x2091;
inline constexpr int GLX_CONTEXT_MINOR_VERSION_ARB = 0x2092;
inline constexpr int GLX_CONTEXT_FLAGS_ARB = 0x2094;
inline constexpr int GLX_CONTEXT_PROFILE_MASK_ARB = 0x9126;
inline constexpr int GLX_CONTEXT_CORE_PROFILE_BIT_ARB = 0x00000001;
inline constexpr int GLX_CONTEXT_COMPATIBILITY_PROFILE_BIT_ARB = 0x00000002;
inline constexpr int GLX_CONTEXT_DEBUG_BIT_ARB = 0x00000001;
inline constexpr int GLX_CONTEXT_FORWARD_COMPATIBLE_BIT_ARB = 0x00000002;

using PFN_glXGetProcAddress = void (*(*)(const GLubyte *))();
using PFN_glXChooseFBConfig = GLXFBConfig *(*)(XDisplay * dpy, int screen, const int *attrib_list, int *nelements);
using PFN_glXGetVisualFromFBConfig = XVisualInfo *(*)(XDisplay * dpy, GLXFBConfig config);
using PFN_glXGetFBConfigAttrib = int (*)(XDisplay *dpy, GLXFBConfig config, int attrib, int *value);
using PFN_glXCreateNewContext = GLXContext (*)(XDisplay *dpy, GLXFBConfig config, int render_type, GLXContext share, XBool direct);
using PFN_glXCreateContextAttribsARB
    = GLXContext (*)(XDisplay *dpy, GLXFBConfig config, GLXContext share, XBool direct, const int *attrib_list);
using PFN_glXDestroyContext = void (*)(XDisplay *dpy, GLXContext ctx);
using PFN_glXMakeCurrent = XBool (*)(XDisplay *dpy, GLXDrawable drawable, GLXContext ctx);
using PFN_glXMakeContextCurrent = XBool (*)(XDisplay *dpy, GLXDrawable draw, GLXDrawable read, GLXContext ctx);
using PFN_glXSwapBuffers = void (*)(XDisplay *dpy, GLXDrawable drawable);
using PFN_glXSwapIntervalEXT = void (*)(XDisplay *dpy, GLXDrawable drawable, int interval);
using PFN_glXQueryExtension = XBool (*)(XDisplay *dpy, int *error_base, int *event_base);
using PFN_glXQueryVersion = XBool (*)(XDisplay *dpy, int *major, int *minor);
using PFN_glXQueryExtensionsString = const char *(*)(XDisplay * dpy, int screen);
using PFN_glXGetCurrentContext = GLXContext (*)(void);
using PFN_glXGetCurrentDrawable = GLXDrawable (*)(void);

using PFN_glXCreatePbuffer = GLXPbuffer (*)(XDisplay *dpy, GLXFBConfig config, const int *attrib_list);
using PFN_glXDestroyPbuffer = void (*)(XDisplay *dpy, GLXPbuffer pbuf);

inline constexpr int GLX_PBUFFER_WIDTH = 0x8041;
inline constexpr int GLX_PBUFFER_HEIGHT = 0x8040;
inline constexpr int GLX_PRESERVED_CONTENTS = 0x801B;
inline constexpr int GLX_LARGEST_PBUFFER = 0x801C;

};      // namespace gl
};      // namespace gfx
};      // namespace micron
