//  Copyright (c) 2024- David Lucius Severus
//
//  Distributed under the Boost Software License, Version 1.0.
//  See accompanying file LICENSE_1_0.txt or copy at
//  http://www.boost.org/LICENSE_1_0.txt
//
//  *** AUTOGENERATED FILE; do not hand-edit; regenerate via:
//        python3 tools/gl_xml_gen/gen_gl.py ***

#pragma once

#include "__gl_types.hpp"

namespace micron
{
namespace gfx
{
namespace gl
{

// PFN<NAME>PROC typedefs for every GL 4.6 core entry point

using PFNGLCULLFACEPROC = void (*)(GLenum mode);
using PFNGLFRONTFACEPROC = void (*)(GLenum mode);
using PFNGLHINTPROC = void (*)(GLenum target, GLenum mode);
using PFNGLLINEWIDTHPROC = void (*)(GLfloat width);
using PFNGLPOINTSIZEPROC = void (*)(GLfloat size);
using PFNGLPOLYGONMODEPROC = void (*)(GLenum face, GLenum mode);
using PFNGLSCISSORPROC = void (*)(GLint x, GLint y, GLsizei width, GLsizei height);
using PFNGLTEXPARAMETERFPROC = void (*)(GLenum target, GLenum pname, GLfloat param);
using PFNGLTEXPARAMETERFVPROC = void (*)(GLenum target, GLenum pname, const GLfloat *params);
using PFNGLTEXPARAMETERIPROC = void (*)(GLenum target, GLenum pname, GLint param);
using PFNGLTEXPARAMETERIVPROC = void (*)(GLenum target, GLenum pname, const GLint *params);
using PFNGLTEXIMAGE1DPROC = void (*)(GLenum target, GLint level, GLint internalformat, GLsizei width, GLint border, GLenum format,
                                     GLenum type, const void *pixels);
using PFNGLTEXIMAGE2DPROC = void (*)(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border,
                                     GLenum format, GLenum type, const void *pixels);
using PFNGLDRAWBUFFERPROC = void (*)(GLenum buf);
using PFNGLCLEARPROC = void (*)(GLbitfield mask);
using PFNGLCLEARCOLORPROC = void (*)(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
using PFNGLCLEARSTENCILPROC = void (*)(GLint s);
using PFNGLCLEARDEPTHPROC = void (*)(GLdouble depth);
using PFNGLSTENCILMASKPROC = void (*)(GLuint mask);
using PFNGLCOLORMASKPROC = void (*)(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha);
using PFNGLDEPTHMASKPROC = void (*)(GLboolean flag);
using PFNGLDISABLEPROC = void (*)(GLenum cap);
using PFNGLENABLEPROC = void (*)(GLenum cap);
using PFNGLFINISHPROC = void (*)(void);
using PFNGLFLUSHPROC = void (*)(void);
using PFNGLBLENDFUNCPROC = void (*)(GLenum sfactor, GLenum dfactor);
using PFNGLLOGICOPPROC = void (*)(GLenum opcode);
using PFNGLSTENCILFUNCPROC = void (*)(GLenum func, GLint ref, GLuint mask);
using PFNGLSTENCILOPPROC = void (*)(GLenum fail, GLenum zfail, GLenum zpass);
using PFNGLDEPTHFUNCPROC = void (*)(GLenum func);
using PFNGLPIXELSTOREFPROC = void (*)(GLenum pname, GLfloat param);
using PFNGLPIXELSTOREIPROC = void (*)(GLenum pname, GLint param);
using PFNGLREADBUFFERPROC = void (*)(GLenum src);
using PFNGLREADPIXELSPROC = void (*)(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, void *pixels);
using PFNGLGETBOOLEANVPROC = void (*)(GLenum pname, GLboolean *data);
using PFNGLGETDOUBLEVPROC = void (*)(GLenum pname, GLdouble *data);
using PFNGLGETERRORPROC = GLenum (*)(void);
using PFNGLGETFLOATVPROC = void (*)(GLenum pname, GLfloat *data);
using PFNGLGETINTEGERVPROC = void (*)(GLenum pname, GLint *data);
using PFNGLGETSTRINGPROC = const GLubyte *(*)(GLenum name);
using PFNGLGETTEXIMAGEPROC = void (*)(GLenum target, GLint level, GLenum format, GLenum type, void *pixels);
using PFNGLGETTEXPARAMETERFVPROC = void (*)(GLenum target, GLenum pname, GLfloat *params);
using PFNGLGETTEXPARAMETERIVPROC = void (*)(GLenum target, GLenum pname, GLint *params);
using PFNGLGETTEXLEVELPARAMETERFVPROC = void (*)(GLenum target, GLint level, GLenum pname, GLfloat *params);
using PFNGLGETTEXLEVELPARAMETERIVPROC = void (*)(GLenum target, GLint level, GLenum pname, GLint *params);
using PFNGLISENABLEDPROC = GLboolean (*)(GLenum cap);
using PFNGLDEPTHRANGEPROC = void (*)(GLdouble n, GLdouble f);
using PFNGLVIEWPORTPROC = void (*)(GLint x, GLint y, GLsizei width, GLsizei height);
using PFNGLDRAWARRAYSPROC = void (*)(GLenum mode, GLint first, GLsizei count);
using PFNGLDRAWELEMENTSPROC = void (*)(GLenum mode, GLsizei count, GLenum type, const void *indices);
using PFNGLGETPOINTERVPROC = void (*)(GLenum pname, void **params);
using PFNGLPOLYGONOFFSETPROC = void (*)(GLfloat factor, GLfloat units);
using PFNGLCOPYTEXIMAGE1DPROC = void (*)(GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLint border);
using PFNGLCOPYTEXIMAGE2DPROC
    = void (*)(GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border);
using PFNGLCOPYTEXSUBIMAGE1DPROC = void (*)(GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width);
using PFNGLCOPYTEXSUBIMAGE2DPROC
    = void (*)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height);
using PFNGLTEXSUBIMAGE1DPROC
    = void (*)(GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const void *pixels);
using PFNGLTEXSUBIMAGE2DPROC = void (*)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height,
                                        GLenum format, GLenum type, const void *pixels);
using PFNGLBINDTEXTUREPROC = void (*)(GLenum target, GLuint texture);
using PFNGLDELETETEXTURESPROC = void (*)(GLsizei n, const GLuint *textures);
using PFNGLGENTEXTURESPROC = void (*)(GLsizei n, GLuint *textures);
using PFNGLISTEXTUREPROC = GLboolean (*)(GLuint texture);
using PFNGLDRAWRANGEELEMENTSPROC = void (*)(GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const void *indices);
using PFNGLTEXIMAGE3DPROC = void (*)(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLsizei depth,
                                     GLint border, GLenum format, GLenum type, const void *pixels);
using PFNGLTEXSUBIMAGE3DPROC = void (*)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width,
                                        GLsizei height, GLsizei depth, GLenum format, GLenum type, const void *pixels);
using PFNGLCOPYTEXSUBIMAGE3DPROC
    = void (*)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height);
using PFNGLACTIVETEXTUREPROC = void (*)(GLenum texture);
using PFNGLSAMPLECOVERAGEPROC = void (*)(GLfloat value, GLboolean invert);
using PFNGLCOMPRESSEDTEXIMAGE3DPROC = void (*)(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height,
                                               GLsizei depth, GLint border, GLsizei imageSize, const void *data);
using PFNGLCOMPRESSEDTEXIMAGE2DPROC = void (*)(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height,
                                               GLint border, GLsizei imageSize, const void *data);
using PFNGLCOMPRESSEDTEXIMAGE1DPROC
    = void (*)(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLint border, GLsizei imageSize, const void *data);
using PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC = void (*)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width,
                                                  GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const void *data);
using PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC = void (*)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height,
                                                  GLenum format, GLsizei imageSize, const void *data);
using PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC
    = void (*)(GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLsizei imageSize, const void *data);
using PFNGLGETCOMPRESSEDTEXIMAGEPROC = void (*)(GLenum target, GLint level, void *img);
using PFNGLBLENDFUNCSEPARATEPROC = void (*)(GLenum sfactorRGB, GLenum dfactorRGB, GLenum sfactorAlpha, GLenum dfactorAlpha);
using PFNGLMULTIDRAWARRAYSPROC = void (*)(GLenum mode, const GLint *first, const GLsizei *count, GLsizei drawcount);
using PFNGLMULTIDRAWELEMENTSPROC = void (*)(GLenum mode, const GLsizei *count, GLenum type, const void *const *indices, GLsizei drawcount);
using PFNGLPOINTPARAMETERFPROC = void (*)(GLenum pname, GLfloat param);
using PFNGLPOINTPARAMETERFVPROC = void (*)(GLenum pname, const GLfloat *params);
using PFNGLPOINTPARAMETERIPROC = void (*)(GLenum pname, GLint param);
using PFNGLPOINTPARAMETERIVPROC = void (*)(GLenum pname, const GLint *params);
using PFNGLBLENDCOLORPROC = void (*)(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
using PFNGLBLENDEQUATIONPROC = void (*)(GLenum mode);
using PFNGLGENQUERIESPROC = void (*)(GLsizei n, GLuint *ids);
using PFNGLDELETEQUERIESPROC = void (*)(GLsizei n, const GLuint *ids);
using PFNGLISQUERYPROC = GLboolean (*)(GLuint id);
using PFNGLBEGINQUERYPROC = void (*)(GLenum target, GLuint id);
using PFNGLENDQUERYPROC = void (*)(GLenum target);
using PFNGLGETQUERYIVPROC = void (*)(GLenum target, GLenum pname, GLint *params);
using PFNGLGETQUERYOBJECTIVPROC = void (*)(GLuint id, GLenum pname, GLint *params);
using PFNGLGETQUERYOBJECTUIVPROC = void (*)(GLuint id, GLenum pname, GLuint *params);
using PFNGLBINDBUFFERPROC = void (*)(GLenum target, GLuint buffer);
using PFNGLDELETEBUFFERSPROC = void (*)(GLsizei n, const GLuint *buffers);
using PFNGLGENBUFFERSPROC = void (*)(GLsizei n, GLuint *buffers);
using PFNGLISBUFFERPROC = GLboolean (*)(GLuint buffer);
using PFNGLBUFFERDATAPROC = void (*)(GLenum target, GLsizeiptr size, const void *data, GLenum usage);
using PFNGLBUFFERSUBDATAPROC = void (*)(GLenum target, GLintptr offset, GLsizeiptr size, const void *data);
using PFNGLGETBUFFERSUBDATAPROC = void (*)(GLenum target, GLintptr offset, GLsizeiptr size, void *data);
using PFNGLMAPBUFFERPROC = void *(*)(GLenum target, GLenum access);
using PFNGLUNMAPBUFFERPROC = GLboolean (*)(GLenum target);
using PFNGLGETBUFFERPARAMETERIVPROC = void (*)(GLenum target, GLenum pname, GLint *params);
using PFNGLGETBUFFERPOINTERVPROC = void (*)(GLenum target, GLenum pname, void **params);
using PFNGLBLENDEQUATIONSEPARATEPROC = void (*)(GLenum modeRGB, GLenum modeAlpha);
using PFNGLDRAWBUFFERSPROC = void (*)(GLsizei n, const GLenum *bufs);
using PFNGLSTENCILOPSEPARATEPROC = void (*)(GLenum face, GLenum sfail, GLenum dpfail, GLenum dppass);
using PFNGLSTENCILFUNCSEPARATEPROC = void (*)(GLenum face, GLenum func, GLint ref, GLuint mask);
using PFNGLSTENCILMASKSEPARATEPROC = void (*)(GLenum face, GLuint mask);
using PFNGLATTACHSHADERPROC = void (*)(GLuint program, GLuint shader);
using PFNGLBINDATTRIBLOCATIONPROC = void (*)(GLuint program, GLuint index, const GLchar *name);
using PFNGLCOMPILESHADERPROC = void (*)(GLuint shader);
using PFNGLCREATEPROGRAMPROC = GLuint (*)(void);
using PFNGLCREATESHADERPROC = GLuint (*)(GLenum type);
using PFNGLDELETEPROGRAMPROC = void (*)(GLuint program);
using PFNGLDELETESHADERPROC = void (*)(GLuint shader);
using PFNGLDETACHSHADERPROC = void (*)(GLuint program, GLuint shader);
using PFNGLDISABLEVERTEXATTRIBARRAYPROC = void (*)(GLuint index);
using PFNGLENABLEVERTEXATTRIBARRAYPROC = void (*)(GLuint index);
using PFNGLGETACTIVEATTRIBPROC
    = void (*)(GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLint *size, GLenum *type, GLchar *name);
using PFNGLGETACTIVEUNIFORMPROC
    = void (*)(GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLint *size, GLenum *type, GLchar *name);
using PFNGLGETATTACHEDSHADERSPROC = void (*)(GLuint program, GLsizei maxCount, GLsizei *count, GLuint *shaders);
using PFNGLGETATTRIBLOCATIONPROC = GLint (*)(GLuint program, const GLchar *name);
using PFNGLGETPROGRAMIVPROC = void (*)(GLuint program, GLenum pname, GLint *params);
using PFNGLGETPROGRAMINFOLOGPROC = void (*)(GLuint program, GLsizei bufSize, GLsizei *length, GLchar *infoLog);
using PFNGLGETSHADERIVPROC = void (*)(GLuint shader, GLenum pname, GLint *params);
using PFNGLGETSHADERINFOLOGPROC = void (*)(GLuint shader, GLsizei bufSize, GLsizei *length, GLchar *infoLog);
using PFNGLGETSHADERSOURCEPROC = void (*)(GLuint shader, GLsizei bufSize, GLsizei *length, GLchar *source);
using PFNGLGETUNIFORMLOCATIONPROC = GLint (*)(GLuint program, const GLchar *name);
using PFNGLGETUNIFORMFVPROC = void (*)(GLuint program, GLint location, GLfloat *params);
using PFNGLGETUNIFORMIVPROC = void (*)(GLuint program, GLint location, GLint *params);
using PFNGLGETVERTEXATTRIBDVPROC = void (*)(GLuint index, GLenum pname, GLdouble *params);
using PFNGLGETVERTEXATTRIBFVPROC = void (*)(GLuint index, GLenum pname, GLfloat *params);
using PFNGLGETVERTEXATTRIBIVPROC = void (*)(GLuint index, GLenum pname, GLint *params);
using PFNGLGETVERTEXATTRIBPOINTERVPROC = void (*)(GLuint index, GLenum pname, void **pointer);
using PFNGLISPROGRAMPROC = GLboolean (*)(GLuint program);
using PFNGLISSHADERPROC = GLboolean (*)(GLuint shader);
using PFNGLLINKPROGRAMPROC = void (*)(GLuint program);
using PFNGLSHADERSOURCEPROC = void (*)(GLuint shader, GLsizei count, const GLchar *const *string, const GLint *length);
using PFNGLUSEPROGRAMPROC = void (*)(GLuint program);
using PFNGLUNIFORM1FPROC = void (*)(GLint location, GLfloat v0);
using PFNGLUNIFORM2FPROC = void (*)(GLint location, GLfloat v0, GLfloat v1);
using PFNGLUNIFORM3FPROC = void (*)(GLint location, GLfloat v0, GLfloat v1, GLfloat v2);
using PFNGLUNIFORM4FPROC = void (*)(GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3);
using PFNGLUNIFORM1IPROC = void (*)(GLint location, GLint v0);
using PFNGLUNIFORM2IPROC = void (*)(GLint location, GLint v0, GLint v1);
using PFNGLUNIFORM3IPROC = void (*)(GLint location, GLint v0, GLint v1, GLint v2);
using PFNGLUNIFORM4IPROC = void (*)(GLint location, GLint v0, GLint v1, GLint v2, GLint v3);
using PFNGLUNIFORM1FVPROC = void (*)(GLint location, GLsizei count, const GLfloat *value);
using PFNGLUNIFORM2FVPROC = void (*)(GLint location, GLsizei count, const GLfloat *value);
using PFNGLUNIFORM3FVPROC = void (*)(GLint location, GLsizei count, const GLfloat *value);
using PFNGLUNIFORM4FVPROC = void (*)(GLint location, GLsizei count, const GLfloat *value);
using PFNGLUNIFORM1IVPROC = void (*)(GLint location, GLsizei count, const GLint *value);
using PFNGLUNIFORM2IVPROC = void (*)(GLint location, GLsizei count, const GLint *value);
using PFNGLUNIFORM3IVPROC = void (*)(GLint location, GLsizei count, const GLint *value);
using PFNGLUNIFORM4IVPROC = void (*)(GLint location, GLsizei count, const GLint *value);
using PFNGLUNIFORMMATRIX2FVPROC = void (*)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
using PFNGLUNIFORMMATRIX3FVPROC = void (*)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
using PFNGLUNIFORMMATRIX4FVPROC = void (*)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
using PFNGLVALIDATEPROGRAMPROC = void (*)(GLuint program);
using PFNGLVERTEXATTRIB1DPROC = void (*)(GLuint index, GLdouble x);
using PFNGLVERTEXATTRIB1DVPROC = void (*)(GLuint index, const GLdouble *v);
using PFNGLVERTEXATTRIB1FPROC = void (*)(GLuint index, GLfloat x);
using PFNGLVERTEXATTRIB1FVPROC = void (*)(GLuint index, const GLfloat *v);
using PFNGLVERTEXATTRIB1SPROC = void (*)(GLuint index, GLshort x);
using PFNGLVERTEXATTRIB1SVPROC = void (*)(GLuint index, const GLshort *v);
using PFNGLVERTEXATTRIB2DPROC = void (*)(GLuint index, GLdouble x, GLdouble y);
using PFNGLVERTEXATTRIB2DVPROC = void (*)(GLuint index, const GLdouble *v);
using PFNGLVERTEXATTRIB2FPROC = void (*)(GLuint index, GLfloat x, GLfloat y);
using PFNGLVERTEXATTRIB2FVPROC = void (*)(GLuint index, const GLfloat *v);
using PFNGLVERTEXATTRIB2SPROC = void (*)(GLuint index, GLshort x, GLshort y);
using PFNGLVERTEXATTRIB2SVPROC = void (*)(GLuint index, const GLshort *v);
using PFNGLVERTEXATTRIB3DPROC = void (*)(GLuint index, GLdouble x, GLdouble y, GLdouble z);
using PFNGLVERTEXATTRIB3DVPROC = void (*)(GLuint index, const GLdouble *v);
using PFNGLVERTEXATTRIB3FPROC = void (*)(GLuint index, GLfloat x, GLfloat y, GLfloat z);
using PFNGLVERTEXATTRIB3FVPROC = void (*)(GLuint index, const GLfloat *v);
using PFNGLVERTEXATTRIB3SPROC = void (*)(GLuint index, GLshort x, GLshort y, GLshort z);
using PFNGLVERTEXATTRIB3SVPROC = void (*)(GLuint index, const GLshort *v);
using PFNGLVERTEXATTRIB4NBVPROC = void (*)(GLuint index, const GLbyte *v);
using PFNGLVERTEXATTRIB4NIVPROC = void (*)(GLuint index, const GLint *v);
using PFNGLVERTEXATTRIB4NSVPROC = void (*)(GLuint index, const GLshort *v);
using PFNGLVERTEXATTRIB4NUBPROC = void (*)(GLuint index, GLubyte x, GLubyte y, GLubyte z, GLubyte w);
using PFNGLVERTEXATTRIB4NUBVPROC = void (*)(GLuint index, const GLubyte *v);
using PFNGLVERTEXATTRIB4NUIVPROC = void (*)(GLuint index, const GLuint *v);
using PFNGLVERTEXATTRIB4NUSVPROC = void (*)(GLuint index, const GLushort *v);
using PFNGLVERTEXATTRIB4BVPROC = void (*)(GLuint index, const GLbyte *v);
using PFNGLVERTEXATTRIB4DPROC = void (*)(GLuint index, GLdouble x, GLdouble y, GLdouble z, GLdouble w);
using PFNGLVERTEXATTRIB4DVPROC = void (*)(GLuint index, const GLdouble *v);
using PFNGLVERTEXATTRIB4FPROC = void (*)(GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w);
using PFNGLVERTEXATTRIB4FVPROC = void (*)(GLuint index, const GLfloat *v);
using PFNGLVERTEXATTRIB4IVPROC = void (*)(GLuint index, const GLint *v);
using PFNGLVERTEXATTRIB4SPROC = void (*)(GLuint index, GLshort x, GLshort y, GLshort z, GLshort w);
using PFNGLVERTEXATTRIB4SVPROC = void (*)(GLuint index, const GLshort *v);
using PFNGLVERTEXATTRIB4UBVPROC = void (*)(GLuint index, const GLubyte *v);
using PFNGLVERTEXATTRIB4UIVPROC = void (*)(GLuint index, const GLuint *v);
using PFNGLVERTEXATTRIB4USVPROC = void (*)(GLuint index, const GLushort *v);
using PFNGLVERTEXATTRIBPOINTERPROC
    = void (*)(GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const void *pointer);
using PFNGLUNIFORMMATRIX2X3FVPROC = void (*)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
using PFNGLUNIFORMMATRIX3X2FVPROC = void (*)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
using PFNGLUNIFORMMATRIX2X4FVPROC = void (*)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
using PFNGLUNIFORMMATRIX4X2FVPROC = void (*)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
using PFNGLUNIFORMMATRIX3X4FVPROC = void (*)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
using PFNGLUNIFORMMATRIX4X3FVPROC = void (*)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
using PFNGLCOLORMASKIPROC = void (*)(GLuint index, GLboolean r, GLboolean g, GLboolean b, GLboolean a);
using PFNGLGETBOOLEANI_VPROC = void (*)(GLenum target, GLuint index, GLboolean *data);
using PFNGLGETINTEGERI_VPROC = void (*)(GLenum target, GLuint index, GLint *data);
using PFNGLENABLEIPROC = void (*)(GLenum target, GLuint index);
using PFNGLDISABLEIPROC = void (*)(GLenum target, GLuint index);
using PFNGLISENABLEDIPROC = GLboolean (*)(GLenum target, GLuint index);
using PFNGLBEGINTRANSFORMFEEDBACKPROC = void (*)(GLenum primitiveMode);
using PFNGLENDTRANSFORMFEEDBACKPROC = void (*)(void);
using PFNGLBINDBUFFERRANGEPROC = void (*)(GLenum target, GLuint index, GLuint buffer, GLintptr offset, GLsizeiptr size);
using PFNGLBINDBUFFERBASEPROC = void (*)(GLenum target, GLuint index, GLuint buffer);
using PFNGLTRANSFORMFEEDBACKVARYINGSPROC = void (*)(GLuint program, GLsizei count, const GLchar *const *varyings, GLenum bufferMode);
using PFNGLGETTRANSFORMFEEDBACKVARYINGPROC
    = void (*)(GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLsizei *size, GLenum *type, GLchar *name);
using PFNGLCLAMPCOLORPROC = void (*)(GLenum target, GLenum clamp);
using PFNGLBEGINCONDITIONALRENDERPROC = void (*)(GLuint id, GLenum mode);
using PFNGLENDCONDITIONALRENDERPROC = void (*)(void);
using PFNGLVERTEXATTRIBIPOINTERPROC = void (*)(GLuint index, GLint size, GLenum type, GLsizei stride, const void *pointer);
using PFNGLGETVERTEXATTRIBIIVPROC = void (*)(GLuint index, GLenum pname, GLint *params);
using PFNGLGETVERTEXATTRIBIUIVPROC = void (*)(GLuint index, GLenum pname, GLuint *params);
using PFNGLVERTEXATTRIBI1IPROC = void (*)(GLuint index, GLint x);
using PFNGLVERTEXATTRIBI2IPROC = void (*)(GLuint index, GLint x, GLint y);
using PFNGLVERTEXATTRIBI3IPROC = void (*)(GLuint index, GLint x, GLint y, GLint z);
using PFNGLVERTEXATTRIBI4IPROC = void (*)(GLuint index, GLint x, GLint y, GLint z, GLint w);
using PFNGLVERTEXATTRIBI1UIPROC = void (*)(GLuint index, GLuint x);
using PFNGLVERTEXATTRIBI2UIPROC = void (*)(GLuint index, GLuint x, GLuint y);
using PFNGLVERTEXATTRIBI3UIPROC = void (*)(GLuint index, GLuint x, GLuint y, GLuint z);
using PFNGLVERTEXATTRIBI4UIPROC = void (*)(GLuint index, GLuint x, GLuint y, GLuint z, GLuint w);
using PFNGLVERTEXATTRIBI1IVPROC = void (*)(GLuint index, const GLint *v);
using PFNGLVERTEXATTRIBI2IVPROC = void (*)(GLuint index, const GLint *v);
using PFNGLVERTEXATTRIBI3IVPROC = void (*)(GLuint index, const GLint *v);
using PFNGLVERTEXATTRIBI4IVPROC = void (*)(GLuint index, const GLint *v);
using PFNGLVERTEXATTRIBI1UIVPROC = void (*)(GLuint index, const GLuint *v);
using PFNGLVERTEXATTRIBI2UIVPROC = void (*)(GLuint index, const GLuint *v);
using PFNGLVERTEXATTRIBI3UIVPROC = void (*)(GLuint index, const GLuint *v);
using PFNGLVERTEXATTRIBI4UIVPROC = void (*)(GLuint index, const GLuint *v);
using PFNGLVERTEXATTRIBI4BVPROC = void (*)(GLuint index, const GLbyte *v);
using PFNGLVERTEXATTRIBI4SVPROC = void (*)(GLuint index, const GLshort *v);
using PFNGLVERTEXATTRIBI4UBVPROC = void (*)(GLuint index, const GLubyte *v);
using PFNGLVERTEXATTRIBI4USVPROC = void (*)(GLuint index, const GLushort *v);
using PFNGLGETUNIFORMUIVPROC = void (*)(GLuint program, GLint location, GLuint *params);
using PFNGLBINDFRAGDATALOCATIONPROC = void (*)(GLuint program, GLuint color, const GLchar *name);
using PFNGLGETFRAGDATALOCATIONPROC = GLint (*)(GLuint program, const GLchar *name);
using PFNGLUNIFORM1UIPROC = void (*)(GLint location, GLuint v0);
using PFNGLUNIFORM2UIPROC = void (*)(GLint location, GLuint v0, GLuint v1);
using PFNGLUNIFORM3UIPROC = void (*)(GLint location, GLuint v0, GLuint v1, GLuint v2);
using PFNGLUNIFORM4UIPROC = void (*)(GLint location, GLuint v0, GLuint v1, GLuint v2, GLuint v3);
using PFNGLUNIFORM1UIVPROC = void (*)(GLint location, GLsizei count, const GLuint *value);
using PFNGLUNIFORM2UIVPROC = void (*)(GLint location, GLsizei count, const GLuint *value);
using PFNGLUNIFORM3UIVPROC = void (*)(GLint location, GLsizei count, const GLuint *value);
using PFNGLUNIFORM4UIVPROC = void (*)(GLint location, GLsizei count, const GLuint *value);
using PFNGLTEXPARAMETERIIVPROC = void (*)(GLenum target, GLenum pname, const GLint *params);
using PFNGLTEXPARAMETERIUIVPROC = void (*)(GLenum target, GLenum pname, const GLuint *params);
using PFNGLGETTEXPARAMETERIIVPROC = void (*)(GLenum target, GLenum pname, GLint *params);
using PFNGLGETTEXPARAMETERIUIVPROC = void (*)(GLenum target, GLenum pname, GLuint *params);
using PFNGLCLEARBUFFERIVPROC = void (*)(GLenum buffer, GLint drawbuffer, const GLint *value);
using PFNGLCLEARBUFFERUIVPROC = void (*)(GLenum buffer, GLint drawbuffer, const GLuint *value);
using PFNGLCLEARBUFFERFVPROC = void (*)(GLenum buffer, GLint drawbuffer, const GLfloat *value);
using PFNGLCLEARBUFFERFIPROC = void (*)(GLenum buffer, GLint drawbuffer, GLfloat depth, GLint stencil);
using PFNGLGETSTRINGIPROC = const GLubyte *(*)(GLenum name, GLuint index);
using PFNGLISRENDERBUFFERPROC = GLboolean (*)(GLuint renderbuffer);
using PFNGLBINDRENDERBUFFERPROC = void (*)(GLenum target, GLuint renderbuffer);
using PFNGLDELETERENDERBUFFERSPROC = void (*)(GLsizei n, const GLuint *renderbuffers);
using PFNGLGENRENDERBUFFERSPROC = void (*)(GLsizei n, GLuint *renderbuffers);
using PFNGLRENDERBUFFERSTORAGEPROC = void (*)(GLenum target, GLenum internalformat, GLsizei width, GLsizei height);
using PFNGLGETRENDERBUFFERPARAMETERIVPROC = void (*)(GLenum target, GLenum pname, GLint *params);
using PFNGLISFRAMEBUFFERPROC = GLboolean (*)(GLuint framebuffer);
using PFNGLBINDFRAMEBUFFERPROC = void (*)(GLenum target, GLuint framebuffer);
using PFNGLDELETEFRAMEBUFFERSPROC = void (*)(GLsizei n, const GLuint *framebuffers);
using PFNGLGENFRAMEBUFFERSPROC = void (*)(GLsizei n, GLuint *framebuffers);
using PFNGLCHECKFRAMEBUFFERSTATUSPROC = GLenum (*)(GLenum target);
using PFNGLFRAMEBUFFERTEXTURE1DPROC = void (*)(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level);
using PFNGLFRAMEBUFFERTEXTURE2DPROC = void (*)(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level);
using PFNGLFRAMEBUFFERTEXTURE3DPROC
    = void (*)(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level, GLint zoffset);
using PFNGLFRAMEBUFFERRENDERBUFFERPROC = void (*)(GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer);
using PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC = void (*)(GLenum target, GLenum attachment, GLenum pname, GLint *params);
using PFNGLGENERATEMIPMAPPROC = void (*)(GLenum target);
using PFNGLBLITFRAMEBUFFERPROC = void (*)(GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1,
                                          GLint dstY1, GLbitfield mask, GLenum filter);
using PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC
    = void (*)(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height);
using PFNGLFRAMEBUFFERTEXTURELAYERPROC = void (*)(GLenum target, GLenum attachment, GLuint texture, GLint level, GLint layer);
using PFNGLMAPBUFFERRANGEPROC = void *(*)(GLenum target, GLintptr offset, GLsizeiptr length, GLbitfield access);
using PFNGLFLUSHMAPPEDBUFFERRANGEPROC = void (*)(GLenum target, GLintptr offset, GLsizeiptr length);
using PFNGLBINDVERTEXARRAYPROC = void (*)(GLuint array);
using PFNGLDELETEVERTEXARRAYSPROC = void (*)(GLsizei n, const GLuint *arrays);
using PFNGLGENVERTEXARRAYSPROC = void (*)(GLsizei n, GLuint *arrays);
using PFNGLISVERTEXARRAYPROC = GLboolean (*)(GLuint array);
using PFNGLDRAWARRAYSINSTANCEDPROC = void (*)(GLenum mode, GLint first, GLsizei count, GLsizei instancecount);
using PFNGLDRAWELEMENTSINSTANCEDPROC = void (*)(GLenum mode, GLsizei count, GLenum type, const void *indices, GLsizei instancecount);
using PFNGLTEXBUFFERPROC = void (*)(GLenum target, GLenum internalformat, GLuint buffer);
using PFNGLPRIMITIVERESTARTINDEXPROC = void (*)(GLuint index);
using PFNGLCOPYBUFFERSUBDATAPROC
    = void (*)(GLenum readTarget, GLenum writeTarget, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size);
using PFNGLGETUNIFORMINDICESPROC
    = void (*)(GLuint program, GLsizei uniformCount, const GLchar *const *uniformNames, GLuint *uniformIndices);
using PFNGLGETACTIVEUNIFORMSIVPROC
    = void (*)(GLuint program, GLsizei uniformCount, const GLuint *uniformIndices, GLenum pname, GLint *params);
using PFNGLGETACTIVEUNIFORMNAMEPROC = void (*)(GLuint program, GLuint uniformIndex, GLsizei bufSize, GLsizei *length, GLchar *uniformName);
using PFNGLGETUNIFORMBLOCKINDEXPROC = GLuint (*)(GLuint program, const GLchar *uniformBlockName);
using PFNGLGETACTIVEUNIFORMBLOCKIVPROC = void (*)(GLuint program, GLuint uniformBlockIndex, GLenum pname, GLint *params);
using PFNGLGETACTIVEUNIFORMBLOCKNAMEPROC
    = void (*)(GLuint program, GLuint uniformBlockIndex, GLsizei bufSize, GLsizei *length, GLchar *uniformBlockName);
using PFNGLUNIFORMBLOCKBINDINGPROC = void (*)(GLuint program, GLuint uniformBlockIndex, GLuint uniformBlockBinding);
using PFNGLDRAWELEMENTSBASEVERTEXPROC = void (*)(GLenum mode, GLsizei count, GLenum type, const void *indices, GLint basevertex);
using PFNGLDRAWRANGEELEMENTSBASEVERTEXPROC
    = void (*)(GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const void *indices, GLint basevertex);
using PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXPROC
    = void (*)(GLenum mode, GLsizei count, GLenum type, const void *indices, GLsizei instancecount, GLint basevertex);
using PFNGLMULTIDRAWELEMENTSBASEVERTEXPROC
    = void (*)(GLenum mode, const GLsizei *count, GLenum type, const void *const *indices, GLsizei drawcount, const GLint *basevertex);
using PFNGLPROVOKINGVERTEXPROC = void (*)(GLenum mode);
using PFNGLFENCESYNCPROC = GLsync (*)(GLenum condition, GLbitfield flags);
using PFNGLISSYNCPROC = GLboolean (*)(GLsync sync);
using PFNGLDELETESYNCPROC = void (*)(GLsync sync);
using PFNGLCLIENTWAITSYNCPROC = GLenum (*)(GLsync sync, GLbitfield flags, GLuint64 timeout);
using PFNGLWAITSYNCPROC = void (*)(GLsync sync, GLbitfield flags, GLuint64 timeout);
using PFNGLGETINTEGER64VPROC = void (*)(GLenum pname, GLint64 *data);
using PFNGLGETSYNCIVPROC = void (*)(GLsync sync, GLenum pname, GLsizei count, GLsizei *length, GLint *values);
using PFNGLGETINTEGER64I_VPROC = void (*)(GLenum target, GLuint index, GLint64 *data);
using PFNGLGETBUFFERPARAMETERI64VPROC = void (*)(GLenum target, GLenum pname, GLint64 *params);
using PFNGLFRAMEBUFFERTEXTUREPROC = void (*)(GLenum target, GLenum attachment, GLuint texture, GLint level);
using PFNGLTEXIMAGE2DMULTISAMPLEPROC
    = void (*)(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLboolean fixedsamplelocations);
using PFNGLTEXIMAGE3DMULTISAMPLEPROC = void (*)(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height,
                                                GLsizei depth, GLboolean fixedsamplelocations);
using PFNGLGETMULTISAMPLEFVPROC = void (*)(GLenum pname, GLuint index, GLfloat *val);
using PFNGLSAMPLEMASKIPROC = void (*)(GLuint maskNumber, GLbitfield mask);
using PFNGLBINDFRAGDATALOCATIONINDEXEDPROC = void (*)(GLuint program, GLuint colorNumber, GLuint index, const GLchar *name);
using PFNGLGETFRAGDATAINDEXPROC = GLint (*)(GLuint program, const GLchar *name);
using PFNGLGENSAMPLERSPROC = void (*)(GLsizei count, GLuint *samplers);
using PFNGLDELETESAMPLERSPROC = void (*)(GLsizei count, const GLuint *samplers);
using PFNGLISSAMPLERPROC = GLboolean (*)(GLuint sampler);
using PFNGLBINDSAMPLERPROC = void (*)(GLuint unit, GLuint sampler);
using PFNGLSAMPLERPARAMETERIPROC = void (*)(GLuint sampler, GLenum pname, GLint param);
using PFNGLSAMPLERPARAMETERIVPROC = void (*)(GLuint sampler, GLenum pname, const GLint *param);
using PFNGLSAMPLERPARAMETERFPROC = void (*)(GLuint sampler, GLenum pname, GLfloat param);
using PFNGLSAMPLERPARAMETERFVPROC = void (*)(GLuint sampler, GLenum pname, const GLfloat *param);
using PFNGLSAMPLERPARAMETERIIVPROC = void (*)(GLuint sampler, GLenum pname, const GLint *param);
using PFNGLSAMPLERPARAMETERIUIVPROC = void (*)(GLuint sampler, GLenum pname, const GLuint *param);
using PFNGLGETSAMPLERPARAMETERIVPROC = void (*)(GLuint sampler, GLenum pname, GLint *params);
using PFNGLGETSAMPLERPARAMETERIIVPROC = void (*)(GLuint sampler, GLenum pname, GLint *params);
using PFNGLGETSAMPLERPARAMETERFVPROC = void (*)(GLuint sampler, GLenum pname, GLfloat *params);
using PFNGLGETSAMPLERPARAMETERIUIVPROC = void (*)(GLuint sampler, GLenum pname, GLuint *params);
using PFNGLQUERYCOUNTERPROC = void (*)(GLuint id, GLenum target);
using PFNGLGETQUERYOBJECTI64VPROC = void (*)(GLuint id, GLenum pname, GLint64 *params);
using PFNGLGETQUERYOBJECTUI64VPROC = void (*)(GLuint id, GLenum pname, GLuint64 *params);
using PFNGLVERTEXATTRIBDIVISORPROC = void (*)(GLuint index, GLuint divisor);
using PFNGLVERTEXATTRIBP1UIPROC = void (*)(GLuint index, GLenum type, GLboolean normalized, GLuint value);
using PFNGLVERTEXATTRIBP1UIVPROC = void (*)(GLuint index, GLenum type, GLboolean normalized, const GLuint *value);
using PFNGLVERTEXATTRIBP2UIPROC = void (*)(GLuint index, GLenum type, GLboolean normalized, GLuint value);
using PFNGLVERTEXATTRIBP2UIVPROC = void (*)(GLuint index, GLenum type, GLboolean normalized, const GLuint *value);
using PFNGLVERTEXATTRIBP3UIPROC = void (*)(GLuint index, GLenum type, GLboolean normalized, GLuint value);
using PFNGLVERTEXATTRIBP3UIVPROC = void (*)(GLuint index, GLenum type, GLboolean normalized, const GLuint *value);
using PFNGLVERTEXATTRIBP4UIPROC = void (*)(GLuint index, GLenum type, GLboolean normalized, GLuint value);
using PFNGLVERTEXATTRIBP4UIVPROC = void (*)(GLuint index, GLenum type, GLboolean normalized, const GLuint *value);
using PFNGLMINSAMPLESHADINGPROC = void (*)(GLfloat value);
using PFNGLBLENDEQUATIONIPROC = void (*)(GLuint buf, GLenum mode);
using PFNGLBLENDEQUATIONSEPARATEIPROC = void (*)(GLuint buf, GLenum modeRGB, GLenum modeAlpha);
using PFNGLBLENDFUNCIPROC = void (*)(GLuint buf, GLenum src, GLenum dst);
using PFNGLBLENDFUNCSEPARATEIPROC = void (*)(GLuint buf, GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha);
using PFNGLDRAWARRAYSINDIRECTPROC = void (*)(GLenum mode, const void *indirect);
using PFNGLDRAWELEMENTSINDIRECTPROC = void (*)(GLenum mode, GLenum type, const void *indirect);
using PFNGLUNIFORM1DPROC = void (*)(GLint location, GLdouble x);
using PFNGLUNIFORM2DPROC = void (*)(GLint location, GLdouble x, GLdouble y);
using PFNGLUNIFORM3DPROC = void (*)(GLint location, GLdouble x, GLdouble y, GLdouble z);
using PFNGLUNIFORM4DPROC = void (*)(GLint location, GLdouble x, GLdouble y, GLdouble z, GLdouble w);
using PFNGLUNIFORM1DVPROC = void (*)(GLint location, GLsizei count, const GLdouble *value);
using PFNGLUNIFORM2DVPROC = void (*)(GLint location, GLsizei count, const GLdouble *value);
using PFNGLUNIFORM3DVPROC = void (*)(GLint location, GLsizei count, const GLdouble *value);
using PFNGLUNIFORM4DVPROC = void (*)(GLint location, GLsizei count, const GLdouble *value);
using PFNGLUNIFORMMATRIX2DVPROC = void (*)(GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
using PFNGLUNIFORMMATRIX3DVPROC = void (*)(GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
using PFNGLUNIFORMMATRIX4DVPROC = void (*)(GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
using PFNGLUNIFORMMATRIX2X3DVPROC = void (*)(GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
using PFNGLUNIFORMMATRIX2X4DVPROC = void (*)(GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
using PFNGLUNIFORMMATRIX3X2DVPROC = void (*)(GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
using PFNGLUNIFORMMATRIX3X4DVPROC = void (*)(GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
using PFNGLUNIFORMMATRIX4X2DVPROC = void (*)(GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
using PFNGLUNIFORMMATRIX4X3DVPROC = void (*)(GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
using PFNGLGETUNIFORMDVPROC = void (*)(GLuint program, GLint location, GLdouble *params);
using PFNGLGETSUBROUTINEUNIFORMLOCATIONPROC = GLint (*)(GLuint program, GLenum shadertype, const GLchar *name);
using PFNGLGETSUBROUTINEINDEXPROC = GLuint (*)(GLuint program, GLenum shadertype, const GLchar *name);
using PFNGLGETACTIVESUBROUTINEUNIFORMIVPROC = void (*)(GLuint program, GLenum shadertype, GLuint index, GLenum pname, GLint *values);
using PFNGLGETACTIVESUBROUTINEUNIFORMNAMEPROC
    = void (*)(GLuint program, GLenum shadertype, GLuint index, GLsizei bufSize, GLsizei *length, GLchar *name);
using PFNGLGETACTIVESUBROUTINENAMEPROC
    = void (*)(GLuint program, GLenum shadertype, GLuint index, GLsizei bufSize, GLsizei *length, GLchar *name);
using PFNGLUNIFORMSUBROUTINESUIVPROC = void (*)(GLenum shadertype, GLsizei count, const GLuint *indices);
using PFNGLGETUNIFORMSUBROUTINEUIVPROC = void (*)(GLenum shadertype, GLint location, GLuint *params);
using PFNGLGETPROGRAMSTAGEIVPROC = void (*)(GLuint program, GLenum shadertype, GLenum pname, GLint *values);
using PFNGLPATCHPARAMETERIPROC = void (*)(GLenum pname, GLint value);
using PFNGLPATCHPARAMETERFVPROC = void (*)(GLenum pname, const GLfloat *values);
using PFNGLBINDTRANSFORMFEEDBACKPROC = void (*)(GLenum target, GLuint id);
using PFNGLDELETETRANSFORMFEEDBACKSPROC = void (*)(GLsizei n, const GLuint *ids);
using PFNGLGENTRANSFORMFEEDBACKSPROC = void (*)(GLsizei n, GLuint *ids);
using PFNGLISTRANSFORMFEEDBACKPROC = GLboolean (*)(GLuint id);
using PFNGLPAUSETRANSFORMFEEDBACKPROC = void (*)(void);
using PFNGLRESUMETRANSFORMFEEDBACKPROC = void (*)(void);
using PFNGLDRAWTRANSFORMFEEDBACKPROC = void (*)(GLenum mode, GLuint id);
using PFNGLDRAWTRANSFORMFEEDBACKSTREAMPROC = void (*)(GLenum mode, GLuint id, GLuint stream);
using PFNGLBEGINQUERYINDEXEDPROC = void (*)(GLenum target, GLuint index, GLuint id);
using PFNGLENDQUERYINDEXEDPROC = void (*)(GLenum target, GLuint index);
using PFNGLGETQUERYINDEXEDIVPROC = void (*)(GLenum target, GLuint index, GLenum pname, GLint *params);
using PFNGLRELEASESHADERCOMPILERPROC = void (*)(void);
using PFNGLSHADERBINARYPROC = void (*)(GLsizei count, const GLuint *shaders, GLenum binaryFormat, const void *binary, GLsizei length);
using PFNGLGETSHADERPRECISIONFORMATPROC = void (*)(GLenum shadertype, GLenum precisiontype, GLint *range, GLint *precision);
using PFNGLDEPTHRANGEFPROC = void (*)(GLfloat n, GLfloat f);
using PFNGLCLEARDEPTHFPROC = void (*)(GLfloat d);
using PFNGLGETPROGRAMBINARYPROC = void (*)(GLuint program, GLsizei bufSize, GLsizei *length, GLenum *binaryFormat, void *binary);
using PFNGLPROGRAMBINARYPROC = void (*)(GLuint program, GLenum binaryFormat, const void *binary, GLsizei length);
using PFNGLPROGRAMPARAMETERIPROC = void (*)(GLuint program, GLenum pname, GLint value);
using PFNGLUSEPROGRAMSTAGESPROC = void (*)(GLuint pipeline, GLbitfield stages, GLuint program);
using PFNGLACTIVESHADERPROGRAMPROC = void (*)(GLuint pipeline, GLuint program);
using PFNGLCREATESHADERPROGRAMVPROC = GLuint (*)(GLenum type, GLsizei count, const GLchar *const *strings);
using PFNGLBINDPROGRAMPIPELINEPROC = void (*)(GLuint pipeline);
using PFNGLDELETEPROGRAMPIPELINESPROC = void (*)(GLsizei n, const GLuint *pipelines);
using PFNGLGENPROGRAMPIPELINESPROC = void (*)(GLsizei n, GLuint *pipelines);
using PFNGLISPROGRAMPIPELINEPROC = GLboolean (*)(GLuint pipeline);
using PFNGLGETPROGRAMPIPELINEIVPROC = void (*)(GLuint pipeline, GLenum pname, GLint *params);
using PFNGLPROGRAMUNIFORM1IPROC = void (*)(GLuint program, GLint location, GLint v0);
using PFNGLPROGRAMUNIFORM1IVPROC = void (*)(GLuint program, GLint location, GLsizei count, const GLint *value);
using PFNGLPROGRAMUNIFORM1FPROC = void (*)(GLuint program, GLint location, GLfloat v0);
using PFNGLPROGRAMUNIFORM1FVPROC = void (*)(GLuint program, GLint location, GLsizei count, const GLfloat *value);
using PFNGLPROGRAMUNIFORM1DPROC = void (*)(GLuint program, GLint location, GLdouble v0);
using PFNGLPROGRAMUNIFORM1DVPROC = void (*)(GLuint program, GLint location, GLsizei count, const GLdouble *value);
using PFNGLPROGRAMUNIFORM1UIPROC = void (*)(GLuint program, GLint location, GLuint v0);
using PFNGLPROGRAMUNIFORM1UIVPROC = void (*)(GLuint program, GLint location, GLsizei count, const GLuint *value);
using PFNGLPROGRAMUNIFORM2IPROC = void (*)(GLuint program, GLint location, GLint v0, GLint v1);
using PFNGLPROGRAMUNIFORM2IVPROC = void (*)(GLuint program, GLint location, GLsizei count, const GLint *value);
using PFNGLPROGRAMUNIFORM2FPROC = void (*)(GLuint program, GLint location, GLfloat v0, GLfloat v1);
using PFNGLPROGRAMUNIFORM2FVPROC = void (*)(GLuint program, GLint location, GLsizei count, const GLfloat *value);
using PFNGLPROGRAMUNIFORM2DPROC = void (*)(GLuint program, GLint location, GLdouble v0, GLdouble v1);
using PFNGLPROGRAMUNIFORM2DVPROC = void (*)(GLuint program, GLint location, GLsizei count, const GLdouble *value);
using PFNGLPROGRAMUNIFORM2UIPROC = void (*)(GLuint program, GLint location, GLuint v0, GLuint v1);
using PFNGLPROGRAMUNIFORM2UIVPROC = void (*)(GLuint program, GLint location, GLsizei count, const GLuint *value);
using PFNGLPROGRAMUNIFORM3IPROC = void (*)(GLuint program, GLint location, GLint v0, GLint v1, GLint v2);
using PFNGLPROGRAMUNIFORM3IVPROC = void (*)(GLuint program, GLint location, GLsizei count, const GLint *value);
using PFNGLPROGRAMUNIFORM3FPROC = void (*)(GLuint program, GLint location, GLfloat v0, GLfloat v1, GLfloat v2);
using PFNGLPROGRAMUNIFORM3FVPROC = void (*)(GLuint program, GLint location, GLsizei count, const GLfloat *value);
using PFNGLPROGRAMUNIFORM3DPROC = void (*)(GLuint program, GLint location, GLdouble v0, GLdouble v1, GLdouble v2);
using PFNGLPROGRAMUNIFORM3DVPROC = void (*)(GLuint program, GLint location, GLsizei count, const GLdouble *value);
using PFNGLPROGRAMUNIFORM3UIPROC = void (*)(GLuint program, GLint location, GLuint v0, GLuint v1, GLuint v2);
using PFNGLPROGRAMUNIFORM3UIVPROC = void (*)(GLuint program, GLint location, GLsizei count, const GLuint *value);
using PFNGLPROGRAMUNIFORM4IPROC = void (*)(GLuint program, GLint location, GLint v0, GLint v1, GLint v2, GLint v3);
using PFNGLPROGRAMUNIFORM4IVPROC = void (*)(GLuint program, GLint location, GLsizei count, const GLint *value);
using PFNGLPROGRAMUNIFORM4FPROC = void (*)(GLuint program, GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3);
using PFNGLPROGRAMUNIFORM4FVPROC = void (*)(GLuint program, GLint location, GLsizei count, const GLfloat *value);
using PFNGLPROGRAMUNIFORM4DPROC = void (*)(GLuint program, GLint location, GLdouble v0, GLdouble v1, GLdouble v2, GLdouble v3);
using PFNGLPROGRAMUNIFORM4DVPROC = void (*)(GLuint program, GLint location, GLsizei count, const GLdouble *value);
using PFNGLPROGRAMUNIFORM4UIPROC = void (*)(GLuint program, GLint location, GLuint v0, GLuint v1, GLuint v2, GLuint v3);
using PFNGLPROGRAMUNIFORM4UIVPROC = void (*)(GLuint program, GLint location, GLsizei count, const GLuint *value);
using PFNGLPROGRAMUNIFORMMATRIX2FVPROC = void (*)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
using PFNGLPROGRAMUNIFORMMATRIX3FVPROC = void (*)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
using PFNGLPROGRAMUNIFORMMATRIX4FVPROC = void (*)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
using PFNGLPROGRAMUNIFORMMATRIX2DVPROC
    = void (*)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
using PFNGLPROGRAMUNIFORMMATRIX3DVPROC
    = void (*)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
using PFNGLPROGRAMUNIFORMMATRIX4DVPROC
    = void (*)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
using PFNGLPROGRAMUNIFORMMATRIX2X3FVPROC
    = void (*)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
using PFNGLPROGRAMUNIFORMMATRIX3X2FVPROC
    = void (*)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
using PFNGLPROGRAMUNIFORMMATRIX2X4FVPROC
    = void (*)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
using PFNGLPROGRAMUNIFORMMATRIX4X2FVPROC
    = void (*)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
using PFNGLPROGRAMUNIFORMMATRIX3X4FVPROC
    = void (*)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
using PFNGLPROGRAMUNIFORMMATRIX4X3FVPROC
    = void (*)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
using PFNGLPROGRAMUNIFORMMATRIX2X3DVPROC
    = void (*)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
using PFNGLPROGRAMUNIFORMMATRIX3X2DVPROC
    = void (*)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
using PFNGLPROGRAMUNIFORMMATRIX2X4DVPROC
    = void (*)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
using PFNGLPROGRAMUNIFORMMATRIX4X2DVPROC
    = void (*)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
using PFNGLPROGRAMUNIFORMMATRIX3X4DVPROC
    = void (*)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
using PFNGLPROGRAMUNIFORMMATRIX4X3DVPROC
    = void (*)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
using PFNGLVALIDATEPROGRAMPIPELINEPROC = void (*)(GLuint pipeline);
using PFNGLGETPROGRAMPIPELINEINFOLOGPROC = void (*)(GLuint pipeline, GLsizei bufSize, GLsizei *length, GLchar *infoLog);
using PFNGLVERTEXATTRIBL1DPROC = void (*)(GLuint index, GLdouble x);
using PFNGLVERTEXATTRIBL2DPROC = void (*)(GLuint index, GLdouble x, GLdouble y);
using PFNGLVERTEXATTRIBL3DPROC = void (*)(GLuint index, GLdouble x, GLdouble y, GLdouble z);
using PFNGLVERTEXATTRIBL4DPROC = void (*)(GLuint index, GLdouble x, GLdouble y, GLdouble z, GLdouble w);
using PFNGLVERTEXATTRIBL1DVPROC = void (*)(GLuint index, const GLdouble *v);
using PFNGLVERTEXATTRIBL2DVPROC = void (*)(GLuint index, const GLdouble *v);
using PFNGLVERTEXATTRIBL3DVPROC = void (*)(GLuint index, const GLdouble *v);
using PFNGLVERTEXATTRIBL4DVPROC = void (*)(GLuint index, const GLdouble *v);
using PFNGLVERTEXATTRIBLPOINTERPROC = void (*)(GLuint index, GLint size, GLenum type, GLsizei stride, const void *pointer);
using PFNGLGETVERTEXATTRIBLDVPROC = void (*)(GLuint index, GLenum pname, GLdouble *params);
using PFNGLVIEWPORTARRAYVPROC = void (*)(GLuint first, GLsizei count, const GLfloat *v);
using PFNGLVIEWPORTINDEXEDFPROC = void (*)(GLuint index, GLfloat x, GLfloat y, GLfloat w, GLfloat h);
using PFNGLVIEWPORTINDEXEDFVPROC = void (*)(GLuint index, const GLfloat *v);
using PFNGLSCISSORARRAYVPROC = void (*)(GLuint first, GLsizei count, const GLint *v);
using PFNGLSCISSORINDEXEDPROC = void (*)(GLuint index, GLint left, GLint bottom, GLsizei width, GLsizei height);
using PFNGLSCISSORINDEXEDVPROC = void (*)(GLuint index, const GLint *v);
using PFNGLDEPTHRANGEARRAYVPROC = void (*)(GLuint first, GLsizei count, const GLdouble *v);
using PFNGLDEPTHRANGEINDEXEDPROC = void (*)(GLuint index, GLdouble n, GLdouble f);
using PFNGLGETFLOATI_VPROC = void (*)(GLenum target, GLuint index, GLfloat *data);
using PFNGLGETDOUBLEI_VPROC = void (*)(GLenum target, GLuint index, GLdouble *data);
using PFNGLDRAWARRAYSINSTANCEDBASEINSTANCEPROC
    = void (*)(GLenum mode, GLint first, GLsizei count, GLsizei instancecount, GLuint baseinstance);
using PFNGLDRAWELEMENTSINSTANCEDBASEINSTANCEPROC
    = void (*)(GLenum mode, GLsizei count, GLenum type, const void *indices, GLsizei instancecount, GLuint baseinstance);
using PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXBASEINSTANCEPROC
    = void (*)(GLenum mode, GLsizei count, GLenum type, const void *indices, GLsizei instancecount, GLint basevertex, GLuint baseinstance);
using PFNGLGETINTERNALFORMATIVPROC = void (*)(GLenum target, GLenum internalformat, GLenum pname, GLsizei count, GLint *params);
using PFNGLGETACTIVEATOMICCOUNTERBUFFERIVPROC = void (*)(GLuint program, GLuint bufferIndex, GLenum pname, GLint *params);
using PFNGLBINDIMAGETEXTUREPROC
    = void (*)(GLuint unit, GLuint texture, GLint level, GLboolean layered, GLint layer, GLenum access, GLenum format);
using PFNGLMEMORYBARRIERPROC = void (*)(GLbitfield barriers);
using PFNGLTEXSTORAGE1DPROC = void (*)(GLenum target, GLsizei levels, GLenum internalformat, GLsizei width);
using PFNGLTEXSTORAGE2DPROC = void (*)(GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height);
using PFNGLTEXSTORAGE3DPROC = void (*)(GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth);
using PFNGLDRAWTRANSFORMFEEDBACKINSTANCEDPROC = void (*)(GLenum mode, GLuint id, GLsizei instancecount);
using PFNGLDRAWTRANSFORMFEEDBACKSTREAMINSTANCEDPROC = void (*)(GLenum mode, GLuint id, GLuint stream, GLsizei instancecount);
using PFNGLCLEARBUFFERDATAPROC = void (*)(GLenum target, GLenum internalformat, GLenum format, GLenum type, const void *data);
using PFNGLCLEARBUFFERSUBDATAPROC
    = void (*)(GLenum target, GLenum internalformat, GLintptr offset, GLsizeiptr size, GLenum format, GLenum type, const void *data);
using PFNGLDISPATCHCOMPUTEPROC = void (*)(GLuint num_groups_x, GLuint num_groups_y, GLuint num_groups_z);
using PFNGLDISPATCHCOMPUTEINDIRECTPROC = void (*)(GLintptr indirect);
using PFNGLCOPYIMAGESUBDATAPROC
    = void (*)(GLuint srcName, GLenum srcTarget, GLint srcLevel, GLint srcX, GLint srcY, GLint srcZ, GLuint dstName, GLenum dstTarget,
               GLint dstLevel, GLint dstX, GLint dstY, GLint dstZ, GLsizei srcWidth, GLsizei srcHeight, GLsizei srcDepth);
using PFNGLFRAMEBUFFERPARAMETERIPROC = void (*)(GLenum target, GLenum pname, GLint param);
using PFNGLGETFRAMEBUFFERPARAMETERIVPROC = void (*)(GLenum target, GLenum pname, GLint *params);
using PFNGLGETINTERNALFORMATI64VPROC = void (*)(GLenum target, GLenum internalformat, GLenum pname, GLsizei count, GLint64 *params);
using PFNGLINVALIDATETEXSUBIMAGEPROC
    = void (*)(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth);
using PFNGLINVALIDATETEXIMAGEPROC = void (*)(GLuint texture, GLint level);
using PFNGLINVALIDATEBUFFERSUBDATAPROC = void (*)(GLuint buffer, GLintptr offset, GLsizeiptr length);
using PFNGLINVALIDATEBUFFERDATAPROC = void (*)(GLuint buffer);
using PFNGLINVALIDATEFRAMEBUFFERPROC = void (*)(GLenum target, GLsizei numAttachments, const GLenum *attachments);
using PFNGLINVALIDATESUBFRAMEBUFFERPROC
    = void (*)(GLenum target, GLsizei numAttachments, const GLenum *attachments, GLint x, GLint y, GLsizei width, GLsizei height);
using PFNGLMULTIDRAWARRAYSINDIRECTPROC = void (*)(GLenum mode, const void *indirect, GLsizei drawcount, GLsizei stride);
using PFNGLMULTIDRAWELEMENTSINDIRECTPROC = void (*)(GLenum mode, GLenum type, const void *indirect, GLsizei drawcount, GLsizei stride);
using PFNGLGETPROGRAMINTERFACEIVPROC = void (*)(GLuint program, GLenum programInterface, GLenum pname, GLint *params);
using PFNGLGETPROGRAMRESOURCEINDEXPROC = GLuint (*)(GLuint program, GLenum programInterface, const GLchar *name);
using PFNGLGETPROGRAMRESOURCENAMEPROC
    = void (*)(GLuint program, GLenum programInterface, GLuint index, GLsizei bufSize, GLsizei *length, GLchar *name);
using PFNGLGETPROGRAMRESOURCEIVPROC = void (*)(GLuint program, GLenum programInterface, GLuint index, GLsizei propCount,
                                               const GLenum *props, GLsizei count, GLsizei *length, GLint *params);
using PFNGLGETPROGRAMRESOURCELOCATIONPROC = GLint (*)(GLuint program, GLenum programInterface, const GLchar *name);
using PFNGLGETPROGRAMRESOURCELOCATIONINDEXPROC = GLint (*)(GLuint program, GLenum programInterface, const GLchar *name);
using PFNGLSHADERSTORAGEBLOCKBINDINGPROC = void (*)(GLuint program, GLuint storageBlockIndex, GLuint storageBlockBinding);
using PFNGLTEXBUFFERRANGEPROC = void (*)(GLenum target, GLenum internalformat, GLuint buffer, GLintptr offset, GLsizeiptr size);
using PFNGLTEXSTORAGE2DMULTISAMPLEPROC
    = void (*)(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLboolean fixedsamplelocations);
using PFNGLTEXSTORAGE3DMULTISAMPLEPROC = void (*)(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height,
                                                  GLsizei depth, GLboolean fixedsamplelocations);
using PFNGLTEXTUREVIEWPROC = void (*)(GLuint texture, GLenum target, GLuint origtexture, GLenum internalformat, GLuint minlevel,
                                      GLuint numlevels, GLuint minlayer, GLuint numlayers);
using PFNGLBINDVERTEXBUFFERPROC = void (*)(GLuint bindingindex, GLuint buffer, GLintptr offset, GLsizei stride);
using PFNGLVERTEXATTRIBFORMATPROC = void (*)(GLuint attribindex, GLint size, GLenum type, GLboolean normalized, GLuint relativeoffset);
using PFNGLVERTEXATTRIBIFORMATPROC = void (*)(GLuint attribindex, GLint size, GLenum type, GLuint relativeoffset);
using PFNGLVERTEXATTRIBLFORMATPROC = void (*)(GLuint attribindex, GLint size, GLenum type, GLuint relativeoffset);
using PFNGLVERTEXATTRIBBINDINGPROC = void (*)(GLuint attribindex, GLuint bindingindex);
using PFNGLVERTEXBINDINGDIVISORPROC = void (*)(GLuint bindingindex, GLuint divisor);
using PFNGLDEBUGMESSAGECONTROLPROC
    = void (*)(GLenum source, GLenum type, GLenum severity, GLsizei count, const GLuint *ids, GLboolean enabled);
using PFNGLDEBUGMESSAGEINSERTPROC = void (*)(GLenum source, GLenum type, GLuint id, GLenum severity, GLsizei length, const GLchar *buf);
using PFNGLDEBUGMESSAGECALLBACKPROC = void (*)(GLDEBUGPROC callback, const void *userParam);
using PFNGLGETDEBUGMESSAGELOGPROC = GLuint (*)(GLuint count, GLsizei bufSize, GLenum *sources, GLenum *types, GLuint *ids,
                                               GLenum *severities, GLsizei *lengths, GLchar *messageLog);
using PFNGLPUSHDEBUGGROUPPROC = void (*)(GLenum source, GLuint id, GLsizei length, const GLchar *message);
using PFNGLPOPDEBUGGROUPPROC = void (*)(void);
using PFNGLOBJECTLABELPROC = void (*)(GLenum identifier, GLuint name, GLsizei length, const GLchar *label);
using PFNGLGETOBJECTLABELPROC = void (*)(GLenum identifier, GLuint name, GLsizei bufSize, GLsizei *length, GLchar *label);
using PFNGLOBJECTPTRLABELPROC = void (*)(const void *ptr, GLsizei length, const GLchar *label);
using PFNGLGETOBJECTPTRLABELPROC = void (*)(const void *ptr, GLsizei bufSize, GLsizei *length, GLchar *label);
using PFNGLBUFFERSTORAGEPROC = void (*)(GLenum target, GLsizeiptr size, const void *data, GLbitfield flags);
using PFNGLCLEARTEXIMAGEPROC = void (*)(GLuint texture, GLint level, GLenum format, GLenum type, const void *data);
using PFNGLCLEARTEXSUBIMAGEPROC = void (*)(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width,
                                           GLsizei height, GLsizei depth, GLenum format, GLenum type, const void *data);
using PFNGLBINDBUFFERSBASEPROC = void (*)(GLenum target, GLuint first, GLsizei count, const GLuint *buffers);
using PFNGLBINDBUFFERSRANGEPROC
    = void (*)(GLenum target, GLuint first, GLsizei count, const GLuint *buffers, const GLintptr *offsets, const GLsizeiptr *sizes);
using PFNGLBINDTEXTURESPROC = void (*)(GLuint first, GLsizei count, const GLuint *textures);
using PFNGLBINDSAMPLERSPROC = void (*)(GLuint first, GLsizei count, const GLuint *samplers);
using PFNGLBINDIMAGETEXTURESPROC = void (*)(GLuint first, GLsizei count, const GLuint *textures);
using PFNGLBINDVERTEXBUFFERSPROC
    = void (*)(GLuint first, GLsizei count, const GLuint *buffers, const GLintptr *offsets, const GLsizei *strides);
using PFNGLCLIPCONTROLPROC = void (*)(GLenum origin, GLenum depth);
using PFNGLCREATETRANSFORMFEEDBACKSPROC = void (*)(GLsizei n, GLuint *ids);
using PFNGLTRANSFORMFEEDBACKBUFFERBASEPROC = void (*)(GLuint xfb, GLuint index, GLuint buffer);
using PFNGLTRANSFORMFEEDBACKBUFFERRANGEPROC = void (*)(GLuint xfb, GLuint index, GLuint buffer, GLintptr offset, GLsizeiptr size);
using PFNGLGETTRANSFORMFEEDBACKIVPROC = void (*)(GLuint xfb, GLenum pname, GLint *param);
using PFNGLGETTRANSFORMFEEDBACKI_VPROC = void (*)(GLuint xfb, GLenum pname, GLuint index, GLint *param);
using PFNGLGETTRANSFORMFEEDBACKI64_VPROC = void (*)(GLuint xfb, GLenum pname, GLuint index, GLint64 *param);
using PFNGLCREATEBUFFERSPROC = void (*)(GLsizei n, GLuint *buffers);
using PFNGLNAMEDBUFFERSTORAGEPROC = void (*)(GLuint buffer, GLsizeiptr size, const void *data, GLbitfield flags);
using PFNGLNAMEDBUFFERDATAPROC = void (*)(GLuint buffer, GLsizeiptr size, const void *data, GLenum usage);
using PFNGLNAMEDBUFFERSUBDATAPROC = void (*)(GLuint buffer, GLintptr offset, GLsizeiptr size, const void *data);
using PFNGLCOPYNAMEDBUFFERSUBDATAPROC
    = void (*)(GLuint readBuffer, GLuint writeBuffer, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size);
using PFNGLCLEARNAMEDBUFFERDATAPROC = void (*)(GLuint buffer, GLenum internalformat, GLenum format, GLenum type, const void *data);
using PFNGLCLEARNAMEDBUFFERSUBDATAPROC
    = void (*)(GLuint buffer, GLenum internalformat, GLintptr offset, GLsizeiptr size, GLenum format, GLenum type, const void *data);
using PFNGLMAPNAMEDBUFFERPROC = void *(*)(GLuint buffer, GLenum access);
using PFNGLMAPNAMEDBUFFERRANGEPROC = void *(*)(GLuint buffer, GLintptr offset, GLsizeiptr length, GLbitfield access);
using PFNGLUNMAPNAMEDBUFFERPROC = GLboolean (*)(GLuint buffer);
using PFNGLFLUSHMAPPEDNAMEDBUFFERRANGEPROC = void (*)(GLuint buffer, GLintptr offset, GLsizeiptr length);
using PFNGLGETNAMEDBUFFERPARAMETERIVPROC = void (*)(GLuint buffer, GLenum pname, GLint *params);
using PFNGLGETNAMEDBUFFERPARAMETERI64VPROC = void (*)(GLuint buffer, GLenum pname, GLint64 *params);
using PFNGLGETNAMEDBUFFERPOINTERVPROC = void (*)(GLuint buffer, GLenum pname, void **params);
using PFNGLGETNAMEDBUFFERSUBDATAPROC = void (*)(GLuint buffer, GLintptr offset, GLsizeiptr size, void *data);
using PFNGLCREATEFRAMEBUFFERSPROC = void (*)(GLsizei n, GLuint *framebuffers);
using PFNGLNAMEDFRAMEBUFFERRENDERBUFFERPROC
    = void (*)(GLuint framebuffer, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer);
using PFNGLNAMEDFRAMEBUFFERPARAMETERIPROC = void (*)(GLuint framebuffer, GLenum pname, GLint param);
using PFNGLNAMEDFRAMEBUFFERTEXTUREPROC = void (*)(GLuint framebuffer, GLenum attachment, GLuint texture, GLint level);
using PFNGLNAMEDFRAMEBUFFERTEXTURELAYERPROC = void (*)(GLuint framebuffer, GLenum attachment, GLuint texture, GLint level, GLint layer);
using PFNGLNAMEDFRAMEBUFFERDRAWBUFFERPROC = void (*)(GLuint framebuffer, GLenum buf);
using PFNGLNAMEDFRAMEBUFFERDRAWBUFFERSPROC = void (*)(GLuint framebuffer, GLsizei n, const GLenum *bufs);
using PFNGLNAMEDFRAMEBUFFERREADBUFFERPROC = void (*)(GLuint framebuffer, GLenum src);
using PFNGLINVALIDATENAMEDFRAMEBUFFERDATAPROC = void (*)(GLuint framebuffer, GLsizei numAttachments, const GLenum *attachments);
using PFNGLINVALIDATENAMEDFRAMEBUFFERSUBDATAPROC
    = void (*)(GLuint framebuffer, GLsizei numAttachments, const GLenum *attachments, GLint x, GLint y, GLsizei width, GLsizei height);
using PFNGLCLEARNAMEDFRAMEBUFFERIVPROC = void (*)(GLuint framebuffer, GLenum buffer, GLint drawbuffer, const GLint *value);
using PFNGLCLEARNAMEDFRAMEBUFFERUIVPROC = void (*)(GLuint framebuffer, GLenum buffer, GLint drawbuffer, const GLuint *value);
using PFNGLCLEARNAMEDFRAMEBUFFERFVPROC = void (*)(GLuint framebuffer, GLenum buffer, GLint drawbuffer, const GLfloat *value);
using PFNGLCLEARNAMEDFRAMEBUFFERFIPROC = void (*)(GLuint framebuffer, GLenum buffer, GLint drawbuffer, GLfloat depth, GLint stencil);
using PFNGLBLITNAMEDFRAMEBUFFERPROC
    = void (*)(GLuint readFramebuffer, GLuint drawFramebuffer, GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0,
               GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter);
using PFNGLCHECKNAMEDFRAMEBUFFERSTATUSPROC = GLenum (*)(GLuint framebuffer, GLenum target);
using PFNGLGETNAMEDFRAMEBUFFERPARAMETERIVPROC = void (*)(GLuint framebuffer, GLenum pname, GLint *param);
using PFNGLGETNAMEDFRAMEBUFFERATTACHMENTPARAMETERIVPROC = void (*)(GLuint framebuffer, GLenum attachment, GLenum pname, GLint *params);
using PFNGLCREATERENDERBUFFERSPROC = void (*)(GLsizei n, GLuint *renderbuffers);
using PFNGLNAMEDRENDERBUFFERSTORAGEPROC = void (*)(GLuint renderbuffer, GLenum internalformat, GLsizei width, GLsizei height);
using PFNGLNAMEDRENDERBUFFERSTORAGEMULTISAMPLEPROC
    = void (*)(GLuint renderbuffer, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height);
using PFNGLGETNAMEDRENDERBUFFERPARAMETERIVPROC = void (*)(GLuint renderbuffer, GLenum pname, GLint *params);
using PFNGLCREATETEXTURESPROC = void (*)(GLenum target, GLsizei n, GLuint *textures);
using PFNGLTEXTUREBUFFERPROC = void (*)(GLuint texture, GLenum internalformat, GLuint buffer);
using PFNGLTEXTUREBUFFERRANGEPROC = void (*)(GLuint texture, GLenum internalformat, GLuint buffer, GLintptr offset, GLsizeiptr size);
using PFNGLTEXTURESTORAGE1DPROC = void (*)(GLuint texture, GLsizei levels, GLenum internalformat, GLsizei width);
using PFNGLTEXTURESTORAGE2DPROC = void (*)(GLuint texture, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height);
using PFNGLTEXTURESTORAGE3DPROC
    = void (*)(GLuint texture, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth);
using PFNGLTEXTURESTORAGE2DMULTISAMPLEPROC
    = void (*)(GLuint texture, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLboolean fixedsamplelocations);
using PFNGLTEXTURESTORAGE3DMULTISAMPLEPROC = void (*)(GLuint texture, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height,
                                                      GLsizei depth, GLboolean fixedsamplelocations);
using PFNGLTEXTURESUBIMAGE1DPROC
    = void (*)(GLuint texture, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const void *pixels);
using PFNGLTEXTURESUBIMAGE2DPROC = void (*)(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height,
                                            GLenum format, GLenum type, const void *pixels);
using PFNGLTEXTURESUBIMAGE3DPROC = void (*)(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width,
                                            GLsizei height, GLsizei depth, GLenum format, GLenum type, const void *pixels);
using PFNGLCOMPRESSEDTEXTURESUBIMAGE1DPROC
    = void (*)(GLuint texture, GLint level, GLint xoffset, GLsizei width, GLenum format, GLsizei imageSize, const void *data);
using PFNGLCOMPRESSEDTEXTURESUBIMAGE2DPROC = void (*)(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLsizei width,
                                                      GLsizei height, GLenum format, GLsizei imageSize, const void *data);
using PFNGLCOMPRESSEDTEXTURESUBIMAGE3DPROC
    = void (*)(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth,
               GLenum format, GLsizei imageSize, const void *data);
using PFNGLCOPYTEXTURESUBIMAGE1DPROC = void (*)(GLuint texture, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width);
using PFNGLCOPYTEXTURESUBIMAGE2DPROC
    = void (*)(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height);
using PFNGLCOPYTEXTURESUBIMAGE3DPROC
    = void (*)(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height);
using PFNGLTEXTUREPARAMETERFPROC = void (*)(GLuint texture, GLenum pname, GLfloat param);
using PFNGLTEXTUREPARAMETERFVPROC = void (*)(GLuint texture, GLenum pname, const GLfloat *param);
using PFNGLTEXTUREPARAMETERIPROC = void (*)(GLuint texture, GLenum pname, GLint param);
using PFNGLTEXTUREPARAMETERIIVPROC = void (*)(GLuint texture, GLenum pname, const GLint *params);
using PFNGLTEXTUREPARAMETERIUIVPROC = void (*)(GLuint texture, GLenum pname, const GLuint *params);
using PFNGLTEXTUREPARAMETERIVPROC = void (*)(GLuint texture, GLenum pname, const GLint *param);
using PFNGLGENERATETEXTUREMIPMAPPROC = void (*)(GLuint texture);
using PFNGLBINDTEXTUREUNITPROC = void (*)(GLuint unit, GLuint texture);
using PFNGLGETTEXTUREIMAGEPROC = void (*)(GLuint texture, GLint level, GLenum format, GLenum type, GLsizei bufSize, void *pixels);
using PFNGLGETCOMPRESSEDTEXTUREIMAGEPROC = void (*)(GLuint texture, GLint level, GLsizei bufSize, void *pixels);
using PFNGLGETTEXTURELEVELPARAMETERFVPROC = void (*)(GLuint texture, GLint level, GLenum pname, GLfloat *params);
using PFNGLGETTEXTURELEVELPARAMETERIVPROC = void (*)(GLuint texture, GLint level, GLenum pname, GLint *params);
using PFNGLGETTEXTUREPARAMETERFVPROC = void (*)(GLuint texture, GLenum pname, GLfloat *params);
using PFNGLGETTEXTUREPARAMETERIIVPROC = void (*)(GLuint texture, GLenum pname, GLint *params);
using PFNGLGETTEXTUREPARAMETERIUIVPROC = void (*)(GLuint texture, GLenum pname, GLuint *params);
using PFNGLGETTEXTUREPARAMETERIVPROC = void (*)(GLuint texture, GLenum pname, GLint *params);
using PFNGLCREATEVERTEXARRAYSPROC = void (*)(GLsizei n, GLuint *arrays);
using PFNGLDISABLEVERTEXARRAYATTRIBPROC = void (*)(GLuint vaobj, GLuint index);
using PFNGLENABLEVERTEXARRAYATTRIBPROC = void (*)(GLuint vaobj, GLuint index);
using PFNGLVERTEXARRAYELEMENTBUFFERPROC = void (*)(GLuint vaobj, GLuint buffer);
using PFNGLVERTEXARRAYVERTEXBUFFERPROC = void (*)(GLuint vaobj, GLuint bindingindex, GLuint buffer, GLintptr offset, GLsizei stride);
using PFNGLVERTEXARRAYVERTEXBUFFERSPROC
    = void (*)(GLuint vaobj, GLuint first, GLsizei count, const GLuint *buffers, const GLintptr *offsets, const GLsizei *strides);
using PFNGLVERTEXARRAYATTRIBBINDINGPROC = void (*)(GLuint vaobj, GLuint attribindex, GLuint bindingindex);
using PFNGLVERTEXARRAYATTRIBFORMATPROC
    = void (*)(GLuint vaobj, GLuint attribindex, GLint size, GLenum type, GLboolean normalized, GLuint relativeoffset);
using PFNGLVERTEXARRAYATTRIBIFORMATPROC = void (*)(GLuint vaobj, GLuint attribindex, GLint size, GLenum type, GLuint relativeoffset);
using PFNGLVERTEXARRAYATTRIBLFORMATPROC = void (*)(GLuint vaobj, GLuint attribindex, GLint size, GLenum type, GLuint relativeoffset);
using PFNGLVERTEXARRAYBINDINGDIVISORPROC = void (*)(GLuint vaobj, GLuint bindingindex, GLuint divisor);
using PFNGLGETVERTEXARRAYIVPROC = void (*)(GLuint vaobj, GLenum pname, GLint *param);
using PFNGLGETVERTEXARRAYINDEXEDIVPROC = void (*)(GLuint vaobj, GLuint index, GLenum pname, GLint *param);
using PFNGLGETVERTEXARRAYINDEXED64IVPROC = void (*)(GLuint vaobj, GLuint index, GLenum pname, GLint64 *param);
using PFNGLCREATESAMPLERSPROC = void (*)(GLsizei n, GLuint *samplers);
using PFNGLCREATEPROGRAMPIPELINESPROC = void (*)(GLsizei n, GLuint *pipelines);
using PFNGLCREATEQUERIESPROC = void (*)(GLenum target, GLsizei n, GLuint *ids);
using PFNGLGETQUERYBUFFEROBJECTI64VPROC = void (*)(GLuint id, GLuint buffer, GLenum pname, GLintptr offset);
using PFNGLGETQUERYBUFFEROBJECTIVPROC = void (*)(GLuint id, GLuint buffer, GLenum pname, GLintptr offset);
using PFNGLGETQUERYBUFFEROBJECTUI64VPROC = void (*)(GLuint id, GLuint buffer, GLenum pname, GLintptr offset);
using PFNGLGETQUERYBUFFEROBJECTUIVPROC = void (*)(GLuint id, GLuint buffer, GLenum pname, GLintptr offset);
using PFNGLMEMORYBARRIERBYREGIONPROC = void (*)(GLbitfield barriers);
using PFNGLGETTEXTURESUBIMAGEPROC = void (*)(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width,
                                             GLsizei height, GLsizei depth, GLenum format, GLenum type, GLsizei bufSize, void *pixels);
using PFNGLGETCOMPRESSEDTEXTURESUBIMAGEPROC = void (*)(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset,
                                                       GLsizei width, GLsizei height, GLsizei depth, GLsizei bufSize, void *pixels);
using PFNGLGETGRAPHICSRESETSTATUSPROC = GLenum (*)(void);
using PFNGLGETNCOMPRESSEDTEXIMAGEPROC = void (*)(GLenum target, GLint lod, GLsizei bufSize, void *pixels);
using PFNGLGETNTEXIMAGEPROC = void (*)(GLenum target, GLint level, GLenum format, GLenum type, GLsizei bufSize, void *pixels);
using PFNGLGETNUNIFORMDVPROC = void (*)(GLuint program, GLint location, GLsizei bufSize, GLdouble *params);
using PFNGLGETNUNIFORMFVPROC = void (*)(GLuint program, GLint location, GLsizei bufSize, GLfloat *params);
using PFNGLGETNUNIFORMIVPROC = void (*)(GLuint program, GLint location, GLsizei bufSize, GLint *params);
using PFNGLGETNUNIFORMUIVPROC = void (*)(GLuint program, GLint location, GLsizei bufSize, GLuint *params);
using PFNGLREADNPIXELSPROC
    = void (*)(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLsizei bufSize, void *data);
using PFNGLTEXTUREBARRIERPROC = void (*)(void);
using PFNGLSPECIALIZESHADERPROC = void (*)(GLuint shader, const GLchar *pEntryPoint, GLuint numSpecializationConstants,
                                           const GLuint *pConstantIndex, const GLuint *pConstantValue);
using PFNGLMULTIDRAWARRAYSINDIRECTCOUNTPROC
    = void (*)(GLenum mode, const void *indirect, GLintptr drawcount, GLsizei maxdrawcount, GLsizei stride);
using PFNGLMULTIDRAWELEMENTSINDIRECTCOUNTPROC
    = void (*)(GLenum mode, GLenum type, const void *indirect, GLintptr drawcount, GLsizei maxdrawcount, GLsizei stride);
using PFNGLPOLYGONOFFSETCLAMPPROC = void (*)(GLfloat factor, GLfloat units, GLfloat clamp);

}      // namespace gl
}      // namespace gfx
}      // namespace micron
