//  Copyright (c) 2024- David Lucius Severus
//
//  Distributed under the Boost Software License, Version 1.0.
//  See accompanying file LICENSE_1_0.txt or copy at
//  http://www.boost.org/LICENSE_1_0.txt
//
//  *** AUTOGENERATED FILE; do not hand-edit; regenerate via:
//        python3 tools/gl_xml_gen/gen_gl.py ***

#pragma once

#include "../../../bits/__arch.hpp"
#include "../../../types.hpp"

#if !defined(__micron_os_linux)
#error "micron::gl is linux-only"
#endif

namespace micron
{
namespace gfx
{
namespace gl
{

// autogenerated by tools/gl_xml_gen/gen_gl.py from /usr/include/GL/glcorearb.h

using GLvoid = void;
using GLenum = unsigned int;
using GLfloat = f32;
using GLint = int;
using GLsizei = int;
using GLbitfield = unsigned int;
using GLdouble = double;
using GLuint = unsigned int;
using GLboolean = unsigned char;
using GLubyte = u8;
using GLclampf = f32;
using GLclampd = double;
using GLsizeiptr = ssize_t;
using GLintptr = intptr_t;
using GLchar = char;
using GLshort = i16;
using GLbyte = i8;
using GLushort = u16;
using GLhalf = u16;
struct __GLsync;
using GLsync = __GLsync *;
using GLuint64 = u64;
using GLint64 = i64;
using GLDEBUGPROC
    = void (*)(GLenum source, GLenum type, GLuint id, GLenum severity, GLsizei length, const GLchar *message, const void *userParam);
using GLDEBUGPROCARB = GLDEBUGPROC;
using GLDEBUGPROCKHR = GLDEBUGPROC;

};      // namespace gl
};      // namespace gfx
};      // namespace micron
