//  Copyright (c) 2024- David Lucius Severus
//
//  Distributed under the Boost Software License, Version 1.0.
//  See accompanying file LICENSE_1_0.txt or copy at
//  http://www.boost.org/LICENSE_1_0.txt
#pragma once

#include "../../except.hpp"
#include "../../linux/dynamic.hpp"
#include "../../memory/cstring.hpp"
#include "../../types.hpp"

#include "__bits/__wayland_types.hpp"
#include "platform.hpp"
#include "wayland_xdg_shell.hpp"

// Wayland-client backend. Loads libwayland-client.so.0 and libwayland-egl.so.1
// via micron::dso and exposes the entry points the display + surface code
// will call.
//
// Window creation under Wayland flows through the xdg-shell protocol, which
// is NOT in libwayland-client — it's a separate XML protocol whose
// marshalling is normally generated by `wayland-scanner` from xdg-shell.xml.
// We hand-roll that marshalling in gl/platform/wayland_xdg_shell.hpp.

namespace micron
{
namespace gfx
{
namespace platform
{

struct wayland_lib_t {
  host_dso host;

  PFN_wl_display_connect wl_display_connect = nullptr;
  PFN_wl_display_connect_to_fd wl_display_connect_to_fd = nullptr;
  PFN_wl_display_disconnect wl_display_disconnect = nullptr;
  PFN_wl_display_get_fd wl_display_get_fd = nullptr;
  PFN_wl_display_dispatch wl_display_dispatch = nullptr;
  PFN_wl_display_dispatch_pending wl_display_dispatch_pending = nullptr;
  PFN_wl_display_roundtrip wl_display_roundtrip = nullptr;
  PFN_wl_display_flush wl_display_flush = nullptr;
  PFN_wl_display_prepare_read wl_display_prepare_read = nullptr;
  PFN_wl_display_read_events wl_display_read_events = nullptr;
  PFN_wl_display_get_registry wl_display_get_registry = nullptr;

  PFN_wl_proxy_marshal_flags wl_proxy_marshal_flags = nullptr;
  PFN_wl_proxy_marshal_array_flags wl_proxy_marshal_array_flags = nullptr;
  PFN_wl_proxy_add_listener wl_proxy_add_listener = nullptr;
  PFN_wl_proxy_destroy wl_proxy_destroy = nullptr;
  PFN_wl_proxy_get_user_data wl_proxy_get_user_data = nullptr;
  PFN_wl_proxy_set_user_data wl_proxy_set_user_data = nullptr;
  PFN_wl_proxy_get_version wl_proxy_get_version = nullptr;
  PFN_wl_proxy_get_id wl_proxy_get_id = nullptr;

  wayland_lib_t() : host("libwayland-client.so.0")
  {
    wl_display_connect = host.sym_as<PFN_wl_display_connect>("wl_display_connect");
    wl_display_connect_to_fd = host.sym_as<PFN_wl_display_connect_to_fd>("wl_display_connect_to_fd");
    wl_display_disconnect = host.sym_as<PFN_wl_display_disconnect>("wl_display_disconnect");
    wl_display_get_fd = host.sym_as<PFN_wl_display_get_fd>("wl_display_get_fd");
    wl_display_dispatch = host.sym_as<PFN_wl_display_dispatch>("wl_display_dispatch");
    wl_display_dispatch_pending = host.sym_as<PFN_wl_display_dispatch_pending>("wl_display_dispatch_pending");
    wl_display_roundtrip = host.sym_as<PFN_wl_display_roundtrip>("wl_display_roundtrip");
    wl_display_flush = host.sym_as<PFN_wl_display_flush>("wl_display_flush");
    wl_display_prepare_read = host.sym_as<PFN_wl_display_prepare_read>("wl_display_prepare_read");
    wl_display_read_events = host.sym_as<PFN_wl_display_read_events>("wl_display_read_events");
    wl_display_get_registry = host.sym_as<PFN_wl_display_get_registry>("wl_display_get_registry");

    wl_proxy_marshal_flags = host.sym_as<PFN_wl_proxy_marshal_flags>("wl_proxy_marshal_flags");
    wl_proxy_marshal_array_flags = host.sym_as<PFN_wl_proxy_marshal_array_flags>("wl_proxy_marshal_array_flags");
    wl_proxy_add_listener = host.sym_as<PFN_wl_proxy_add_listener>("wl_proxy_add_listener");
    wl_proxy_destroy = host.sym_as<PFN_wl_proxy_destroy>("wl_proxy_destroy");
    wl_proxy_get_user_data = host.sym_as<PFN_wl_proxy_get_user_data>("wl_proxy_get_user_data");
    wl_proxy_set_user_data = host.sym_as<PFN_wl_proxy_set_user_data>("wl_proxy_set_user_data");
    wl_proxy_get_version = host.sym_as<PFN_wl_proxy_get_version>("wl_proxy_get_version");
    wl_proxy_get_id = host.sym_as<PFN_wl_proxy_get_id>("wl_proxy_get_id");

    if ( !wl_display_connect || !wl_display_disconnect || !wl_display_get_fd || !wl_display_roundtrip || !wl_display_get_registry
         || !wl_proxy_add_listener || !wl_proxy_destroy ) {
      throw except::library_error("wayland: required entry points missing in libwayland-client.so.0");
    }
    // wl_proxy_marshal_flags was added in libwayland 1.20 (2021); on older
    // systems the legacy wl_proxy_marshal must be used instead. We require
    // 1.20+ for now to keep marshalling code uniform.
    if ( !wl_proxy_marshal_flags ) {
      throw except::library_error("wayland: libwayland-client < 1.20 (no wl_proxy_marshal_flags)");
    }
  }
};

class wayland_display_t
{
private:
  wl_display *__display = nullptr;
  wl_registry *__registry = nullptr;
  wl_compositor *__compositor = nullptr;
  xdg_wm_base *__shell = nullptr;
  u32 __compositor_name = 0;
  u32 __shell_name = 0;
  u32 __compositor_version = 0;
  u32 __shell_version = 0;
  i32 __fd = -1;
  wayland_lib_t *__lib = nullptr;

  // Registry-global handler. Recognises wl_compositor and xdg_wm_base by
  // name string and binds them via wl_registry.bind. Other globals (wl_seat,
  // wl_output, etc.) are recorded for io/uxin via the user's own listener
  // attached after open() returns — we do not bind them ourselves.
  static void
  __on_global(void *data, wl_registry *registry, u32 name, const char *interface, u32 version) noexcept
  {
    auto *self = static_cast<wayland_display_t *>(data);
    if ( micron::strcmp(interface, "wl_compositor") == 0 ) {
      const u32 use_ver = version < 4 ? version : 4u;
      void *p = self->__lib->wl_proxy_marshal_flags(reinterpret_cast<wl_proxy *>(registry), xdg_shell_ops::wl_registry_bind,
                                                    &__wl_compositor_interface, use_ver, 0, name, "wl_compositor", use_ver, nullptr);
      self->__compositor = reinterpret_cast<wl_compositor *>(p);
      self->__compositor_name = name;
      self->__compositor_version = use_ver;
    } else if ( micron::strcmp(interface, "xdg_wm_base") == 0 ) {
      const u32 use_ver = version < 1 ? version : 1u;
      void *p = self->__lib->wl_proxy_marshal_flags(reinterpret_cast<wl_proxy *>(registry), xdg_shell_ops::wl_registry_bind,
                                                    &__xdg_wm_base_interface, use_ver, 0, name, "xdg_wm_base", use_ver, nullptr);
      self->__shell = reinterpret_cast<xdg_wm_base *>(p);
      self->__shell_name = name;
      self->__shell_version = use_ver;
      // Attach the ping-pong listener so the compositor doesn't deem us
      // unresponsive while we sit waiting for swaps.
      static xdg_wm_base_listener_t listener{
        /*ping*/ [](void *d, xdg_wm_base *base, u32 serial) {
          auto *me = static_cast<wayland_display_t *>(d);
          me->__lib->wl_proxy_marshal_flags(reinterpret_cast<wl_proxy *>(base), xdg_shell_ops::xdg_wm_base_pong, nullptr,
                                            me->__shell_version, 0, serial);
        },
      };
      self->__lib->wl_proxy_add_listener(reinterpret_cast<wl_proxy *>(self->__shell), reinterpret_cast<void (**)(void)>(&listener), self);
    }
  }

  static void
  __on_global_remove(void *, wl_registry *, u32) noexcept
  {
  }

public:
  ~wayland_display_t() { close(); }

  wayland_display_t() = default;

  wayland_display_t(const wayland_display_t &) = delete;
  wayland_display_t(wayland_display_t &&) = delete;

  wayland_display_t &operator=(const wayland_display_t &) = delete;
  wayland_display_t &operator=(wayland_display_t &&) = delete;

  wl_display *
  display() const noexcept
  {
    return __display;
  }

  wl_compositor *
  compositor() const noexcept
  {
    return __compositor;
  }

  xdg_wm_base *
  shell() const noexcept
  {
    return __shell;
  }

  u32
  compositor_version() const noexcept
  {
    return __compositor_version;
  }

  u32
  shell_version() const noexcept
  {
    return __shell_version;
  }

  i32
  raw_fd() const noexcept
  {
    return __fd;
  }

  wayland_lib_t *
  lib() const noexcept
  {
    return __lib;
  }

  void
  open(wayland_lib_t &w)
  {
    __lib = &w;
    __display = w.wl_display_connect(nullptr);
    if ( !__display )
      throw except::network_error("wayland: wl_display_connect returned null — $WAYLAND_DISPLAY unset or socket unreachable");
    __fd = static_cast<i32>(w.wl_display_get_fd(__display));

    __registry = w.wl_display_get_registry(__display);
    static wl_registry_listener_t reg_listener{ &__on_global, &__on_global_remove };
    w.wl_proxy_add_listener(reinterpret_cast<wl_proxy *>(__registry), reinterpret_cast<void (**)(void)>(&reg_listener), this);

    // Two roundtrips: the first delivers the registry globals, the second
    // delivers any post-bind notifications (e.g. xdg_wm_base's ping if it
    // fires immediately).
    w.wl_display_roundtrip(__display);
    w.wl_display_roundtrip(__display);

    if ( !__compositor ) throw except::library_error("wayland: compositor missing — wl_compositor not advertised by server");
    if ( !__shell ) throw except::library_error("wayland: xdg_wm_base missing — server does not support xdg-shell");
  }

  void
  flush() noexcept
  {
    if ( __lib && __display ) __lib->wl_display_flush(__display);
  }

  void
  roundtrip() noexcept
  {
    if ( __lib && __display ) __lib->wl_display_roundtrip(__display);
  }

  void
  dispatch_pending() noexcept
  {
    if ( __lib && __display ) __lib->wl_display_dispatch_pending(__display);
  }

  void
  close() noexcept
  {
    if ( __lib && __shell ) __lib->wl_proxy_destroy(reinterpret_cast<wl_proxy *>(__shell));
    if ( __lib && __compositor ) __lib->wl_proxy_destroy(reinterpret_cast<wl_proxy *>(__compositor));
    if ( __lib && __registry ) __lib->wl_proxy_destroy(reinterpret_cast<wl_proxy *>(__registry));
    if ( __lib && __display ) __lib->wl_display_disconnect(__display);
    __display = nullptr;
    __registry = nullptr;
    __compositor = nullptr;
    __shell = nullptr;
    __fd = -1;
  }
};

class wayland_window_t
{
private:
  wl_surface *__surface = nullptr;
  xdg_surface *__xsurface = nullptr;
  xdg_toplevel *__toplevel = nullptr;
  i32 __width = 0;
  i32 __height = 0;
  bool __should_close = false;
  bool __configured = false;
  u32 __last_serial = 0;
  wayland_display_t *__disp = nullptr;

  // Window-event callbacks installed by gfx::window. Wayland surfaces only
  // expose resize / close / expose via xdg-shell; focus and visibility are
  // partially observable (xdg_toplevel.configure_state activated bit + map
  // events) but require wl_array parsing — deferred to a future pass.
  // GL-specific native handles (wl_egl_window) ride on the resize callback:
  // gfx::window's GL flavour installs a thunk that calls wl_egl_window_resize
  // before forwarding to the user's set_resize_func<Fn>().
  void *__owner = nullptr;
  void (*__cb_resize)(void *, i32, i32) noexcept = nullptr;
  void (*__cb_close)(void *) noexcept = nullptr;
  void (*__cb_focus)(void *, bool) noexcept = nullptr;
  void (*__cb_expose)(void *) noexcept = nullptr;
  void (*__cb_visibility)(void *, bool) noexcept = nullptr;
  void (*__cb_move)(void *, i32, i32) noexcept = nullptr;

  static void
  __on_xdg_surface_configure(void *data, xdg_surface *s, u32 serial) noexcept
  {
    auto *self = static_cast<wayland_window_t *>(data);
    self->__last_serial = serial;
    const bool first_configure = !self->__configured;
    self->__configured = true;
    self->__disp->lib()->wl_proxy_marshal_flags(reinterpret_cast<wl_proxy *>(s), xdg_shell_ops::xdg_surface_ack_configure, nullptr,
                                                self->__disp->shell_version(), 0, serial);
    // Treat each xdg_surface.configure as an expose hint — the compositor is
    // ready for us to redraw at the latest configured size.
    (void)first_configure;
    if ( self->__cb_expose ) self->__cb_expose(self->__owner);
  }

  static void
  __on_toplevel_configure(void *data, xdg_toplevel *, i32 w, i32 h, void *) noexcept
  {
    auto *self = static_cast<wayland_window_t *>(data);
    // Zero w/h means "the compositor leaves the size to the client" — keep
    // whatever we last had.
    if ( w > 0 && h > 0 && (w != self->__width || h != self->__height) ) {
      self->__width = w;
      self->__height = h;
      if ( self->__cb_resize ) self->__cb_resize(self->__owner, w, h);
    }
  }

  static void
  __on_toplevel_close(void *data, xdg_toplevel *) noexcept
  {
    auto *self = static_cast<wayland_window_t *>(data);
    self->__should_close = true;
    if ( self->__cb_close ) self->__cb_close(self->__owner);
  }

  static void
  __on_toplevel_configure_bounds(void *, xdg_toplevel *, i32, i32) noexcept
  {
  }

  static void
  __on_toplevel_wm_capabilities(void *, xdg_toplevel *, void *) noexcept
  {
  }

public:
  static constexpr backend_tag_t tag = backend_tag_t::wayland;

  ~wayland_window_t() { destroy(); }

  wayland_window_t() = default;

  wayland_window_t(const wayland_window_t &) = delete;
  wayland_window_t(wayland_window_t &&) = delete;

  wayland_window_t &operator=(const wayland_window_t &) = delete;
  wayland_window_t &operator=(wayland_window_t &&) = delete;

  wl_surface *
  surface() const noexcept
  {
    return __surface;
  }

  xdg_surface *
  xsurface() const noexcept
  {
    return __xsurface;
  }

  xdg_toplevel *
  toplevel() const noexcept
  {
    return __toplevel;
  }

  i32
  width() const noexcept
  {
    return __width;
  }

  i32
  height() const noexcept
  {
    return __height;
  }

  bool
  should_close() const noexcept
  {
    return __should_close;
  }

  void
  set_owner(void *o) noexcept
  {
    __owner = o;
  }

  void
  set_resize_cb(void (*f)(void *, i32, i32) noexcept) noexcept
  {
    __cb_resize = f;
  }

  void
  set_close_cb(void (*f)(void *) noexcept) noexcept
  {
    __cb_close = f;
  }

  void
  set_focus_cb(void (*f)(void *, bool) noexcept) noexcept
  {
    __cb_focus = f;
  }

  void
  set_expose_cb(void (*f)(void *) noexcept) noexcept
  {
    __cb_expose = f;
  }

  void
  set_visibility_cb(void (*f)(void *, bool) noexcept) noexcept
  {
    __cb_visibility = f;
  }

  void
  set_move_cb(void (*f)(void *, i32, i32) noexcept) noexcept
  {
    __cb_move = f;
  }

  void
  create(wayland_display_t &dpy, i32 w, i32 h, const char *title)
  {
    __disp = &dpy;
    __width = w;
    __height = h;
    auto &lib = *dpy.lib();

    // wl_compositor.create_surface — opcode 0, sig "n", returns wl_surface.
    void *surf = lib.wl_proxy_marshal_flags(reinterpret_cast<wl_proxy *>(dpy.compositor()), xdg_shell_ops::wl_compositor_create_surface,
                                            &__wl_surface_interface, dpy.compositor_version(), 0, nullptr);
    __surface = reinterpret_cast<wl_surface *>(surf);
    if ( !__surface ) throw except::library_error("wayland: wl_compositor.create_surface returned null");

    // xdg_wm_base.get_xdg_surface — opcode 2, sig "no".
    void *xsurf
        = lib.wl_proxy_marshal_flags(reinterpret_cast<wl_proxy *>(dpy.shell()), xdg_shell_ops::xdg_wm_base_get_xdg_surface,
                                     &__xdg_surface_interface, dpy.shell_version(), 0, nullptr, reinterpret_cast<wl_proxy *>(__surface));
    __xsurface = reinterpret_cast<xdg_surface *>(xsurf);
    if ( !__xsurface ) throw except::library_error("wayland: xdg_wm_base.get_xdg_surface returned null");

    static xdg_surface_listener_t xdg_surf_listener{ &__on_xdg_surface_configure };
    lib.wl_proxy_add_listener(reinterpret_cast<wl_proxy *>(__xsurface), reinterpret_cast<void (**)(void)>(&xdg_surf_listener), this);

    // xdg_surface.get_toplevel — opcode 1, sig "n".
    void *top = lib.wl_proxy_marshal_flags(reinterpret_cast<wl_proxy *>(__xsurface), xdg_shell_ops::xdg_surface_get_toplevel,
                                           &__xdg_toplevel_interface, dpy.shell_version(), 0, nullptr);
    __toplevel = reinterpret_cast<xdg_toplevel *>(top);
    if ( !__toplevel ) throw except::library_error("wayland: xdg_surface.get_toplevel returned null");

    static xdg_toplevel_listener_t top_listener{
      &__on_toplevel_configure,
      &__on_toplevel_close,
      &__on_toplevel_configure_bounds,
      &__on_toplevel_wm_capabilities,
    };
    lib.wl_proxy_add_listener(reinterpret_cast<wl_proxy *>(__toplevel), reinterpret_cast<void (**)(void)>(&top_listener), this);

    if ( title ) {
      lib.wl_proxy_marshal_flags(reinterpret_cast<wl_proxy *>(__toplevel), xdg_shell_ops::xdg_toplevel_set_title, nullptr,
                                 dpy.shell_version(), 0, title);
    }

    // Commit triggers the initial configure round-trip. After this returns
    // the surface has a role; an API-specific native handle (GL's
    // wl_egl_window, or Vulkan's VkSurfaceKHR via VK_KHR_wayland_surface)
    // can be attached on top.
    lib.wl_proxy_marshal_flags(reinterpret_cast<wl_proxy *>(__surface), xdg_shell_ops::wl_surface_commit, nullptr, dpy.compositor_version(),
                               0);
    lib.wl_display_roundtrip(dpy.display());
  }

  void
  poll_events() noexcept
  {
    if ( __disp ) __disp->dispatch_pending();
  }

  void
  set_title(const char *title) noexcept
  {
    if ( !__disp || !__toplevel || !title ) return;
    __disp->lib()->wl_proxy_marshal_flags(reinterpret_cast<wl_proxy *>(__toplevel), xdg_shell_ops::xdg_toplevel_set_title, nullptr,
                                          __disp->shell_version(), 0, title);
  }

  void
  resize(i32 w, i32 h) noexcept
  {
    __width = w;
    __height = h;
  }

  void
  destroy() noexcept
  {
    if ( !__disp ) return;
    auto &lib = *__disp->lib();
    if ( __toplevel ) {
      lib.wl_proxy_marshal_flags(reinterpret_cast<wl_proxy *>(__toplevel), xdg_shell_ops::xdg_toplevel_destroy, nullptr,
                                 __disp->shell_version(), 1 /*WL_MARSHAL_FLAG_DESTROY*/);
      __toplevel = nullptr;
    }
    if ( __xsurface ) {
      lib.wl_proxy_marshal_flags(reinterpret_cast<wl_proxy *>(__xsurface), xdg_shell_ops::xdg_surface_destroy, nullptr,
                                 __disp->shell_version(), 1);
      __xsurface = nullptr;
    }
    if ( __surface ) {
      lib.wl_proxy_marshal_flags(reinterpret_cast<wl_proxy *>(__surface), xdg_shell_ops::wl_surface_destroy, nullptr,
                                 __disp->compositor_version(), 1);
      __surface = nullptr;
    }
  }
};

};      // namespace platform
};      // namespace gfx
};      // namespace micron
