#!/usr/bin/env python3

from __future__ import annotations

import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

VK_XML = Path(__file__).resolve().parent.parent.parent / "tools" / "vk.xml"

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
VK_DIR = REPO_ROOT / "src" / "gfx" / "vk"
BITS_DIR = VK_DIR / "__bits"
VULKAN_HPP = VK_DIR / "vulkan.hpp"

TARGET_VERSIONS = ("VK_VERSION_1_0", "VK_VERSION_1_1", "VK_VERSION_1_2", "VK_VERSION_1_3")
ALLOWED_EXTENSIONS = {
    "VK_KHR_surface",
    "VK_KHR_swapchain",
    "VK_KHR_xlib_surface",
    "VK_KHR_wayland_surface",
    "VK_EXT_debug_utils",
    "VK_KHR_synchronization2",
}

C_TYPE_MAP = {
    "uint8_t":  "u8",
    "uint16_t": "u16",
    "uint32_t": "u32",
    "uint64_t": "u64",
    "int8_t":   "i8",
    "int16_t":  "i16",
    "int32_t":  "i32",
    "int64_t":  "i64",
    "size_t":   "usize",
}

EXTERNAL_TYPE_MAP = {
    "Display":   "::micron::gfx::platform::XDisplay",
    "Window":    "::micron::gfx::platform::XWindow",
    "VisualID":  "::micron::gfx::platform::XVisualID",
    "wl_display": "::micron::gfx::platform::wl_display",
    "wl_surface": "::micron::gfx::platform::wl_surface",
}

SKIP_TYPES = {
    "vk_platform",
    "VK_DEFINE_HANDLE",
    "VK_DEFINE_NON_DISPATCHABLE_HANDLE",
    "VK_USE_64_BIT_PTR_DEFINES",
    "VK_NULL_HANDLE",
    "VK_MAKE_VERSION",
    "VK_VERSION_MAJOR",
    "VK_VERSION_MINOR",
    "VK_VERSION_PATCH",
    "VK_API_VERSION",
    "VK_HEADER_VERSION",
    "VK_HEADER_VERSION_COMPLETE",
    "VK_MAKE_API_VERSION",
    "VK_API_VERSION_VARIANT",
    "VK_API_VERSION_MAJOR",
    "VK_API_VERSION_MINOR",
    "VK_API_VERSION_PATCH",
}

GLOBAL_COMMANDS = {
    "vkEnumerateInstanceVersion",
    "vkEnumerateInstanceExtensionProperties",
    "vkEnumerateInstanceLayerProperties",
    "vkCreateInstance",
}

INSTANCE_FIRST_PARAMS = {"VkInstance", "VkPhysicalDevice"}
DEVICE_FIRST_PARAMS = {"VkDevice", "VkQueue", "VkCommandBuffer"}

LICENSE_HEADER = """\
//  Copyright (c) 2024- David Lucius Severus
//
//  Distributed under the Boost Software License, Version 1.0.
//  See accompanying file LICENSE_1_0.txt or copy at
//  http://www.boost.org/LICENSE_1_0.txt
//
//  *** AUTOGENERATED FILE; do not hand-edit; regenerate via:
//        python3 tools/vk_xml_gen/gen_vk.py ***
"""


def text_walk(elem: ET.Element) -> str:
    out = []
    if elem.text:
        out.append(elem.text)
    for c in elem:
        if c.tag == "comment":
            continue
        out.append(text_walk(c))
        if c.tail:
            out.append(c.tail)
    return "".join(out)


def squash(s: str) -> str:
    return re.sub(r"\s+", " ", s).strip()


def rewrite_scalar_types(s: str) -> str:
    for k, v in C_TYPE_MAP.items():
        s = re.sub(rf"\b{k}\b", v, s)
    return s


def rewrite_attrs(s: str) -> str:
    return re.sub(r"\bVKAPI_(?:PTR|ATTR|CALL)\b", "", s)


def rewrite_external(s: str) -> str:
    for k, v in EXTERNAL_TYPE_MAP.items():
        s = re.sub(rf"\b{k}\b", v, s)
    return s


def rewrite_all(s: str) -> str:
    return squash(rewrite_external(rewrite_attrs(rewrite_scalar_types(s))))


def enum_prefix_for(group_name: str) -> str:
    s = group_name
    if s.startswith("Vk"):
        s = s[2:]
    is_v2 = s.endswith("FlagBits2")
    is_v64 = s.endswith("FlagBits64")
    s = re.sub(r"FlagBits(64|2)?$", "", s)
    # PascalCase to SCREAMING_SNAKE_CASE.
    s = re.sub(r"(?<!^)(?=[A-Z])", "_", s).upper()
    if s:
        base = f"VK_{s}_"
    else:
        base = "VK_"
    if is_v2:
        return base + "2_"
    if is_v64:
        return base + "64_"
    return base


def sanitize_member(full_name: str, prefix: str) -> str:
    if full_name.startswith(prefix):
        rest = full_name[len(prefix):]
    elif full_name.startswith("VK_"):
        rest = full_name[3:]
    else:
        rest = full_name
    if not rest:
        rest = "_NONE"
    if rest[0].isdigit():
        rest = "_" + rest
    return rest


def to_deleter_name(handle_t: str) -> str:
    """VkBuffer -> buffer_deleter, VkDeviceMemory -> device_memory_deleter."""
    s = handle_t
    if s.startswith("Vk"):
        s = s[2:]
    snake = re.sub(r"(?<!^)(?=[A-Z])", "_", s).lower()
    return f"{snake}_deleter"


_VENDOR_SUFFIXES = ("KHR", "EXT", "NV", "NVX", "AMD", "INTEL", "QCOM", "ARM", "GOOGLE", "VALVE",
                    "HUAWEI", "MVK", "FUCHSIA", "GGP", "NN", "ANDROID", "EXT2")


def _split_vendor_suffix(name: str) -> tuple[str, str]:
    """Returns (base, suffix) where suffix is the vendor tag at the end of
    `name`, or empty if none."""
    for sfx in _VENDOR_SUFFIXES:
        if name.endswith(sfx) and len(name) > len(sfx):
            return name[:-len(sfx)], sfx
    return name, ""


def bit_type_of_flags(flags_name: str) -> str | None:
    """VkBufferUsageFlags  -> VkBufferUsageFlagBits
       VkPipelineStageFlags2 -> VkPipelineStageFlagBits2
       VkAccessFlags64 -> VkAccessFlagBits64
       VkDebugUtilsMessageSeverityFlagsEXT -> VkDebugUtilsMessageSeverityFlagBitsEXT
       VkBufferUsageFlags2KHR -> VkBufferUsageFlagBits2KHR"""
    base, suffix = _split_vendor_suffix(flags_name)
    if base.endswith("Flags64"):
        return base[:-len("Flags64")] + "FlagBits64" + suffix
    if base.endswith("Flags2"):
        return base[:-len("Flags2")] + "FlagBits2" + suffix
    if base.endswith("Flags"):
        return base[:-len("Flags")] + "FlagBits" + suffix
    return None


def is_flagbits_type(group_name: str) -> bool:
    base, _ = _split_vendor_suffix(group_name)
    return base.endswith("FlagBits") or base.endswith("FlagBits64") or base.endswith("FlagBits2")


def flagbits_underlying(group_name: str) -> str:
    base, _ = _split_vendor_suffix(group_name)
    if base.endswith("FlagBits64") or base.endswith("FlagBits2"):
        return "u64"
    return "u32"


def flags_name_of_bits(group_name: str) -> str:
    base, suffix = _split_vendor_suffix(group_name)
    if base.endswith("FlagBits64"):
        return base[:-len("FlagBits64")] + "Flags64" + suffix
    if base.endswith("FlagBits2"):
        return base[:-len("FlagBits2")] + "Flags2" + suffix
    if base.endswith("FlagBits"):
        return base[:-len("FlagBits")] + "Flags" + suffix
    return group_name



class Registry:
    def __init__(self):
        self.types: dict[str, ET.Element] = {}
        self.types_order: list[str] = []
        self.enums: dict[str, ET.Element] = {}
        self.enum_values: dict[str, list[tuple[str, str, str]]] = {}
        self.api_constants: list[tuple[str, str, str]] = []
        self.commands: dict[str, ET.Element] = {}
        self.commands_order: list[str] = []
        self.required_types: set[str] = set()
        self.required_enums: set[str] = set()
        self.required_commands: list[str] = []
        self.ext_numbers: dict[str, int] = {}
        self.type_aliases: dict[str, str] = {}
        self.enum_aliases: dict[str, str] = {}
        self.command_aliases: dict[str, str] = {}


def parse(root: ET.Element) -> Registry:
    reg = Registry()

    types_el = root.find("types")
    assert types_el is not None
    for t in types_el.findall("type"):
        name = t.get("name") or (t.find("name").text if t.find("name") is not None else None)
        if not name:
            continue
        if t.get("alias"):
            reg.type_aliases[name] = t.get("alias")
            continue
        reg.types[name] = t
        reg.types_order.append(name)

    for e in root.findall("enums"):
        group = e.get("name") or ""
        reg.enums[group] = e
        rows: list[tuple[str, str, str]] = []
        for enum in e.findall("enum"):
            if enum.get("alias"):
                reg.enum_aliases[enum.get("name")] = enum.get("alias")
                continue
            n = enum.get("name")
            if not n:
                continue
            v = enum.get("value")
            if v is None:
                bp = enum.get("bitpos")
                if bp is not None:
                    v = f"(1ULL << {bp})"
            t = enum.get("type") or ""
            if v is None:
                continue
            rows.append((n, v, t))
        if group == "API Constants":
            reg.api_constants.extend(rows)
        else:
            reg.enum_values[group] = rows

    commands_el = root.find("commands")
    assert commands_el is not None
    for c in commands_el.findall("command"):
        if c.get("alias"):
            reg.command_aliases[c.get("name")] = c.get("alias")
            continue
        proto = c.find("proto")
        if proto is None:
            continue
        nm = proto.find("name")
        if nm is None or not nm.text:
            continue
        reg.commands[nm.text] = c

    for f in root.findall("feature"):
        name = f.get("name")
        if name not in TARGET_VERSIONS:
            continue
        collect_requires(f, reg, is_extension=False)

    for ext in root.find("extensions").findall("extension"):
        name = ext.get("name")
        if name not in ALLOWED_EXTENSIONS:
            continue
        number = int(ext.get("number"))
        reg.ext_numbers[name] = number
        collect_requires(ext, reg, is_extension=True, ext_number=number)

    close_transitive_types(reg)

    for name in list(reg.required_types):
        t = reg.types.get(name)
        if t is None:
            continue
        if (t.get("category") or "") != "enum":
            continue
        for value_name, _v, _t in reg.enum_values.get(name, []):
            reg.required_enums.add(value_name)

    return reg


def close_transitive_types(reg: Registry) -> None:
    def refs_in(t: ET.Element) -> set[str]:
        out: set[str] = set()
        req = t.get("requires")
        if req and req in reg.types:
            out.add(req)
        for tt in t.findall(".//type"):
            if tt.text and tt.text in reg.types:
                out.add(tt.text)
        return out

    while True:
        added = False
        for name in list(reg.required_types):
            t = reg.types.get(name)
            if t is None:
                continue
            for ref in refs_in(t):
                if ref not in reg.required_types:
                    reg.required_types.add(ref)
                    added = True
        for alias, target in reg.type_aliases.items():
            if alias in reg.required_types and target not in reg.required_types:
                reg.required_types.add(target)
                added = True
        if not added:
            break


def collect_requires(parent_el: ET.Element, reg: Registry, *, is_extension: bool, ext_number: int = 0):
    for req in parent_el.findall("require"):
        for t in req.findall("type"):
            n = t.get("name")
            if n:
                reg.required_types.add(n)
        for e in req.findall("enum"):
            n = e.get("name")
            if not n:
                continue
            reg.required_enums.add(n)
            extends = e.get("extends")
            if extends:
                v = e.get("value")
                if v is None:
                    bp = e.get("bitpos")
                    if bp is not None:
                        v = f"(1ULL << {bp})"
                    else:
                        offset = e.get("offset")
                        if offset is not None:
                            ext_num = int(e.get("extnumber") or ext_number)
                            d = -1 if e.get("dir") == "-" else 1
                            val = d * (1_000_000_000 + (ext_num - 1) * 1000 + int(offset))
                            v = str(val)
                if v is None:
                    continue
                reg.enum_values.setdefault(extends, []).append((n, v, e.get("type") or ""))
            else:
                v = e.get("value")
                if v is not None:
                    reg.api_constants.append((n, v, e.get("type") or ""))
        for c in req.findall("command"):
            n = c.get("name")
            if n and n not in reg.required_commands:
                reg.required_commands.append(n)



def emit_type(name: str, t: ET.Element, reg: Registry) -> str | None:
    category = t.get("category") or ""

    if name in SKIP_TYPES:
        return None
    if name in EXTERNAL_TYPE_MAP:
        return f"using {name} = {EXTERNAL_TYPE_MAP[name]};"

    if category == "basetype":
        body = squash(text_walk(t))
        body = rewrite_scalar_types(body)
        m = re.match(r"typedef\s+(.+?)\s+([A-Za-z_]\w*)\s*;\s*$", body)
        if m:
            return f"using {m.group(2)} = {m.group(1)};"
        return body

    if category == "handle":
        body = squash(text_walk(t))
        if "VK_DEFINE_NON_DISPATCHABLE_HANDLE" in body:
            return f"struct {name}_T; using {name} = {name}_T *;"
        if "VK_DEFINE_HANDLE" in body:
            return f"struct {name}_T; using {name} = {name}_T *;"
        return None

    if category == "bitmask":
        body = squash(text_walk(t))
        m = re.match(r"typedef\s+(.+?)\s+([A-Za-z_]\w*)\s*;\s*$", body)
        if not m:
            return None
        flags_name = m.group(2)
        underlying_kw = m.group(1)
        bit_type = bit_type_of_flags(flags_name)
        if bit_type and bit_type in reg.required_types:
            return f"using {flags_name} = micron::gfx::vk::flags<{bit_type}>;"
        return f"using {flags_name} = {underlying_kw};"

    if category == "enum":
        return emit_enum_class(name, reg)

    if category == "funcpointer":
        body = squash(text_walk(t))
        body = rewrite_attrs(body)
        body = rewrite_scalar_types(body)
        m = re.match(r"typedef\s+(.+?)\s*\(\s*\*\s*([A-Za-z_]\w*)\s*\)\s*\((.*)\)\s*;\s*$", body, re.DOTALL)
        if m:
            ret = m.group(1).strip()
            nm = m.group(2)
            args = m.group(3).strip()
            return f"using {nm} = {ret} (*)({args});"
        return None

    if category == "struct" or category == "union":
        return emit_record(name, t, is_union=(category == "union"))

    if category == "define":
        return None

    return None


def emit_enum_class(name: str, reg: Registry) -> str:
    if is_flagbits_type(name):
        underlying = flagbits_underlying(name)
    else:
        underlying = "i32"

    rows = reg.enum_values.get(name, [])
    rows = [r for r in rows if r[0] in reg.required_enums]

    if not rows:
        return f"enum class {name} : {underlying} {{}};"

    pfx = enum_prefix_for(name)
    seen: set[str] = set()
    lines = [f"enum class {name} : {underlying} {{"]
    for n, v, _ in rows:
        if n in seen:
            continue
        seen.add(n)
        clean = re.sub(r"([0-9])([UuLlFf]+)$", r"\1", v)
        member = sanitize_member(n, pfx)
        lines.append(f"  {member} = {clean},")
    lines.append("};")
    return "\n".join(lines)


def emit_record(name: str, t: ET.Element, *, is_union: bool) -> str:
    kw = "union" if is_union else "struct"
    lines = [f"{kw} {name} {{"]
    for m in t.findall("member"):
        if m.get("api") == "vulkansc":
            continue
        decl = squash(text_walk(m))
        decl = re.sub(r"//.*$", "", decl).strip()
        decl = rewrite_all(decl)
        decl = decl.rstrip(";").strip()
        if not decl:
            continue
        decl += ";"
        lines.append(f"  {decl}")
    lines.append("};")
    return "\n".join(lines)


def cpp_value_type(v: str) -> str:
    v = v.strip()
    if v.endswith(("ULL", "ull")):
        return "u64"
    if v.endswith(("LL", "ll")):
        return "i64"
    if v.endswith(("U", "u")):
        return "u32"
    if v.endswith(("F", "f")):
        return "f32"
    if v.startswith('"'):
        return "const char *"
    if re.match(r"^-?\d+$", v):
        return "i32"
    if re.match(r"^0x[0-9a-fA-F]+$", v):
        return "u32"
    return "u32"


def emit_api_constants(consts: list[tuple[str, str, str]]) -> list[str]:
    out: list[str] = []
    seen: set[str] = set()
    for n, v, t in consts:
        if n in seen:
            continue
        seen.add(n)
        ct = cpp_value_type(v) if not t else map_enum_type(t)
        clean = re.sub(r"([0-9])([UuLlFf]+)$", r"\1", v) if not v.startswith('"') else v
        out.append(f"inline constexpr {ct} {n} = {clean};")
    return out


def map_enum_type(t: str) -> str:
    if t == "uint32_t":
        return "u32"
    if t == "uint64_t":
        return "u64"
    return t or "u32"


def command_signature(cmd: ET.Element) -> tuple[str, str, str, list[str]]:
    proto = cmd.find("proto")
    ret_t = squash(text_walk(proto).replace(proto.find("name").text, "")).strip()
    name = proto.find("name").text
    params = []
    first_types = []
    for p in cmd.findall("param"):
        if p.get("api") == "vulkansc":
            continue
        decl = squash(text_walk(p))
        decl = rewrite_all(decl)
        params.append(decl)
        tt = p.find("type")
        if tt is not None and tt.text:
            first_types.append(tt.text)
    return name, rewrite_all(ret_t), ", ".join(params), first_types


def pfn_name(api_name: str) -> str:
    return f"PFN_{api_name}"


def dispatch_kind(api_name: str, first_types: list[str]) -> int:
    if api_name in GLOBAL_COMMANDS:
        return 0
    if not first_types:
        return 0
    f = first_types[0]
    if f in DEVICE_FIRST_PARAMS:
        return 2
    if f in INSTANCE_FIRST_PARAMS:
        return 1
    return 1


def topo_sort_records(reg: Registry, candidates: list[str]) -> list[str]:
    candidates_set = set(candidates)
    record_set = {n for n in candidates
                  if reg.types.get(n) is not None
                  and reg.types[n].get("category") in ("struct", "union")}

    deps: dict[str, set[str]] = {}
    for name in record_set:
        t = reg.types[name]
        s: set[str] = set()
        for m in t.findall("member"):
            if m.get("api") == "vulkansc":
                continue
            tt = m.find("type")
            if tt is None or not tt.text:
                continue
            tname = tt.text
            if tname not in record_set:
                continue
            raw = squash(text_walk(m))
            if "*" in raw:
                continue
            s.add(tname)
        deps[name] = s

    visited: set[str] = set()
    order: list[str] = []

    def visit(n: str, stack: tuple[str, ...]) -> None:
        if n in visited:
            return
        if n in stack:
            return
        for d in sorted(deps.get(n, ())):
            visit(d, stack + (n,))
        visited.add(n)
        order.append(n)

    for name in candidates:
        visit(name, ())
    return order


def write_types(reg: Registry) -> str:
    out = [LICENSE_HEADER, "#pragma once", ""]
    out.append('#include "../../../bits/__arch.hpp"')
    out.append('#include "../../../types.hpp"')
    out.append('')
    out.append('#include "../flags.hpp"')
    out.append('')
    out.append('#include "../../platform/__bits/__wayland_types.hpp"')
    out.append('#include "../../platform/__bits/__x11_types.hpp"')
    out.append("")
    out.append("#if !defined(__micron_os_linux)")
    out.append('#error "micron::gfx::vk is linux-only"')
    out.append("#endif")
    out.append("")
    out.append("namespace micron")
    out.append("{")
    out.append("namespace gfx")
    out.append("{")
    out.append("namespace vk")
    out.append("{")
    out.append("")
    out.append("// autogenerated from vk.xml;")
    out.append("")

    emitted: set[str] = set()

    # Classify required types by category.
    basetypes: list[str] = []
    handles: list[str] = []
    enum_types: list[str] = []
    bitmask_types: list[str] = []
    funcpointers: list[str] = []
    records: list[str] = []
    external_types: list[str] = []
    other_types: list[str] = []

    for name in reg.types_order:
        if name not in reg.required_types or name in emitted:
            continue
        t = reg.types.get(name)
        if t is None:
            continue
        if name in EXTERNAL_TYPE_MAP:
            external_types.append(name)
            continue
        cat = t.get("category") or ""
        if cat == "basetype":
            basetypes.append(name)
        elif cat == "handle":
            handles.append(name)
        elif cat == "enum":
            enum_types.append(name)
        elif cat == "bitmask":
            bitmask_types.append(name)
        elif cat == "funcpointer":
            funcpointers.append(name)
        elif cat in ("struct", "union"):
            records.append(name)
        else:
            other_types.append(name)

    out.append("// Struct / union forward declarations")
    for name in records:
        cat = reg.types[name].get("category")
        out.append(f"{cat} {name};")
    out.append("")

    # External-type aliases.
    if external_types:
        out.append("// External types (platform forwards)")
        for name in external_types:
            decl = emit_type(name, reg.types[name], reg)
            if decl:
                out.append(decl)
                emitted.add(name)
        out.append("")

    out.append("// Basetypes")
    for name in basetypes:
        decl = emit_type(name, reg.types[name], reg)
        if decl:
            out.append(decl)
            emitted.add(name)
    out.append("")

    out.append("// Handles (dispatchable + non-dispatchable)")
    for name in handles:
        decl = emit_type(name, reg.types[name], reg)
        if decl:
            out.append(decl)
            emitted.add(name)
    out.append("")

    out.append("// Scoped enum class definitions")
    for name in enum_types:
        decl = emit_type(name, reg.types[name], reg)
        if decl:
            out.append(decl)
            emitted.add(name)
    out.append("")

    for name in bitmask_types:
        decl = emit_type(name, reg.types[name], reg)
        if decl:
            out.append(decl)
            emitted.add(name)
    out.append("")

    # Funcpointers.
    out.append("// Function-pointer typedefs")
    for name in funcpointers:
        decl = emit_type(name, reg.types[name], reg)
        if decl:
            out.append(decl)
            emitted.add(name)
    out.append("")

    out.extend(emit_api_constants(reg.api_constants))
    out.append("")

    out.append("// Struct / union definitions")
    for name in topo_sort_records(reg, records):
        decl = emit_type(name, reg.types[name], reg)
        if decl:
            out.append(decl)
            emitted.add(name)

    for name in other_types:
        decl = emit_type(name, reg.types[name], reg)
        if decl:
            out.append(decl)
            emitted.add(name)

    for alias, target in reg.type_aliases.items():
        if alias in reg.required_types and target in emitted:
            out.append(f"using {alias} = {target};")
            emitted.add(alias)
    out.append("")
    out.append("};      // namespace vk")
    out.append("};      // namespace gfx")
    out.append("};      // namespace micron")
    return "\n".join(out) + "\n"


def write_enums(reg: Registry) -> str:
    out = [LICENSE_HEADER, "#pragma once", "", '#include "__vk_types.hpp"', ""]
    out.append("namespace micron { namespace gfx { namespace vk {")
    out.append("")
    out.append("// legacy VK_* aliases pointing into the matching enum class")
    out.append("")

    emitted_alias: set[str] = set()
    for group in sorted(reg.enum_values):
        if group not in reg.required_types:
            continue
        rows = reg.enum_values[group]
        rows = [r for r in rows if r[0] in reg.required_enums]
        if not rows:
            continue
        pfx = enum_prefix_for(group)
        out.append(f"// --- {group} ---")
        seen: set[str] = set()
        for n, _, _ in rows:
            if n in seen:
                continue
            seen.add(n)
            member = sanitize_member(n, pfx)
            out.append(f"inline constexpr {group} {n} = {group}::{member};")
            emitted_alias.add(n)
        out.append("")

    aliased: list[str] = []
    for alias, target in reg.enum_aliases.items():
        if alias not in reg.required_enums:
            continue
        if alias in emitted_alias:
            continue
        if target not in emitted_alias:
            continue
        aliased.append(f"inline constexpr auto {alias} = {target};")
    if aliased:
        out.append("// Enum aliases")
        out.extend(aliased)
        out.append("")

    out.append("}; }; };      // namespace micron::gfx::vk")
    return "\n".join(out) + "\n"


def write_protos(reg: Registry) -> str:
    out = [LICENSE_HEADER, "#pragma once", "", '#include "__vk_types.hpp"', ""]
    out.append("namespace micron { namespace gfx { namespace vk {")
    out.append("")
    out.append("// PFN_vkXxx typedefs for every selected entry point")
    out.append("")
    for cmd_name in reg.required_commands:
        real_name = cmd_name
        while real_name in reg.command_aliases:
            real_name = reg.command_aliases[real_name]
        cmd = reg.commands.get(real_name)
        if cmd is None:
            continue
        api_name, ret_t, params, _ = command_signature(cmd)
        out.append(f"using {pfn_name(cmd_name)} = {ret_t} (*)({params});")
    out.append("")
    out.append("}; }; };      // namespace micron::gfx::vk")
    return "\n".join(out) + "\n"


def write_table(reg: Registry) -> str:
    out = [LICENSE_HEADER, "#pragma once", "", '#include "__vk_protos.hpp"', ""]
    out.append("namespace micron { namespace gfx { namespace vk {")
    out.append("")
    out.append("// master entry metadata tbl")
    out.append("")
    out.append("struct vk_entry_t {")
    out.append("  const char *name;")
    out.append("  u16 index;")
    out.append("  u8 dispatch_kind;     // 0=global, 1=instance, 2=device")
    out.append("};")
    out.append("")
    out.append("inline constexpr vk_entry_t vk_table[] = {")
    for i, cmd_name in enumerate(reg.required_commands):
        real_name = cmd_name
        while real_name in reg.command_aliases:
            real_name = reg.command_aliases[real_name]
        cmd = reg.commands.get(real_name)
        if cmd is None:
            continue
        _, _, _, first_types = command_signature(cmd)
        k = dispatch_kind(cmd_name, first_types)
        out.append(f'  {{ "{cmd_name}", {i}, {k} }},')
    out.append("};")
    out.append("")
    out.append("inline constexpr usize vk_table_size = sizeof(vk_table) / sizeof(vk_table[0]);")
    out.append("")
    out.append("consteval u16")
    out.append("sym_index_of(const char *name) noexcept")
    out.append("{")
    out.append("  for ( u16 i = 0; i < vk_table_size; ++i ) {")
    out.append("    const char *a = vk_table[i].name;")
    out.append("    const char *b = name;")
    out.append("    while ( *a && *a == *b ) { ++a; ++b; }")
    out.append("    if ( *a == 0 && *b == 0 ) return i;")
    out.append("  }")
    out.append("  return u16(-1);")
    out.append("}")
    out.append("")
    out.append("}; }; };      // namespace micron::gfx::vk")
    return "\n".join(out) + "\n"


def write_flag_traits(reg: Registry) -> str:
    out = [LICENSE_HEADER, "#pragma once", "", '#include "../flags.hpp"', '#include "__vk_types.hpp"', ""]
    out.append("namespace micron { namespace gfx { namespace vk {")
    out.append("")

    for group in sorted(reg.enum_values):
        if not is_flagbits_type(group):
            continue
        if group not in reg.required_types:
            continue
        rows = reg.enum_values[group]
        rows = [r for r in rows if r[0] in reg.required_enums]
        if not rows:
            continue
        underlying = flagbits_underlying(group)
        flags_name = flags_name_of_bits(group)
        if flags_name not in reg.required_types:
            continue

        pfx = enum_prefix_for(group)
        seen: set[str] = set()
        unique_members: list[str] = []
        for n, _, _ in rows:
            if n in seen:
                continue
            seen.add(n)
            unique_members.append(sanitize_member(n, pfx))

        out.append(f"template <> struct flag_traits<{group}> {{")
        out.append(f"  static constexpr bool is_bitmask = true;")
        if unique_members:
            ors = " | ".join(f"static_cast<{underlying}>({group}::{m})" for m in unique_members)
            out.append(f"  static constexpr {flags_name} all_flags{{ static_cast<{underlying}>({ors}) }};")
        else:
            out.append(f"  static constexpr {flags_name} all_flags{{ static_cast<{underlying}>(0) }};")
        out.append("};")
        out.append("")

    out.append("} } }      // namespace micron::gfx::vk")
    return "\n".join(out) + "\n"


def write_structure_types(reg: Registry) -> str:
    out = [LICENSE_HEADER, "#pragma once", "", '#include "../structure_type.hpp"', '#include "__vk_types.hpp"', ""]
    out.append("namespace micron { namespace gfx { namespace vk {")
    out.append("")
    out.append("")

    structure_type_prefix = enum_prefix_for("VkStructureType")

    for name in reg.types_order:
        if name not in reg.required_types:
            continue
        t = reg.types.get(name)
        if t is None:
            continue
        cat = t.get("category") or ""
        if cat not in ("struct", "union"):
            continue
        for m in t.findall("member"):
            if m.get("api") == "vulkansc":
                continue
            mn = m.find("name")
            if mn is None or mn.text != "sType":
                continue
            values = m.get("values")
            if not values:
                continue
            v = values.split(",")[0].strip()
            if v not in reg.required_enums:
                continue
            member = sanitize_member(v, structure_type_prefix)
            out.append(f"template <> struct structure_type_of<{name}> {{")
            out.append(f"  static constexpr VkStructureType value = VkStructureType::{member};")
            out.append("};")

    out.append("")
    out.append("} } }      // namespace micron::gfx::vk")
    return "\n".join(out) + "\n"


def write_deleters(reg: Registry) -> str:
    out = [LICENSE_HEADER, "#pragma once", "", '#include "../vulkan.hpp"', ""]
    out.append("namespace micron { namespace gfx { namespace vk {")
    out.append("")

    seen_handles: set[str] = set()

    for cmd_name in reg.required_commands:
        real = cmd_name
        while real in reg.command_aliases:
            real = reg.command_aliases[real]
        cmd = reg.commands.get(real)
        if cmd is None:
            continue

        params = []
        for p in cmd.findall("param"):
            if p.get("api") == "vulkansc":
                continue
            decl_text = squash(text_walk(p))
            tt = p.find("type")
            pn = p.find("name")
            params.append((tt.text if tt is not None else "", pn.text if pn is not None else "", decl_text))

        if cmd_name in ("vkDestroyInstance", "vkDestroyDevice") and len(params) == 2:
            handle_t, _, _ = params[0]
            if handle_t and handle_t not in seen_handles:
                _emit_orphan_deleter(out, handle_t, cmd_name)
                seen_handles.add(handle_t)
            continue

        if cmd_name.startswith("vkDestroy") and len(params) == 3:
            parent_t, _, _ = params[0]
            handle_t, _, _ = params[1]
            alloc_t, _, _ = params[2]
            if alloc_t == "VkAllocationCallbacks" and handle_t and handle_t not in seen_handles:
                _emit_simple_deleter(out, handle_t, parent_t, cmd_name)
                seen_handles.add(handle_t)
            continue

        if cmd_name == "vkFreeMemory" and len(params) == 3:
            parent_t, _, _ = params[0]
            handle_t, _, _ = params[1]
            if handle_t and handle_t not in seen_handles:
                _emit_simple_deleter(out, handle_t, parent_t, cmd_name)
                seen_handles.add(handle_t)
            continue

        if cmd_name.startswith("vkFree") and len(params) == 4:
            parent_t, _, _ = params[0]
            pool_t, _, _ = params[1]
            handle_t, _, _ = params[3]
            if handle_t and handle_t not in seen_handles:
                _emit_pool_deleter(out, handle_t, parent_t, pool_t, cmd_name)
                seen_handles.add(handle_t)
            continue

    out.append("}; }; };      // namespace micron::gfx::vk")
    return "\n".join(out) + "\n"


def _emit_simple_deleter(out: list[str], handle_t: str, parent_t: str, destroy_cmd: str) -> None:
    name = to_deleter_name(handle_t)
    out.append(f"struct {name} {{")
    out.append(f"  {parent_t} parent = nullptr;")
    out.append(f"  const VkAllocationCallbacks *alloc = nullptr;")
    out.append(f"  void operator()({handle_t} h) const noexcept")
    out.append(f"  {{")
    out.append(f"    if ( h && parent && {destroy_cmd} ) {destroy_cmd}(parent, h, alloc);")
    out.append(f"  }}")
    out.append("};")
    out.append("")


def _emit_pool_deleter(out: list[str], handle_t: str, parent_t: str, pool_t: str, free_cmd: str) -> None:
    name = to_deleter_name(handle_t)
    out.append(f"struct {name} {{")
    out.append(f"  {parent_t} parent = nullptr;")
    out.append(f"  {pool_t} pool = nullptr;")
    out.append(f"  void operator()({handle_t} h) const noexcept")
    out.append(f"  {{")
    out.append(f"    if ( h && parent && pool && {free_cmd} ) {free_cmd}(parent, pool, 1, &h);")
    out.append(f"  }}")
    out.append("};")
    out.append("")


def _emit_orphan_deleter(out: list[str], handle_t: str, destroy_cmd: str) -> None:
    name = to_deleter_name(handle_t)
    out.append(f"struct {name} {{")
    out.append(f"  const VkAllocationCallbacks *alloc = nullptr;")
    out.append(f"  void operator()({handle_t} h) const noexcept")
    out.append(f"  {{")
    out.append(f"    if ( h && {destroy_cmd} ) {destroy_cmd}(h, alloc);")
    out.append(f"  }}")
    out.append("};")
    out.append("")


def write_vulkan_hpp(reg: Registry) -> str:
    out = [LICENSE_HEADER, "#pragma once", ""]
    out.append('#include "__bits/__vk_enums.hpp"')
    out.append('#include "__bits/__vk_protos.hpp"')
    out.append('#include "__bits/__vk_table.hpp"')
    out.append('#include "__bits/__vk_types.hpp"')
    out.append("")
    out.append('#include "__bits/__vk_core_supplement.hpp"')
    out.append("")
    out.append("// main Vulkan fns")
    out.append("")
    out.append("namespace micron { namespace gfx { namespace vk {")
    out.append("")
    for cmd_name in reg.required_commands:
        out.append(f"inline {pfn_name(cmd_name)} {cmd_name} = nullptr;")
    out.append("")
    out.append("inline void **const __vk_fnptr_slots[] = {")
    for cmd_name in reg.required_commands:
        out.append(f"  reinterpret_cast<void **>(&{cmd_name}),")
    out.append("};")
    out.append("")
    out.append("static_assert(sizeof(__vk_fnptr_slots) / sizeof(__vk_fnptr_slots[0]) == vk_table_size,")
    out.append('              "vulkan.hpp __vk_fnptr_slots must parallel __vk_table.hpp vk_table by index");')
    out.append("")
    out.append("}; }; };      // namespace micron::gfx::vk")
    out.append("")
    out.append('#include "__bits/__vk_flag_traits.hpp"')
    out.append('#include "__bits/__vk_structure_types.hpp"')
    out.append('#include "__bits/__vk_deleters.hpp"')
    out.append("")
    out.append("namespace micron { namespace vk = ::micron::gfx::vk; }")
    out.append("")
    out.append("#define MICRON_VK_SYM(name) (::micron::gfx::vk::sym_index_of(#name))")
    return "\n".join(out) + "\n"


def main() -> int:
    if not VK_XML.exists():
        print(f"error: {VK_XML} not found", file=sys.stderr)
        return 1
    tree = ET.parse(VK_XML)
    reg = parse(tree.getroot())
    print(f"required: {len(reg.required_types)} types, {len(reg.required_enums)} enums, {len(reg.required_commands)} commands")
    BITS_DIR.mkdir(parents=True, exist_ok=True)
    (BITS_DIR / "__vk_types.hpp").write_text(write_types(reg))
    (BITS_DIR / "__vk_enums.hpp").write_text(write_enums(reg))
    (BITS_DIR / "__vk_protos.hpp").write_text(write_protos(reg))
    (BITS_DIR / "__vk_table.hpp").write_text(write_table(reg))
    (BITS_DIR / "__vk_flag_traits.hpp").write_text(write_flag_traits(reg))
    (BITS_DIR / "__vk_structure_types.hpp").write_text(write_structure_types(reg))
    (BITS_DIR / "__vk_deleters.hpp").write_text(write_deleters(reg))
    VULKAN_HPP.write_text(write_vulkan_hpp(reg))
    for f in ("__vk_types.hpp", "__vk_enums.hpp", "__vk_protos.hpp", "__vk_table.hpp",
              "__vk_flag_traits.hpp", "__vk_structure_types.hpp", "__vk_deleters.hpp"):
        print(f"wrote {BITS_DIR}/{f}")
    print(f"wrote {VULKAN_HPP}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
