#!/usr/bin/env python3

from __future__ import annotations

import os
import re
import sys
from pathlib import Path

GLCOREARB = Path("/usr/include/GL/glcorearb.h")

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
BITS_DIR = REPO_ROOT / "src" / "gfx" / "gl" / "__bits"
OPENGL_HPP = REPO_ROOT / "src" / "gfx" / "gl" / "opengl.hpp"

TYPE_MAP = {
    "khronos_int8_t":   "i8",
    "khronos_uint8_t":  "u8",
    "khronos_int16_t":  "i16",
    "khronos_uint16_t": "u16",
    "khronos_int32_t":  "i32",
    "khronos_uint32_t": "u32",
    "khronos_int64_t":  "i64",
    "khronos_uint64_t": "u64",
    "khronos_intptr_t": "intptr_t",
    "khronos_ssize_t":  "ssize_t",
    "khronos_float_t":  "f32",
}

SPECIAL_TYPES = {
    "GLsync":     "struct __GLsync; using GLsync = __GLsync *;",
    "GLDEBUGPROC": (
        "using GLDEBUGPROC = void (*)(GLenum source, GLenum type, GLuint id, "
        "GLenum severity, GLsizei length, const GLchar *message, "
        "const void *userParam);\n"
        "using GLDEBUGPROCARB = GLDEBUGPROC;\n"
        "using GLDEBUGPROCKHR = GLDEBUGPROC;"
    ),
}

LICENSE_HEADER = """\
//  Copyright (c) 2024- David Lucius Severus
//
//  Distributed under the Boost Software License, Version 1.0.
//  See accompanying file LICENSE_1_0.txt or copy at
//  http://www.boost.org/LICENSE_1_0.txt
//
//  *** AUTOGENERATED FILE; do not hand-edit; regenerate via:
//        python3 tools/gl_xml_gen/gen_gl.py ***
"""


def rewrite_khronos(s: str) -> str:
    for k, v in TYPE_MAP.items():
        s = re.sub(rf"\b{k}\b", v, s)
    return s


def parse_glcorearb(text: str):
    types_order: list[str] = []
    types: dict[str, str] = {}
    enums_order: list[str] = []
    enums: dict[str, str] = {}
    pfns_order: list[str] = []
    pfns: dict[str, tuple[str, str]] = {}
    apis_order: list[str] = []
    apis: dict[str, tuple[int, int]] = {}

    cur_ver: tuple[int, int] | None = None

    ver_re = re.compile(r"^#ifndef GL_VERSION_(\d+)_(\d+)\s*$")
    end_re = re.compile(r"^#endif /\* GL_VERSION_\d+_\d+ \*/\s*$")

    typedef_re = re.compile(r"^typedef\s+(.+?)\s+(GL[a-zA-Z0-9_]+);\s*$")
    typedef_struct_re = re.compile(r"^typedef\s+struct\s+(\w+)\s*\*\s*(GL[a-zA-Z0-9_]+);\s*$")
    callback_typedef_re = re.compile(
        r"^typedef\s+(.+?)\s*\(\s*APIENTRY\s*\*\s*(GL[a-zA-Z0-9_]+)\s*\)\s*\((.*?)\)\s*;\s*$",
        re.DOTALL,
    )
    define_re = re.compile(r"^#define\s+(GL_[A-Z0-9_]+)\s+(.+?)\s*$")
    pfn_re = re.compile(
        r"^typedef\s+(.+?)\s*\(APIENTRYP\s+(PFNGL[A-Z0-9_]+PROC)\)\s*\((.*?)\)\s*;\s*$",
        re.DOTALL,
    )
    api_re = re.compile(r"^GLAPI\s+.+?APIENTRY\s+(gl[A-Z][a-zA-Z0-9_]+)\s*\(")

    glued: list[str] = []
    buf = ""
    for line in text.splitlines():
        if buf:
            buf += " " + line.strip()
            if line.rstrip().endswith(";"):
                glued.append(buf)
                buf = ""
            continue
        if line.startswith("typedef ") and not line.rstrip().endswith(";"):
            buf = line
            continue
        glued.append(line)

    for line in glued:
        m = ver_re.match(line)
        if m:
            cur_ver = (int(m.group(1)), int(m.group(2)))
            continue
        if end_re.match(line):
            cur_ver = None
            continue

        if cur_ver is None:
            continue

        m = callback_typedef_re.match(line)
        if m:
            ret = rewrite_khronos(m.group(1).strip())
            name = m.group(2)
            args = rewrite_khronos(m.group(3).strip())
            if name not in types:
                types_order.append(name)
                types[name] = f"using {name} = {ret} (*)({args});"
            continue

        m = pfn_re.match(line)
        if m:
            ret = rewrite_khronos(m.group(1).strip())
            name = m.group(2)
            args = rewrite_khronos(m.group(3).strip())
            if name not in pfns:
                pfns_order.append(name)
                pfns[name] = (ret, args)
            continue

        m = typedef_struct_re.match(line)
        if m:
            name = m.group(2)
            if name not in types:
                types_order.append(name)
                types[name] = f"struct {m.group(1)}; using {name} = {m.group(1)} *;"
            continue

        m = typedef_re.match(line)
        if m:
            name = m.group(2)
            underlying = rewrite_khronos(m.group(1).strip())
            if name not in types:
                types_order.append(name)
                types[name] = f"using {name} = {underlying};"
            continue

        m = define_re.match(line)
        if m:
            name = m.group(1)
            value = m.group(2).strip()
            if re.match(r"^GL_VERSION_\d+_\d+$", name):
                continue
            value = re.sub(r"\s+/\*.*\*/$", "", value).strip()
            if name not in enums:
                enums_order.append(name)
                enums[name] = value
            continue

        m = api_re.search(line)
        if m:
            name = m.group(1)
            if name not in apis:
                apis_order.append(name)
                apis[name] = cur_ver
            continue

    return (
        [(n, types[n]) for n in types_order],
        [(n, enums[n]) for n in enums_order],
        [(n, *pfns[n]) for n in pfns_order],
        [(n, *apis[n]) for n in apis_order],
    )


def pfn_for(api: str) -> str:
    """glClearColor -> PFNGLCLEARCOLORPROC"""
    return f"PFN{api.upper()}PROC"


def write_types(types):
    out = [LICENSE_HEADER, "#pragma once", ""]
    out.append('#include "../../../bits/__arch.hpp"')
    out.append('#include "../../../types.hpp"')
    out.append("")
    out.append("#if !defined(__micron_os_linux)")
    out.append('#error "micron::gl is linux-only"')
    out.append("#endif")
    out.append("")
    out.append("namespace micron")
    out.append("{")
    out.append("namespace gfx")
    out.append("{")
    out.append("namespace gl")
    out.append("{")
    out.append("")
    out.append("// autogenerated by tools/gl_xml_gen/gen_gl.py from /usr/include/GL/glcorearb.h")
    out.append("")
    seen: set[str] = set()
    for name, defn in types:
        if name in seen:
            continue
        out.append(defn)
        seen.add(name)
    if "GLDEBUGPROC" in seen:
        out.append("using GLDEBUGPROCARB = GLDEBUGPROC;")
        out.append("using GLDEBUGPROCKHR = GLDEBUGPROC;")
    out.append("")
    out.append("};      // namespace gl")
    out.append("};      // namespace gfx")
    out.append("};      // namespace micron")
    return "\n".join(out) + "\n"


def write_enums(enums):
    out = [LICENSE_HEADER, "#pragma once", "", '#include "__gl_types.hpp"', ""]
    out.append("namespace micron { namespace gfx { namespace gl {")
    out.append("")
    out.append("// all #define GL_* from GL_VERSION_1_0 through GL_VERSION_4_6")
    out.append("")
    for name, value in enums:
        v = value.strip()
        if v.endswith("ull") or v.endswith("ULL") or "0xFFFFFFFFFFFFFFFF" in v:
            t = "GLuint64"
        elif v.startswith("-"):
            t = "GLint"
        else:
            t = "GLenum"
        out.append(f"inline constexpr {t} {name} = {v};")
    out.append("")
    out.append("} } }      // namespace micron::gfx::gl")
    return "\n".join(out) + "\n"


def write_protos(pfns):
    out = [LICENSE_HEADER, "#pragma once", "", '#include "__gl_types.hpp"', ""]
    out.append("namespace micron { namespace gfx { namespace gl {")
    out.append("")
    out.append("// PFN<NAME>PROC typedefs for every GL 4.6 core entry point")
    out.append("")
    for name, ret, args in pfns:
        out.append(f"using {name} = {ret} (*)({args});")
    out.append("")
    out.append("} } }      // namespace micron::gfx::gl")
    return "\n".join(out) + "\n"


def write_table(apis):
    out = [LICENSE_HEADER, "#pragma once", "", '#include "__gl_protos.hpp"', ""]
    out.append("namespace micron { namespace gfx { namespace gl {")
    out.append("")
    out.append("// main entry metadata tbl")
    out.append("")
    out.append("struct sym_meta_t {")
    out.append("  const char *name;")
    out.append("  u16 index;")
    out.append("  u8 ver_major;")
    out.append("  u8 ver_minor;")
    out.append("};")
    out.append("")
    out.append("inline constexpr sym_meta_t gl_table[] = {")
    for i, (name, mj, mn) in enumerate(apis):
        out.append(f'  {{ "{name}", {i}, {mj}, {mn} }},')
    out.append("};")
    out.append("")
    out.append("inline constexpr usize gl_table_size = sizeof(gl_table) / sizeof(gl_table[0]);")
    out.append("")
    out.append("consteval u16")
    out.append("sym_index_of(const char *name) noexcept")
    out.append("{")
    out.append("  for ( u16 i = 0; i < gl_table_size; ++i ) {")
    out.append("    const char *a = gl_table[i].name;")
    out.append("    const char *b = name;")
    out.append("    while ( *a && *a == *b ) { ++a; ++b; }")
    out.append("    if ( *a == 0 && *b == 0 ) return i;")
    out.append("  }")
    out.append("  return u16(-1);")
    out.append("}")
    out.append("")
    out.append("}; }; };      // namespace micron::gfx::gl")
    return "\n".join(out) + "\n"


def write_opengl(apis):
    out = [LICENSE_HEADER, "#pragma once", ""]
    out.append('#include "__bits/__gl_enums.hpp"')
    out.append('#include "__bits/__gl_protos.hpp"')
    out.append('#include "__bits/__gl_table.hpp"')
    out.append('#include "__bits/__gl_types.hpp"')
    out.append("")
    out.append("// main openGL entries")
    out.append("")
    out.append("namespace micron { namespace gfx { namespace gl {")
    out.append("")

    # Inline-variable PFN pointers.
    for name, _mj, _mn in apis:
        out.append(f"inline {pfn_for(name)} {name} = nullptr;")
    out.append("")

    # Parallel slot table.
    out.append("// Parallel to gl_table[] by index — used by __load_core_4_6.")
    out.append("inline void **const __gl_fnptr_slots[] = {")
    for name, _mj, _mn in apis:
        out.append(f"  reinterpret_cast<void **>(&{name}),")
    out.append("};")
    out.append("")
    out.append("static_assert(sizeof(__gl_fnptr_slots) / sizeof(__gl_fnptr_slots[0]) == gl_table_size,")
    out.append('              "opengl.hpp __gl_fnptr_slots must parallel __gl_table.hpp gl_table by index");')
    out.append("")
    out.append("} ;      // namespace gl")
    out.append("};      // namespace gfx")
    out.append("")
    out.append("// forward every openGL entry point into micron::")
    for name, _mj, _mn in apis:
        out.append(f"using gfx::gl::{name};")
    out.append("")
    out.append("namespace gl = ::micron::gfx::gl;")
    out.append("")
    out.append("};      // namespace micron")
    return "\n".join(out) + "\n"


def main():
    if not GLCOREARB.exists():
        print(f"error: {GLCOREARB} not found — install mesa-libGL-devel or glcorearb.h", file=sys.stderr)
        return 1
    text = GLCOREARB.read_text()
    types, enums, pfns, apis = parse_glcorearb(text)

    print(f"parsed {len(types)} types, {len(enums)} enums, {len(pfns)} PFN typedefs, {len(apis)} entry points")

    BITS_DIR.mkdir(parents=True, exist_ok=True)
    (BITS_DIR / "__gl_types.hpp").write_text(write_types(types))
    (BITS_DIR / "__gl_enums.hpp").write_text(write_enums(enums))
    (BITS_DIR / "__gl_protos.hpp").write_text(write_protos(pfns))
    (BITS_DIR / "__gl_table.hpp").write_text(write_table(apis))
    OPENGL_HPP.write_text(write_opengl(apis))
    print(f"wrote {BITS_DIR}/__gl_types.hpp")
    print(f"wrote {BITS_DIR}/__gl_enums.hpp")
    print(f"wrote {BITS_DIR}/__gl_protos.hpp")
    print(f"wrote {BITS_DIR}/__gl_table.hpp")
    print(f"wrote {OPENGL_HPP}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
