//  Copyright (c) 2024- David Lucius Severus
//
//  Distributed under the Boost Software License, Version 1.0.
//  See accompanying file LICENSE_1_0.txt or copy at
//  http://www.boost.org/LICENSE_1_0.txt
//
//  *** AUTOGENERATED FILE; do not hand-edit; regenerate via:
//        python3 tools/vk_xml_gen/gen_vk.py ***

#pragma once

#include "__vk_types.hpp"

namespace micron
{
namespace gfx
{
namespace vk
{

// PFN_vkXxx typedefs for every selected entry point

using PFN_vkCreateInstance
    = VkResult (*)(const VkInstanceCreateInfo *pCreateInfo, const VkAllocationCallbacks *pAllocator, VkInstance *pInstance);
using PFN_vkDestroyInstance = void (*)(VkInstance instance, const VkAllocationCallbacks *pAllocator);
using PFN_vkEnumeratePhysicalDevices = VkResult (*)(VkInstance instance, u32 *pPhysicalDeviceCount, VkPhysicalDevice *pPhysicalDevices);
using PFN_vkGetPhysicalDeviceFeatures = void (*)(VkPhysicalDevice physicalDevice, VkPhysicalDeviceFeatures *pFeatures);
using PFN_vkGetPhysicalDeviceFormatProperties
    = void (*)(VkPhysicalDevice physicalDevice, VkFormat format, VkFormatProperties *pFormatProperties);
using PFN_vkGetPhysicalDeviceImageFormatProperties
    = VkResult (*)(VkPhysicalDevice physicalDevice, VkFormat format, VkImageType type, VkImageTiling tiling, VkImageUsageFlags usage,
                   VkImageCreateFlags flags, VkImageFormatProperties *pImageFormatProperties);
using PFN_vkGetPhysicalDeviceProperties = void (*)(VkPhysicalDevice physicalDevice, VkPhysicalDeviceProperties *pProperties);
using PFN_vkGetPhysicalDeviceQueueFamilyProperties
    = void (*)(VkPhysicalDevice physicalDevice, u32 *pQueueFamilyPropertyCount, VkQueueFamilyProperties *pQueueFamilyProperties);
using PFN_vkGetPhysicalDeviceMemoryProperties
    = void (*)(VkPhysicalDevice physicalDevice, VkPhysicalDeviceMemoryProperties *pMemoryProperties);
using PFN_vkGetInstanceProcAddr = PFN_vkVoidFunction (*)(VkInstance instance, const char *pName);
using PFN_vkGetDeviceProcAddr = PFN_vkVoidFunction (*)(VkDevice device, const char *pName);
using PFN_vkCreateDevice = VkResult (*)(VkPhysicalDevice physicalDevice, const VkDeviceCreateInfo *pCreateInfo,
                                        const VkAllocationCallbacks *pAllocator, VkDevice *pDevice);
using PFN_vkDestroyDevice = void (*)(VkDevice device, const VkAllocationCallbacks *pAllocator);
using PFN_vkEnumerateInstanceExtensionProperties
    = VkResult (*)(const char *pLayerName, u32 *pPropertyCount, VkExtensionProperties *pProperties);
using PFN_vkEnumerateDeviceExtensionProperties
    = VkResult (*)(VkPhysicalDevice physicalDevice, const char *pLayerName, u32 *pPropertyCount, VkExtensionProperties *pProperties);
using PFN_vkEnumerateInstanceLayerProperties = VkResult (*)(u32 *pPropertyCount, VkLayerProperties *pProperties);
using PFN_vkEnumerateDeviceLayerProperties
    = VkResult (*)(VkPhysicalDevice physicalDevice, u32 *pPropertyCount, VkLayerProperties *pProperties);
using PFN_vkGetDeviceQueue = void (*)(VkDevice device, u32 queueFamilyIndex, u32 queueIndex, VkQueue *pQueue);
using PFN_vkQueueSubmit = VkResult (*)(VkQueue queue, u32 submitCount, const VkSubmitInfo *pSubmits, VkFence fence);
using PFN_vkQueueWaitIdle = VkResult (*)(VkQueue queue);
using PFN_vkDeviceWaitIdle = VkResult (*)(VkDevice device);
using PFN_vkAllocateMemory = VkResult (*)(VkDevice device, const VkMemoryAllocateInfo *pAllocateInfo,
                                          const VkAllocationCallbacks *pAllocator, VkDeviceMemory *pMemory);
using PFN_vkFreeMemory = void (*)(VkDevice device, VkDeviceMemory memory, const VkAllocationCallbacks *pAllocator);
using PFN_vkMapMemory
    = VkResult (*)(VkDevice device, VkDeviceMemory memory, VkDeviceSize offset, VkDeviceSize size, VkMemoryMapFlags flags, void **ppData);
using PFN_vkUnmapMemory = void (*)(VkDevice device, VkDeviceMemory memory);
using PFN_vkFlushMappedMemoryRanges = VkResult (*)(VkDevice device, u32 memoryRangeCount, const VkMappedMemoryRange *pMemoryRanges);
using PFN_vkInvalidateMappedMemoryRanges = VkResult (*)(VkDevice device, u32 memoryRangeCount, const VkMappedMemoryRange *pMemoryRanges);
using PFN_vkGetDeviceMemoryCommitment = void (*)(VkDevice device, VkDeviceMemory memory, VkDeviceSize *pCommittedMemoryInBytes);
using PFN_vkBindBufferMemory = VkResult (*)(VkDevice device, VkBuffer buffer, VkDeviceMemory memory, VkDeviceSize memoryOffset);
using PFN_vkBindImageMemory = VkResult (*)(VkDevice device, VkImage image, VkDeviceMemory memory, VkDeviceSize memoryOffset);
using PFN_vkGetBufferMemoryRequirements = void (*)(VkDevice device, VkBuffer buffer, VkMemoryRequirements *pMemoryRequirements);
using PFN_vkGetImageMemoryRequirements = void (*)(VkDevice device, VkImage image, VkMemoryRequirements *pMemoryRequirements);
using PFN_vkGetImageSparseMemoryRequirements = void (*)(VkDevice device, VkImage image, u32 *pSparseMemoryRequirementCount,
                                                        VkSparseImageMemoryRequirements *pSparseMemoryRequirements);
using PFN_vkGetPhysicalDeviceSparseImageFormatProperties
    = void (*)(VkPhysicalDevice physicalDevice, VkFormat format, VkImageType type, VkSampleCountFlagBits samples, VkImageUsageFlags usage,
               VkImageTiling tiling, u32 *pPropertyCount, VkSparseImageFormatProperties *pProperties);
using PFN_vkQueueBindSparse = VkResult (*)(VkQueue queue, u32 bindInfoCount, const VkBindSparseInfo *pBindInfo, VkFence fence);
using PFN_vkCreateFence
    = VkResult (*)(VkDevice device, const VkFenceCreateInfo *pCreateInfo, const VkAllocationCallbacks *pAllocator, VkFence *pFence);
using PFN_vkDestroyFence = void (*)(VkDevice device, VkFence fence, const VkAllocationCallbacks *pAllocator);
using PFN_vkResetFences = VkResult (*)(VkDevice device, u32 fenceCount, const VkFence *pFences);
using PFN_vkGetFenceStatus = VkResult (*)(VkDevice device, VkFence fence);
using PFN_vkWaitForFences = VkResult (*)(VkDevice device, u32 fenceCount, const VkFence *pFences, VkBool32 waitAll, u64 timeout);
using PFN_vkCreateSemaphore = VkResult (*)(VkDevice device, const VkSemaphoreCreateInfo *pCreateInfo,
                                           const VkAllocationCallbacks *pAllocator, VkSemaphore *pSemaphore);
using PFN_vkDestroySemaphore = void (*)(VkDevice device, VkSemaphore semaphore, const VkAllocationCallbacks *pAllocator);
using PFN_vkCreateEvent
    = VkResult (*)(VkDevice device, const VkEventCreateInfo *pCreateInfo, const VkAllocationCallbacks *pAllocator, VkEvent *pEvent);
using PFN_vkDestroyEvent = void (*)(VkDevice device, VkEvent event, const VkAllocationCallbacks *pAllocator);
using PFN_vkGetEventStatus = VkResult (*)(VkDevice device, VkEvent event);
using PFN_vkSetEvent = VkResult (*)(VkDevice device, VkEvent event);
using PFN_vkResetEvent = VkResult (*)(VkDevice device, VkEvent event);
using PFN_vkCreateQueryPool = VkResult (*)(VkDevice device, const VkQueryPoolCreateInfo *pCreateInfo,
                                           const VkAllocationCallbacks *pAllocator, VkQueryPool *pQueryPool);
using PFN_vkDestroyQueryPool = void (*)(VkDevice device, VkQueryPool queryPool, const VkAllocationCallbacks *pAllocator);
using PFN_vkGetQueryPoolResults = VkResult (*)(VkDevice device, VkQueryPool queryPool, u32 firstQuery, u32 queryCount, usize dataSize,
                                               void *pData, VkDeviceSize stride, VkQueryResultFlags flags);
using PFN_vkCreateBuffer
    = VkResult (*)(VkDevice device, const VkBufferCreateInfo *pCreateInfo, const VkAllocationCallbacks *pAllocator, VkBuffer *pBuffer);
using PFN_vkDestroyBuffer = void (*)(VkDevice device, VkBuffer buffer, const VkAllocationCallbacks *pAllocator);
using PFN_vkCreateBufferView = VkResult (*)(VkDevice device, const VkBufferViewCreateInfo *pCreateInfo,
                                            const VkAllocationCallbacks *pAllocator, VkBufferView *pView);
using PFN_vkDestroyBufferView = void (*)(VkDevice device, VkBufferView bufferView, const VkAllocationCallbacks *pAllocator);
using PFN_vkCreateImage
    = VkResult (*)(VkDevice device, const VkImageCreateInfo *pCreateInfo, const VkAllocationCallbacks *pAllocator, VkImage *pImage);
using PFN_vkDestroyImage = void (*)(VkDevice device, VkImage image, const VkAllocationCallbacks *pAllocator);
using PFN_vkGetImageSubresourceLayout
    = void (*)(VkDevice device, VkImage image, const VkImageSubresource *pSubresource, VkSubresourceLayout *pLayout);
using PFN_vkCreateImageView
    = VkResult (*)(VkDevice device, const VkImageViewCreateInfo *pCreateInfo, const VkAllocationCallbacks *pAllocator, VkImageView *pView);
using PFN_vkDestroyImageView = void (*)(VkDevice device, VkImageView imageView, const VkAllocationCallbacks *pAllocator);
using PFN_vkCreateShaderModule = VkResult (*)(VkDevice device, const VkShaderModuleCreateInfo *pCreateInfo,
                                              const VkAllocationCallbacks *pAllocator, VkShaderModule *pShaderModule);
using PFN_vkDestroyShaderModule = void (*)(VkDevice device, VkShaderModule shaderModule, const VkAllocationCallbacks *pAllocator);
using PFN_vkCreatePipelineCache = VkResult (*)(VkDevice device, const VkPipelineCacheCreateInfo *pCreateInfo,
                                               const VkAllocationCallbacks *pAllocator, VkPipelineCache *pPipelineCache);
using PFN_vkDestroyPipelineCache = void (*)(VkDevice device, VkPipelineCache pipelineCache, const VkAllocationCallbacks *pAllocator);
using PFN_vkGetPipelineCacheData = VkResult (*)(VkDevice device, VkPipelineCache pipelineCache, usize *pDataSize, void *pData);
using PFN_vkMergePipelineCaches
    = VkResult (*)(VkDevice device, VkPipelineCache dstCache, u32 srcCacheCount, const VkPipelineCache *pSrcCaches);
using PFN_vkCreateGraphicsPipelines
    = VkResult (*)(VkDevice device, VkPipelineCache pipelineCache, u32 createInfoCount, const VkGraphicsPipelineCreateInfo *pCreateInfos,
                   const VkAllocationCallbacks *pAllocator, VkPipeline *pPipelines);
using PFN_vkCreateComputePipelines
    = VkResult (*)(VkDevice device, VkPipelineCache pipelineCache, u32 createInfoCount, const VkComputePipelineCreateInfo *pCreateInfos,
                   const VkAllocationCallbacks *pAllocator, VkPipeline *pPipelines);
using PFN_vkDestroyPipeline = void (*)(VkDevice device, VkPipeline pipeline, const VkAllocationCallbacks *pAllocator);
using PFN_vkCreatePipelineLayout = VkResult (*)(VkDevice device, const VkPipelineLayoutCreateInfo *pCreateInfo,
                                                const VkAllocationCallbacks *pAllocator, VkPipelineLayout *pPipelineLayout);
using PFN_vkDestroyPipelineLayout = void (*)(VkDevice device, VkPipelineLayout pipelineLayout, const VkAllocationCallbacks *pAllocator);
using PFN_vkCreateSampler
    = VkResult (*)(VkDevice device, const VkSamplerCreateInfo *pCreateInfo, const VkAllocationCallbacks *pAllocator, VkSampler *pSampler);
using PFN_vkDestroySampler = void (*)(VkDevice device, VkSampler sampler, const VkAllocationCallbacks *pAllocator);
using PFN_vkCreateDescriptorSetLayout = VkResult (*)(VkDevice device, const VkDescriptorSetLayoutCreateInfo *pCreateInfo,
                                                     const VkAllocationCallbacks *pAllocator, VkDescriptorSetLayout *pSetLayout);
using PFN_vkDestroyDescriptorSetLayout
    = void (*)(VkDevice device, VkDescriptorSetLayout descriptorSetLayout, const VkAllocationCallbacks *pAllocator);
using PFN_vkCreateDescriptorPool = VkResult (*)(VkDevice device, const VkDescriptorPoolCreateInfo *pCreateInfo,
                                                const VkAllocationCallbacks *pAllocator, VkDescriptorPool *pDescriptorPool);
using PFN_vkDestroyDescriptorPool = void (*)(VkDevice device, VkDescriptorPool descriptorPool, const VkAllocationCallbacks *pAllocator);
using PFN_vkResetDescriptorPool = VkResult (*)(VkDevice device, VkDescriptorPool descriptorPool, VkDescriptorPoolResetFlags flags);
using PFN_vkAllocateDescriptorSets
    = VkResult (*)(VkDevice device, const VkDescriptorSetAllocateInfo *pAllocateInfo, VkDescriptorSet *pDescriptorSets);
using PFN_vkFreeDescriptorSets
    = VkResult (*)(VkDevice device, VkDescriptorPool descriptorPool, u32 descriptorSetCount, const VkDescriptorSet *pDescriptorSets);
using PFN_vkUpdateDescriptorSets = void (*)(VkDevice device, u32 descriptorWriteCount, const VkWriteDescriptorSet *pDescriptorWrites,
                                            u32 descriptorCopyCount, const VkCopyDescriptorSet *pDescriptorCopies);
using PFN_vkCreateFramebuffer = VkResult (*)(VkDevice device, const VkFramebufferCreateInfo *pCreateInfo,
                                             const VkAllocationCallbacks *pAllocator, VkFramebuffer *pFramebuffer);
using PFN_vkDestroyFramebuffer = void (*)(VkDevice device, VkFramebuffer framebuffer, const VkAllocationCallbacks *pAllocator);
using PFN_vkCreateRenderPass = VkResult (*)(VkDevice device, const VkRenderPassCreateInfo *pCreateInfo,
                                            const VkAllocationCallbacks *pAllocator, VkRenderPass *pRenderPass);
using PFN_vkDestroyRenderPass = void (*)(VkDevice device, VkRenderPass renderPass, const VkAllocationCallbacks *pAllocator);
using PFN_vkGetRenderAreaGranularity = void (*)(VkDevice device, VkRenderPass renderPass, VkExtent2D *pGranularity);
using PFN_vkCreateCommandPool = VkResult (*)(VkDevice device, const VkCommandPoolCreateInfo *pCreateInfo,
                                             const VkAllocationCallbacks *pAllocator, VkCommandPool *pCommandPool);
using PFN_vkDestroyCommandPool = void (*)(VkDevice device, VkCommandPool commandPool, const VkAllocationCallbacks *pAllocator);
using PFN_vkResetCommandPool = VkResult (*)(VkDevice device, VkCommandPool commandPool, VkCommandPoolResetFlags flags);
using PFN_vkAllocateCommandBuffers
    = VkResult (*)(VkDevice device, const VkCommandBufferAllocateInfo *pAllocateInfo, VkCommandBuffer *pCommandBuffers);
using PFN_vkFreeCommandBuffers
    = void (*)(VkDevice device, VkCommandPool commandPool, u32 commandBufferCount, const VkCommandBuffer *pCommandBuffers);
using PFN_vkBeginCommandBuffer = VkResult (*)(VkCommandBuffer commandBuffer, const VkCommandBufferBeginInfo *pBeginInfo);
using PFN_vkEndCommandBuffer = VkResult (*)(VkCommandBuffer commandBuffer);
using PFN_vkResetCommandBuffer = VkResult (*)(VkCommandBuffer commandBuffer, VkCommandBufferResetFlags flags);
using PFN_vkCmdBindPipeline = void (*)(VkCommandBuffer commandBuffer, VkPipelineBindPoint pipelineBindPoint, VkPipeline pipeline);
using PFN_vkCmdSetViewport = void (*)(VkCommandBuffer commandBuffer, u32 firstViewport, u32 viewportCount, const VkViewport *pViewports);
using PFN_vkCmdSetScissor = void (*)(VkCommandBuffer commandBuffer, u32 firstScissor, u32 scissorCount, const VkRect2D *pScissors);
using PFN_vkCmdSetLineWidth = void (*)(VkCommandBuffer commandBuffer, float lineWidth);
using PFN_vkCmdSetDepthBias
    = void (*)(VkCommandBuffer commandBuffer, float depthBiasConstantFactor, float depthBiasClamp, float depthBiasSlopeFactor);
using PFN_vkCmdSetBlendConstants = void (*)(VkCommandBuffer commandBuffer, const float blendConstants[4]);
using PFN_vkCmdSetDepthBounds = void (*)(VkCommandBuffer commandBuffer, float minDepthBounds, float maxDepthBounds);
using PFN_vkCmdSetStencilCompareMask = void (*)(VkCommandBuffer commandBuffer, VkStencilFaceFlags faceMask, u32 compareMask);
using PFN_vkCmdSetStencilWriteMask = void (*)(VkCommandBuffer commandBuffer, VkStencilFaceFlags faceMask, u32 writeMask);
using PFN_vkCmdSetStencilReference = void (*)(VkCommandBuffer commandBuffer, VkStencilFaceFlags faceMask, u32 reference);
using PFN_vkCmdBindDescriptorSets
    = void (*)(VkCommandBuffer commandBuffer, VkPipelineBindPoint pipelineBindPoint, VkPipelineLayout layout, u32 firstSet,
               u32 descriptorSetCount, const VkDescriptorSet *pDescriptorSets, u32 dynamicOffsetCount, const u32 *pDynamicOffsets);
using PFN_vkCmdBindIndexBuffer = void (*)(VkCommandBuffer commandBuffer, VkBuffer buffer, VkDeviceSize offset, VkIndexType indexType);
using PFN_vkCmdBindVertexBuffers
    = void (*)(VkCommandBuffer commandBuffer, u32 firstBinding, u32 bindingCount, const VkBuffer *pBuffers, const VkDeviceSize *pOffsets);
using PFN_vkCmdDraw = void (*)(VkCommandBuffer commandBuffer, u32 vertexCount, u32 instanceCount, u32 firstVertex, u32 firstInstance);
using PFN_vkCmdDrawIndexed
    = void (*)(VkCommandBuffer commandBuffer, u32 indexCount, u32 instanceCount, u32 firstIndex, i32 vertexOffset, u32 firstInstance);
using PFN_vkCmdDrawIndirect = void (*)(VkCommandBuffer commandBuffer, VkBuffer buffer, VkDeviceSize offset, u32 drawCount, u32 stride);
using PFN_vkCmdDrawIndexedIndirect
    = void (*)(VkCommandBuffer commandBuffer, VkBuffer buffer, VkDeviceSize offset, u32 drawCount, u32 stride);
using PFN_vkCmdDispatch = void (*)(VkCommandBuffer commandBuffer, u32 groupCountX, u32 groupCountY, u32 groupCountZ);
using PFN_vkCmdDispatchIndirect = void (*)(VkCommandBuffer commandBuffer, VkBuffer buffer, VkDeviceSize offset);
using PFN_vkCmdCopyBuffer
    = void (*)(VkCommandBuffer commandBuffer, VkBuffer srcBuffer, VkBuffer dstBuffer, u32 regionCount, const VkBufferCopy *pRegions);
using PFN_vkCmdCopyImage = void (*)(VkCommandBuffer commandBuffer, VkImage srcImage, VkImageLayout srcImageLayout, VkImage dstImage,
                                    VkImageLayout dstImageLayout, u32 regionCount, const VkImageCopy *pRegions);
using PFN_vkCmdBlitImage = void (*)(VkCommandBuffer commandBuffer, VkImage srcImage, VkImageLayout srcImageLayout, VkImage dstImage,
                                    VkImageLayout dstImageLayout, u32 regionCount, const VkImageBlit *pRegions, VkFilter filter);
using PFN_vkCmdCopyBufferToImage = void (*)(VkCommandBuffer commandBuffer, VkBuffer srcBuffer, VkImage dstImage,
                                            VkImageLayout dstImageLayout, u32 regionCount, const VkBufferImageCopy *pRegions);
using PFN_vkCmdCopyImageToBuffer = void (*)(VkCommandBuffer commandBuffer, VkImage srcImage, VkImageLayout srcImageLayout,
                                            VkBuffer dstBuffer, u32 regionCount, const VkBufferImageCopy *pRegions);
using PFN_vkCmdUpdateBuffer
    = void (*)(VkCommandBuffer commandBuffer, VkBuffer dstBuffer, VkDeviceSize dstOffset, VkDeviceSize dataSize, const void *pData);
using PFN_vkCmdFillBuffer
    = void (*)(VkCommandBuffer commandBuffer, VkBuffer dstBuffer, VkDeviceSize dstOffset, VkDeviceSize size, u32 data);
using PFN_vkCmdClearColorImage = void (*)(VkCommandBuffer commandBuffer, VkImage image, VkImageLayout imageLayout,
                                          const VkClearColorValue *pColor, u32 rangeCount, const VkImageSubresourceRange *pRanges);
using PFN_vkCmdClearDepthStencilImage
    = void (*)(VkCommandBuffer commandBuffer, VkImage image, VkImageLayout imageLayout, const VkClearDepthStencilValue *pDepthStencil,
               u32 rangeCount, const VkImageSubresourceRange *pRanges);
using PFN_vkCmdClearAttachments = void (*)(VkCommandBuffer commandBuffer, u32 attachmentCount, const VkClearAttachment *pAttachments,
                                           u32 rectCount, const VkClearRect *pRects);
using PFN_vkCmdResolveImage = void (*)(VkCommandBuffer commandBuffer, VkImage srcImage, VkImageLayout srcImageLayout, VkImage dstImage,
                                       VkImageLayout dstImageLayout, u32 regionCount, const VkImageResolve *pRegions);
using PFN_vkCmdSetEvent = void (*)(VkCommandBuffer commandBuffer, VkEvent event, VkPipelineStageFlags stageMask);
using PFN_vkCmdResetEvent = void (*)(VkCommandBuffer commandBuffer, VkEvent event, VkPipelineStageFlags stageMask);
using PFN_vkCmdWaitEvents
    = void (*)(VkCommandBuffer commandBuffer, u32 eventCount, const VkEvent *pEvents, VkPipelineStageFlags srcStageMask,
               VkPipelineStageFlags dstStageMask, u32 memoryBarrierCount, const VkMemoryBarrier *pMemoryBarriers,
               u32 bufferMemoryBarrierCount, const VkBufferMemoryBarrier *pBufferMemoryBarriers, u32 imageMemoryBarrierCount,
               const VkImageMemoryBarrier *pImageMemoryBarriers);
using PFN_vkCmdPipelineBarrier
    = void (*)(VkCommandBuffer commandBuffer, VkPipelineStageFlags srcStageMask, VkPipelineStageFlags dstStageMask,
               VkDependencyFlags dependencyFlags, u32 memoryBarrierCount, const VkMemoryBarrier *pMemoryBarriers,
               u32 bufferMemoryBarrierCount, const VkBufferMemoryBarrier *pBufferMemoryBarriers, u32 imageMemoryBarrierCount,
               const VkImageMemoryBarrier *pImageMemoryBarriers);
using PFN_vkCmdBeginQuery = void (*)(VkCommandBuffer commandBuffer, VkQueryPool queryPool, u32 query, VkQueryControlFlags flags);
using PFN_vkCmdEndQuery = void (*)(VkCommandBuffer commandBuffer, VkQueryPool queryPool, u32 query);
using PFN_vkCmdResetQueryPool = void (*)(VkCommandBuffer commandBuffer, VkQueryPool queryPool, u32 firstQuery, u32 queryCount);
using PFN_vkCmdWriteTimestamp
    = void (*)(VkCommandBuffer commandBuffer, VkPipelineStageFlagBits pipelineStage, VkQueryPool queryPool, u32 query);
using PFN_vkCmdCopyQueryPoolResults = void (*)(VkCommandBuffer commandBuffer, VkQueryPool queryPool, u32 firstQuery, u32 queryCount,
                                               VkBuffer dstBuffer, VkDeviceSize dstOffset, VkDeviceSize stride, VkQueryResultFlags flags);
using PFN_vkCmdPushConstants = void (*)(VkCommandBuffer commandBuffer, VkPipelineLayout layout, VkShaderStageFlags stageFlags, u32 offset,
                                        u32 size, const void *pValues);
using PFN_vkCmdBeginRenderPass
    = void (*)(VkCommandBuffer commandBuffer, const VkRenderPassBeginInfo *pRenderPassBegin, VkSubpassContents contents);
using PFN_vkCmdNextSubpass = void (*)(VkCommandBuffer commandBuffer, VkSubpassContents contents);
using PFN_vkCmdEndRenderPass = void (*)(VkCommandBuffer commandBuffer);
using PFN_vkCmdExecuteCommands = void (*)(VkCommandBuffer commandBuffer, u32 commandBufferCount, const VkCommandBuffer *pCommandBuffers);
using PFN_vkEnumerateInstanceVersion = VkResult (*)(u32 *pApiVersion);
using PFN_vkBindBufferMemory2 = VkResult (*)(VkDevice device, u32 bindInfoCount, const VkBindBufferMemoryInfo *pBindInfos);
using PFN_vkBindImageMemory2 = VkResult (*)(VkDevice device, u32 bindInfoCount, const VkBindImageMemoryInfo *pBindInfos);
using PFN_vkGetDeviceGroupPeerMemoryFeatures
    = void (*)(VkDevice device, u32 heapIndex, u32 localDeviceIndex, u32 remoteDeviceIndex, VkPeerMemoryFeatureFlags *pPeerMemoryFeatures);
using PFN_vkCmdSetDeviceMask = void (*)(VkCommandBuffer commandBuffer, u32 deviceMask);
using PFN_vkCmdDispatchBase = void (*)(VkCommandBuffer commandBuffer, u32 baseGroupX, u32 baseGroupY, u32 baseGroupZ, u32 groupCountX,
                                       u32 groupCountY, u32 groupCountZ);
using PFN_vkEnumeratePhysicalDeviceGroups
    = VkResult (*)(VkInstance instance, u32 *pPhysicalDeviceGroupCount, VkPhysicalDeviceGroupProperties *pPhysicalDeviceGroupProperties);
using PFN_vkGetImageMemoryRequirements2
    = void (*)(VkDevice device, const VkImageMemoryRequirementsInfo2 *pInfo, VkMemoryRequirements2 *pMemoryRequirements);
using PFN_vkGetBufferMemoryRequirements2
    = void (*)(VkDevice device, const VkBufferMemoryRequirementsInfo2 *pInfo, VkMemoryRequirements2 *pMemoryRequirements);
using PFN_vkGetImageSparseMemoryRequirements2
    = void (*)(VkDevice device, const VkImageSparseMemoryRequirementsInfo2 *pInfo, u32 *pSparseMemoryRequirementCount,
               VkSparseImageMemoryRequirements2 *pSparseMemoryRequirements);
using PFN_vkGetPhysicalDeviceFeatures2 = void (*)(VkPhysicalDevice physicalDevice, VkPhysicalDeviceFeatures2 *pFeatures);
using PFN_vkGetPhysicalDeviceProperties2 = void (*)(VkPhysicalDevice physicalDevice, VkPhysicalDeviceProperties2 *pProperties);
using PFN_vkGetPhysicalDeviceFormatProperties2
    = void (*)(VkPhysicalDevice physicalDevice, VkFormat format, VkFormatProperties2 *pFormatProperties);
using PFN_vkGetPhysicalDeviceImageFormatProperties2
    = VkResult (*)(VkPhysicalDevice physicalDevice, const VkPhysicalDeviceImageFormatInfo2 *pImageFormatInfo,
                   VkImageFormatProperties2 *pImageFormatProperties);
using PFN_vkGetPhysicalDeviceQueueFamilyProperties2
    = void (*)(VkPhysicalDevice physicalDevice, u32 *pQueueFamilyPropertyCount, VkQueueFamilyProperties2 *pQueueFamilyProperties);
using PFN_vkGetPhysicalDeviceMemoryProperties2
    = void (*)(VkPhysicalDevice physicalDevice, VkPhysicalDeviceMemoryProperties2 *pMemoryProperties);
using PFN_vkGetPhysicalDeviceSparseImageFormatProperties2
    = void (*)(VkPhysicalDevice physicalDevice, const VkPhysicalDeviceSparseImageFormatInfo2 *pFormatInfo, u32 *pPropertyCount,
               VkSparseImageFormatProperties2 *pProperties);
using PFN_vkTrimCommandPool = void (*)(VkDevice device, VkCommandPool commandPool, VkCommandPoolTrimFlags flags);
using PFN_vkGetDeviceQueue2 = void (*)(VkDevice device, const VkDeviceQueueInfo2 *pQueueInfo, VkQueue *pQueue);
using PFN_vkCreateSamplerYcbcrConversion
    = VkResult (*)(VkDevice device, const VkSamplerYcbcrConversionCreateInfo *pCreateInfo, const VkAllocationCallbacks *pAllocator,
                   VkSamplerYcbcrConversion *pYcbcrConversion);
using PFN_vkDestroySamplerYcbcrConversion
    = void (*)(VkDevice device, VkSamplerYcbcrConversion ycbcrConversion, const VkAllocationCallbacks *pAllocator);
using PFN_vkCreateDescriptorUpdateTemplate
    = VkResult (*)(VkDevice device, const VkDescriptorUpdateTemplateCreateInfo *pCreateInfo, const VkAllocationCallbacks *pAllocator,
                   VkDescriptorUpdateTemplate *pDescriptorUpdateTemplate);
using PFN_vkDestroyDescriptorUpdateTemplate
    = void (*)(VkDevice device, VkDescriptorUpdateTemplate descriptorUpdateTemplate, const VkAllocationCallbacks *pAllocator);
using PFN_vkUpdateDescriptorSetWithTemplate
    = void (*)(VkDevice device, VkDescriptorSet descriptorSet, VkDescriptorUpdateTemplate descriptorUpdateTemplate, const void *pData);
using PFN_vkGetPhysicalDeviceExternalBufferProperties
    = void (*)(VkPhysicalDevice physicalDevice, const VkPhysicalDeviceExternalBufferInfo *pExternalBufferInfo,
               VkExternalBufferProperties *pExternalBufferProperties);
using PFN_vkGetPhysicalDeviceExternalFenceProperties
    = void (*)(VkPhysicalDevice physicalDevice, const VkPhysicalDeviceExternalFenceInfo *pExternalFenceInfo,
               VkExternalFenceProperties *pExternalFenceProperties);
using PFN_vkGetPhysicalDeviceExternalSemaphoreProperties
    = void (*)(VkPhysicalDevice physicalDevice, const VkPhysicalDeviceExternalSemaphoreInfo *pExternalSemaphoreInfo,
               VkExternalSemaphoreProperties *pExternalSemaphoreProperties);
using PFN_vkGetDescriptorSetLayoutSupport
    = void (*)(VkDevice device, const VkDescriptorSetLayoutCreateInfo *pCreateInfo, VkDescriptorSetLayoutSupport *pSupport);
using PFN_vkCmdDrawIndirectCount = void (*)(VkCommandBuffer commandBuffer, VkBuffer buffer, VkDeviceSize offset, VkBuffer countBuffer,
                                            VkDeviceSize countBufferOffset, u32 maxDrawCount, u32 stride);
using PFN_vkCmdDrawIndexedIndirectCount = void (*)(VkCommandBuffer commandBuffer, VkBuffer buffer, VkDeviceSize offset,
                                                   VkBuffer countBuffer, VkDeviceSize countBufferOffset, u32 maxDrawCount, u32 stride);
using PFN_vkCreateRenderPass2 = VkResult (*)(VkDevice device, const VkRenderPassCreateInfo2 *pCreateInfo,
                                             const VkAllocationCallbacks *pAllocator, VkRenderPass *pRenderPass);
using PFN_vkCmdBeginRenderPass2
    = void (*)(VkCommandBuffer commandBuffer, const VkRenderPassBeginInfo *pRenderPassBegin, const VkSubpassBeginInfo *pSubpassBeginInfo);
using PFN_vkCmdNextSubpass2
    = void (*)(VkCommandBuffer commandBuffer, const VkSubpassBeginInfo *pSubpassBeginInfo, const VkSubpassEndInfo *pSubpassEndInfo);
using PFN_vkCmdEndRenderPass2 = void (*)(VkCommandBuffer commandBuffer, const VkSubpassEndInfo *pSubpassEndInfo);
using PFN_vkResetQueryPool = void (*)(VkDevice device, VkQueryPool queryPool, u32 firstQuery, u32 queryCount);
using PFN_vkGetSemaphoreCounterValue = VkResult (*)(VkDevice device, VkSemaphore semaphore, u64 *pValue);
using PFN_vkWaitSemaphores = VkResult (*)(VkDevice device, const VkSemaphoreWaitInfo *pWaitInfo, u64 timeout);
using PFN_vkSignalSemaphore = VkResult (*)(VkDevice device, const VkSemaphoreSignalInfo *pSignalInfo);
using PFN_vkGetBufferDeviceAddress = VkDeviceAddress (*)(VkDevice device, const VkBufferDeviceAddressInfo *pInfo);
using PFN_vkGetBufferOpaqueCaptureAddress = u64 (*)(VkDevice device, const VkBufferDeviceAddressInfo *pInfo);
using PFN_vkGetDeviceMemoryOpaqueCaptureAddress = u64 (*)(VkDevice device, const VkDeviceMemoryOpaqueCaptureAddressInfo *pInfo);
using PFN_vkGetPhysicalDeviceToolProperties
    = VkResult (*)(VkPhysicalDevice physicalDevice, u32 *pToolCount, VkPhysicalDeviceToolProperties *pToolProperties);
using PFN_vkCreatePrivateDataSlot = VkResult (*)(VkDevice device, const VkPrivateDataSlotCreateInfo *pCreateInfo,
                                                 const VkAllocationCallbacks *pAllocator, VkPrivateDataSlot *pPrivateDataSlot);
using PFN_vkDestroyPrivateDataSlot = void (*)(VkDevice device, VkPrivateDataSlot privateDataSlot, const VkAllocationCallbacks *pAllocator);
using PFN_vkSetPrivateData
    = VkResult (*)(VkDevice device, VkObjectType objectType, u64 objectHandle, VkPrivateDataSlot privateDataSlot, u64 data);
using PFN_vkGetPrivateData
    = void (*)(VkDevice device, VkObjectType objectType, u64 objectHandle, VkPrivateDataSlot privateDataSlot, u64 *pData);
using PFN_vkCmdSetEvent2 = void (*)(VkCommandBuffer commandBuffer, VkEvent event, const VkDependencyInfo *pDependencyInfo);
using PFN_vkCmdResetEvent2 = void (*)(VkCommandBuffer commandBuffer, VkEvent event, VkPipelineStageFlags2 stageMask);
using PFN_vkCmdWaitEvents2
    = void (*)(VkCommandBuffer commandBuffer, u32 eventCount, const VkEvent *pEvents, const VkDependencyInfo *pDependencyInfos);
using PFN_vkCmdPipelineBarrier2 = void (*)(VkCommandBuffer commandBuffer, const VkDependencyInfo *pDependencyInfo);
using PFN_vkCmdWriteTimestamp2 = void (*)(VkCommandBuffer commandBuffer, VkPipelineStageFlags2 stage, VkQueryPool queryPool, u32 query);
using PFN_vkQueueSubmit2 = VkResult (*)(VkQueue queue, u32 submitCount, const VkSubmitInfo2 *pSubmits, VkFence fence);
using PFN_vkCmdCopyBuffer2 = void (*)(VkCommandBuffer commandBuffer, const VkCopyBufferInfo2 *pCopyBufferInfo);
using PFN_vkCmdCopyImage2 = void (*)(VkCommandBuffer commandBuffer, const VkCopyImageInfo2 *pCopyImageInfo);
using PFN_vkCmdCopyBufferToImage2 = void (*)(VkCommandBuffer commandBuffer, const VkCopyBufferToImageInfo2 *pCopyBufferToImageInfo);
using PFN_vkCmdCopyImageToBuffer2 = void (*)(VkCommandBuffer commandBuffer, const VkCopyImageToBufferInfo2 *pCopyImageToBufferInfo);
using PFN_vkCmdBlitImage2 = void (*)(VkCommandBuffer commandBuffer, const VkBlitImageInfo2 *pBlitImageInfo);
using PFN_vkCmdResolveImage2 = void (*)(VkCommandBuffer commandBuffer, const VkResolveImageInfo2 *pResolveImageInfo);
using PFN_vkCmdBeginRendering = void (*)(VkCommandBuffer commandBuffer, const VkRenderingInfo *pRenderingInfo);
using PFN_vkCmdEndRendering = void (*)(VkCommandBuffer commandBuffer);
using PFN_vkCmdSetCullMode = void (*)(VkCommandBuffer commandBuffer, VkCullModeFlags cullMode);
using PFN_vkCmdSetFrontFace = void (*)(VkCommandBuffer commandBuffer, VkFrontFace frontFace);
using PFN_vkCmdSetPrimitiveTopology = void (*)(VkCommandBuffer commandBuffer, VkPrimitiveTopology primitiveTopology);
using PFN_vkCmdSetViewportWithCount = void (*)(VkCommandBuffer commandBuffer, u32 viewportCount, const VkViewport *pViewports);
using PFN_vkCmdSetScissorWithCount = void (*)(VkCommandBuffer commandBuffer, u32 scissorCount, const VkRect2D *pScissors);
using PFN_vkCmdBindVertexBuffers2 = void (*)(VkCommandBuffer commandBuffer, u32 firstBinding, u32 bindingCount, const VkBuffer *pBuffers,
                                             const VkDeviceSize *pOffsets, const VkDeviceSize *pSizes, const VkDeviceSize *pStrides);
using PFN_vkCmdSetDepthTestEnable = void (*)(VkCommandBuffer commandBuffer, VkBool32 depthTestEnable);
using PFN_vkCmdSetDepthWriteEnable = void (*)(VkCommandBuffer commandBuffer, VkBool32 depthWriteEnable);
using PFN_vkCmdSetDepthCompareOp = void (*)(VkCommandBuffer commandBuffer, VkCompareOp depthCompareOp);
using PFN_vkCmdSetDepthBoundsTestEnable = void (*)(VkCommandBuffer commandBuffer, VkBool32 depthBoundsTestEnable);
using PFN_vkCmdSetStencilTestEnable = void (*)(VkCommandBuffer commandBuffer, VkBool32 stencilTestEnable);
using PFN_vkCmdSetStencilOp = void (*)(VkCommandBuffer commandBuffer, VkStencilFaceFlags faceMask, VkStencilOp failOp, VkStencilOp passOp,
                                       VkStencilOp depthFailOp, VkCompareOp compareOp);
using PFN_vkCmdSetRasterizerDiscardEnable = void (*)(VkCommandBuffer commandBuffer, VkBool32 rasterizerDiscardEnable);
using PFN_vkCmdSetDepthBiasEnable = void (*)(VkCommandBuffer commandBuffer, VkBool32 depthBiasEnable);
using PFN_vkCmdSetPrimitiveRestartEnable = void (*)(VkCommandBuffer commandBuffer, VkBool32 primitiveRestartEnable);
using PFN_vkGetDeviceBufferMemoryRequirements
    = void (*)(VkDevice device, const VkDeviceBufferMemoryRequirements *pInfo, VkMemoryRequirements2 *pMemoryRequirements);
using PFN_vkGetDeviceImageMemoryRequirements
    = void (*)(VkDevice device, const VkDeviceImageMemoryRequirements *pInfo, VkMemoryRequirements2 *pMemoryRequirements);
using PFN_vkGetDeviceImageSparseMemoryRequirements
    = void (*)(VkDevice device, const VkDeviceImageMemoryRequirements *pInfo, u32 *pSparseMemoryRequirementCount,
               VkSparseImageMemoryRequirements2 *pSparseMemoryRequirements);
using PFN_vkDestroySurfaceKHR = void (*)(VkInstance instance, VkSurfaceKHR surface, const VkAllocationCallbacks *pAllocator);
using PFN_vkGetPhysicalDeviceSurfaceSupportKHR
    = VkResult (*)(VkPhysicalDevice physicalDevice, u32 queueFamilyIndex, VkSurfaceKHR surface, VkBool32 *pSupported);
using PFN_vkGetPhysicalDeviceSurfaceCapabilitiesKHR
    = VkResult (*)(VkPhysicalDevice physicalDevice, VkSurfaceKHR surface, VkSurfaceCapabilitiesKHR *pSurfaceCapabilities);
using PFN_vkGetPhysicalDeviceSurfaceFormatsKHR
    = VkResult (*)(VkPhysicalDevice physicalDevice, VkSurfaceKHR surface, u32 *pSurfaceFormatCount, VkSurfaceFormatKHR *pSurfaceFormats);
using PFN_vkGetPhysicalDeviceSurfacePresentModesKHR
    = VkResult (*)(VkPhysicalDevice physicalDevice, VkSurfaceKHR surface, u32 *pPresentModeCount, VkPresentModeKHR *pPresentModes);
using PFN_vkCreateSwapchainKHR = VkResult (*)(VkDevice device, const VkSwapchainCreateInfoKHR *pCreateInfo,
                                              const VkAllocationCallbacks *pAllocator, VkSwapchainKHR *pSwapchain);
using PFN_vkDestroySwapchainKHR = void (*)(VkDevice device, VkSwapchainKHR swapchain, const VkAllocationCallbacks *pAllocator);
using PFN_vkGetSwapchainImagesKHR
    = VkResult (*)(VkDevice device, VkSwapchainKHR swapchain, u32 *pSwapchainImageCount, VkImage *pSwapchainImages);
using PFN_vkAcquireNextImageKHR
    = VkResult (*)(VkDevice device, VkSwapchainKHR swapchain, u64 timeout, VkSemaphore semaphore, VkFence fence, u32 *pImageIndex);
using PFN_vkQueuePresentKHR = VkResult (*)(VkQueue queue, const VkPresentInfoKHR *pPresentInfo);
using PFN_vkGetDeviceGroupPresentCapabilitiesKHR
    = VkResult (*)(VkDevice device, VkDeviceGroupPresentCapabilitiesKHR *pDeviceGroupPresentCapabilities);
using PFN_vkGetDeviceGroupSurfacePresentModesKHR
    = VkResult (*)(VkDevice device, VkSurfaceKHR surface, VkDeviceGroupPresentModeFlagsKHR *pModes);
using PFN_vkGetPhysicalDevicePresentRectanglesKHR
    = VkResult (*)(VkPhysicalDevice physicalDevice, VkSurfaceKHR surface, u32 *pRectCount, VkRect2D *pRects);
using PFN_vkAcquireNextImage2KHR = VkResult (*)(VkDevice device, const VkAcquireNextImageInfoKHR *pAcquireInfo, u32 *pImageIndex);
using PFN_vkCreateXlibSurfaceKHR = VkResult (*)(VkInstance instance, const VkXlibSurfaceCreateInfoKHR *pCreateInfo,
                                                const VkAllocationCallbacks *pAllocator, VkSurfaceKHR *pSurface);
using PFN_vkGetPhysicalDeviceXlibPresentationSupportKHR
    = VkBool32 (*)(VkPhysicalDevice physicalDevice, u32 queueFamilyIndex, ::micron::gfx::platform::XDisplay *dpy,
                   ::micron::gfx::platform::XVisualID visualID);
using PFN_vkCreateWaylandSurfaceKHR = VkResult (*)(VkInstance instance, const VkWaylandSurfaceCreateInfoKHR *pCreateInfo,
                                                   const VkAllocationCallbacks *pAllocator, VkSurfaceKHR *pSurface);
using PFN_vkGetPhysicalDeviceWaylandPresentationSupportKHR
    = VkBool32 (*)(VkPhysicalDevice physicalDevice, u32 queueFamilyIndex, struct ::micron::gfx::platform::wl_display *display);
using PFN_vkSetDebugUtilsObjectNameEXT = VkResult (*)(VkDevice device, const VkDebugUtilsObjectNameInfoEXT *pNameInfo);
using PFN_vkSetDebugUtilsObjectTagEXT = VkResult (*)(VkDevice device, const VkDebugUtilsObjectTagInfoEXT *pTagInfo);
using PFN_vkQueueBeginDebugUtilsLabelEXT = void (*)(VkQueue queue, const VkDebugUtilsLabelEXT *pLabelInfo);
using PFN_vkQueueEndDebugUtilsLabelEXT = void (*)(VkQueue queue);
using PFN_vkQueueInsertDebugUtilsLabelEXT = void (*)(VkQueue queue, const VkDebugUtilsLabelEXT *pLabelInfo);
using PFN_vkCmdBeginDebugUtilsLabelEXT = void (*)(VkCommandBuffer commandBuffer, const VkDebugUtilsLabelEXT *pLabelInfo);
using PFN_vkCmdEndDebugUtilsLabelEXT = void (*)(VkCommandBuffer commandBuffer);
using PFN_vkCmdInsertDebugUtilsLabelEXT = void (*)(VkCommandBuffer commandBuffer, const VkDebugUtilsLabelEXT *pLabelInfo);
using PFN_vkCreateDebugUtilsMessengerEXT = VkResult (*)(VkInstance instance, const VkDebugUtilsMessengerCreateInfoEXT *pCreateInfo,
                                                        const VkAllocationCallbacks *pAllocator, VkDebugUtilsMessengerEXT *pMessenger);
using PFN_vkDestroyDebugUtilsMessengerEXT
    = void (*)(VkInstance instance, VkDebugUtilsMessengerEXT messenger, const VkAllocationCallbacks *pAllocator);
using PFN_vkSubmitDebugUtilsMessageEXT
    = void (*)(VkInstance instance, VkDebugUtilsMessageSeverityFlagBitsEXT messageSeverity, VkDebugUtilsMessageTypeFlagsEXT messageTypes,
               const VkDebugUtilsMessengerCallbackDataEXT *pCallbackData);
using PFN_vkCmdSetEvent2KHR = void (*)(VkCommandBuffer commandBuffer, VkEvent event, const VkDependencyInfo *pDependencyInfo);
using PFN_vkCmdResetEvent2KHR = void (*)(VkCommandBuffer commandBuffer, VkEvent event, VkPipelineStageFlags2 stageMask);
using PFN_vkCmdWaitEvents2KHR
    = void (*)(VkCommandBuffer commandBuffer, u32 eventCount, const VkEvent *pEvents, const VkDependencyInfo *pDependencyInfos);
using PFN_vkCmdPipelineBarrier2KHR = void (*)(VkCommandBuffer commandBuffer, const VkDependencyInfo *pDependencyInfo);
using PFN_vkCmdWriteTimestamp2KHR = void (*)(VkCommandBuffer commandBuffer, VkPipelineStageFlags2 stage, VkQueryPool queryPool, u32 query);
using PFN_vkQueueSubmit2KHR = VkResult (*)(VkQueue queue, u32 submitCount, const VkSubmitInfo2 *pSubmits, VkFence fence);
using PFN_vkCmdWriteBufferMarker2AMD
    = void (*)(VkCommandBuffer commandBuffer, VkPipelineStageFlags2 stage, VkBuffer dstBuffer, VkDeviceSize dstOffset, u32 marker);
using PFN_vkGetQueueCheckpointData2NV = void (*)(VkQueue queue, u32 *pCheckpointDataCount, VkCheckpointData2NV *pCheckpointData);

};      // namespace vk
};      // namespace gfx
};      // namespace micron
