//  Copyright (c) 2024- David Lucius Severus
//
//  Distributed under the Boost Software License, Version 1.0.
//  See accompanying file LICENSE_1_0.txt or copy at
//  http://www.boost.org/LICENSE_1_0.txt
//
//  *** AUTOGENERATED FILE; do not hand-edit; regenerate via:
//        python3 tools/vk_xml_gen/gen_vk.py ***

#pragma once

#include "../vulkan.hpp"

namespace micron
{
namespace gfx
{
namespace vk
{

struct instance_deleter {
  const VkAllocationCallbacks *alloc = nullptr;

  void
  operator()(VkInstance h) const noexcept
  {
    if ( h && vkDestroyInstance ) vkDestroyInstance(h, alloc);
  }
};

struct device_deleter {
  const VkAllocationCallbacks *alloc = nullptr;

  void
  operator()(VkDevice h) const noexcept
  {
    if ( h && vkDestroyDevice ) vkDestroyDevice(h, alloc);
  }
};

struct device_memory_deleter {
  VkDevice parent = nullptr;
  const VkAllocationCallbacks *alloc = nullptr;

  void
  operator()(VkDeviceMemory h) const noexcept
  {
    if ( h && parent && vkFreeMemory ) vkFreeMemory(parent, h, alloc);
  }
};

struct fence_deleter {
  VkDevice parent = nullptr;
  const VkAllocationCallbacks *alloc = nullptr;

  void
  operator()(VkFence h) const noexcept
  {
    if ( h && parent && vkDestroyFence ) vkDestroyFence(parent, h, alloc);
  }
};

struct semaphore_deleter {
  VkDevice parent = nullptr;
  const VkAllocationCallbacks *alloc = nullptr;

  void
  operator()(VkSemaphore h) const noexcept
  {
    if ( h && parent && vkDestroySemaphore ) vkDestroySemaphore(parent, h, alloc);
  }
};

struct event_deleter {
  VkDevice parent = nullptr;
  const VkAllocationCallbacks *alloc = nullptr;

  void
  operator()(VkEvent h) const noexcept
  {
    if ( h && parent && vkDestroyEvent ) vkDestroyEvent(parent, h, alloc);
  }
};

struct query_pool_deleter {
  VkDevice parent = nullptr;
  const VkAllocationCallbacks *alloc = nullptr;

  void
  operator()(VkQueryPool h) const noexcept
  {
    if ( h && parent && vkDestroyQueryPool ) vkDestroyQueryPool(parent, h, alloc);
  }
};

struct buffer_deleter {
  VkDevice parent = nullptr;
  const VkAllocationCallbacks *alloc = nullptr;

  void
  operator()(VkBuffer h) const noexcept
  {
    if ( h && parent && vkDestroyBuffer ) vkDestroyBuffer(parent, h, alloc);
  }
};

struct buffer_view_deleter {
  VkDevice parent = nullptr;
  const VkAllocationCallbacks *alloc = nullptr;

  void
  operator()(VkBufferView h) const noexcept
  {
    if ( h && parent && vkDestroyBufferView ) vkDestroyBufferView(parent, h, alloc);
  }
};

struct image_deleter {
  VkDevice parent = nullptr;
  const VkAllocationCallbacks *alloc = nullptr;

  void
  operator()(VkImage h) const noexcept
  {
    if ( h && parent && vkDestroyImage ) vkDestroyImage(parent, h, alloc);
  }
};

struct image_view_deleter {
  VkDevice parent = nullptr;
  const VkAllocationCallbacks *alloc = nullptr;

  void
  operator()(VkImageView h) const noexcept
  {
    if ( h && parent && vkDestroyImageView ) vkDestroyImageView(parent, h, alloc);
  }
};

struct shader_module_deleter {
  VkDevice parent = nullptr;
  const VkAllocationCallbacks *alloc = nullptr;

  void
  operator()(VkShaderModule h) const noexcept
  {
    if ( h && parent && vkDestroyShaderModule ) vkDestroyShaderModule(parent, h, alloc);
  }
};

struct pipeline_cache_deleter {
  VkDevice parent = nullptr;
  const VkAllocationCallbacks *alloc = nullptr;

  void
  operator()(VkPipelineCache h) const noexcept
  {
    if ( h && parent && vkDestroyPipelineCache ) vkDestroyPipelineCache(parent, h, alloc);
  }
};

struct pipeline_deleter {
  VkDevice parent = nullptr;
  const VkAllocationCallbacks *alloc = nullptr;

  void
  operator()(VkPipeline h) const noexcept
  {
    if ( h && parent && vkDestroyPipeline ) vkDestroyPipeline(parent, h, alloc);
  }
};

struct pipeline_layout_deleter {
  VkDevice parent = nullptr;
  const VkAllocationCallbacks *alloc = nullptr;

  void
  operator()(VkPipelineLayout h) const noexcept
  {
    if ( h && parent && vkDestroyPipelineLayout ) vkDestroyPipelineLayout(parent, h, alloc);
  }
};

struct sampler_deleter {
  VkDevice parent = nullptr;
  const VkAllocationCallbacks *alloc = nullptr;

  void
  operator()(VkSampler h) const noexcept
  {
    if ( h && parent && vkDestroySampler ) vkDestroySampler(parent, h, alloc);
  }
};

struct descriptor_set_layout_deleter {
  VkDevice parent = nullptr;
  const VkAllocationCallbacks *alloc = nullptr;

  void
  operator()(VkDescriptorSetLayout h) const noexcept
  {
    if ( h && parent && vkDestroyDescriptorSetLayout ) vkDestroyDescriptorSetLayout(parent, h, alloc);
  }
};

struct descriptor_pool_deleter {
  VkDevice parent = nullptr;
  const VkAllocationCallbacks *alloc = nullptr;

  void
  operator()(VkDescriptorPool h) const noexcept
  {
    if ( h && parent && vkDestroyDescriptorPool ) vkDestroyDescriptorPool(parent, h, alloc);
  }
};

struct descriptor_set_deleter {
  VkDevice parent = nullptr;
  VkDescriptorPool pool = nullptr;

  void
  operator()(VkDescriptorSet h) const noexcept
  {
    if ( h && parent && pool && vkFreeDescriptorSets ) vkFreeDescriptorSets(parent, pool, 1, &h);
  }
};

struct framebuffer_deleter {
  VkDevice parent = nullptr;
  const VkAllocationCallbacks *alloc = nullptr;

  void
  operator()(VkFramebuffer h) const noexcept
  {
    if ( h && parent && vkDestroyFramebuffer ) vkDestroyFramebuffer(parent, h, alloc);
  }
};

struct render_pass_deleter {
  VkDevice parent = nullptr;
  const VkAllocationCallbacks *alloc = nullptr;

  void
  operator()(VkRenderPass h) const noexcept
  {
    if ( h && parent && vkDestroyRenderPass ) vkDestroyRenderPass(parent, h, alloc);
  }
};

struct command_pool_deleter {
  VkDevice parent = nullptr;
  const VkAllocationCallbacks *alloc = nullptr;

  void
  operator()(VkCommandPool h) const noexcept
  {
    if ( h && parent && vkDestroyCommandPool ) vkDestroyCommandPool(parent, h, alloc);
  }
};

struct command_buffer_deleter {
  VkDevice parent = nullptr;
  VkCommandPool pool = nullptr;

  void
  operator()(VkCommandBuffer h) const noexcept
  {
    if ( h && parent && pool && vkFreeCommandBuffers ) vkFreeCommandBuffers(parent, pool, 1, &h);
  }
};

struct sampler_ycbcr_conversion_deleter {
  VkDevice parent = nullptr;
  const VkAllocationCallbacks *alloc = nullptr;

  void
  operator()(VkSamplerYcbcrConversion h) const noexcept
  {
    if ( h && parent && vkDestroySamplerYcbcrConversion ) vkDestroySamplerYcbcrConversion(parent, h, alloc);
  }
};

struct descriptor_update_template_deleter {
  VkDevice parent = nullptr;
  const VkAllocationCallbacks *alloc = nullptr;

  void
  operator()(VkDescriptorUpdateTemplate h) const noexcept
  {
    if ( h && parent && vkDestroyDescriptorUpdateTemplate ) vkDestroyDescriptorUpdateTemplate(parent, h, alloc);
  }
};

struct private_data_slot_deleter {
  VkDevice parent = nullptr;
  const VkAllocationCallbacks *alloc = nullptr;

  void
  operator()(VkPrivateDataSlot h) const noexcept
  {
    if ( h && parent && vkDestroyPrivateDataSlot ) vkDestroyPrivateDataSlot(parent, h, alloc);
  }
};

struct surface_k_h_r_deleter {
  VkInstance parent = nullptr;
  const VkAllocationCallbacks *alloc = nullptr;

  void
  operator()(VkSurfaceKHR h) const noexcept
  {
    if ( h && parent && vkDestroySurfaceKHR ) vkDestroySurfaceKHR(parent, h, alloc);
  }
};

struct swapchain_k_h_r_deleter {
  VkDevice parent = nullptr;
  const VkAllocationCallbacks *alloc = nullptr;

  void
  operator()(VkSwapchainKHR h) const noexcept
  {
    if ( h && parent && vkDestroySwapchainKHR ) vkDestroySwapchainKHR(parent, h, alloc);
  }
};

struct debug_utils_messenger_e_x_t_deleter {
  VkInstance parent = nullptr;
  const VkAllocationCallbacks *alloc = nullptr;

  void
  operator()(VkDebugUtilsMessengerEXT h) const noexcept
  {
    if ( h && parent && vkDestroyDebugUtilsMessengerEXT ) vkDestroyDebugUtilsMessengerEXT(parent, h, alloc);
  }
};

};      // namespace vk
};      // namespace gfx
};      // namespace micron
