//  Copyright (c) 2024- David Lucius Severus
//
//  Distributed under the Boost Software License, Version 1.0.
//  See accompanying file LICENSE_1_0.txt or copy at
//  http://www.boost.org/LICENSE_1_0.txt
//
//  not autogenerated, yet

#pragma once

#include "__vk_types.hpp"

#ifndef VKAPI_PTR
#define VKAPI_PTR
#endif
#ifndef VKAPI_ATTR
#define VKAPI_ATTR
#endif
#ifndef VKAPI_CALL
#define VKAPI_CALL
#endif

namespace micron
{
namespace gfx
{
namespace vk
{

#ifndef VK_NULL_HANDLE
#define VK_NULL_HANDLE 0
#endif

inline constexpr u32 VK_API_VERSION_1_0 = (1u << 22);
inline constexpr u32 VK_API_VERSION_1_1 = (1u << 22) | (1u << 12);
inline constexpr u32 VK_API_VERSION_1_2 = (1u << 22) | (2u << 12);
inline constexpr u32 VK_API_VERSION_1_3 = (1u << 22) | (3u << 12);

inline constexpr const char *VK_LAYER_KHRONOS_VALIDATION_NAME = "VK_LAYER_KHRONOS_validation";

}      // namespace vk
}      // namespace gfx
}      // namespace micron
