//  Copyright (c) 2024- David Lucius Severus
//
//  Distributed under the Boost Software License, Version 1.0.
//  See accompanying file LICENSE_1_0.txt or copy at
//  http://www.boost.org/LICENSE_1_0.txt
#pragma once

#include "../../../atomic/atomic.hpp"
#include "../../../memory/allocation/abcmalloc/malloc.hpp"
#include "../../../memory/cmemory.hpp"
#include "../../../types.hpp"

#include "__vk_types.hpp"

//  not autogenerated. this lives under __bits/ so that __vk_deleters.hpp can include it rather than forward declare it

namespace micron
{
namespace gfx
{
namespace vk
{

// WARNING: Vulkan drivers support two memory types device memory and cpu/host memory
// cpu side allocations route through VkAllocationCallbacks passed to every vkCreate*
// if null, the driver picks the base internal allocator, otherwise will use the provided one

namespace __vk_host
{

// COMMAND OBJECT CACHE DEVICE INSTANCE
inline constexpr u32 __scope_count = 5;

// %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
// block header
//   user - 8    offset_to_raw   what abc::dealloc has to be given
//   user - 16   size            reqd size; abc::query_size only knows the granted one
//   user - 24   scope
//   user - 32   magic           flags a free of memory this allocator never handed out

inline constexpr usize __off_raw = 8;
inline constexpr usize __off_size = 16;
inline constexpr usize __off_scope = 24;
inline constexpr usize __off_magic = 32;
inline constexpr usize __header_size = 32;

inline constexpr usize __min_align = 16;

inline constexpr usize __magic = static_cast<usize>(0x564b484cul);      // 'VKHL'

// __alloc rounds with ~(align_eff - 1), and align_eff is floored by __min_align
static_assert(__min_align != 0 and (__min_align & (__min_align - 1)) == 0, "__min_align feeds an alignment mask; power of two only");
static_assert(__header_size >= __off_magic, "every header field must fit below the user pointer");
static_assert(__off_magic >= __off_scope + sizeof(usize) and __off_scope >= __off_size + sizeof(usize)
                  and __off_size >= __off_raw + sizeof(usize) and __off_raw >= sizeof(usize),
              "header fields overlap");
static_assert(__magic != 0, "the magic must survive truncation to a 32-bit usize");

#if defined(MICRON_VK_HOST_STATS)
struct __host_stats {
  micron::atomic_token<u64> live_blocks{ 0 };
  micron::atomic_token<u64> live_bytes{ 0 };
  micron::atomic_token<u64> peak_bytes{ 0 };
  micron::atomic_token<u64> allocs{ 0 };
  micron::atomic_token<u64> frees{ 0 };
  micron::atomic_token<u64> reallocs{ 0 };
  micron::atomic_token<u64> foreign_frees{ 0 };      // magic mismatch: not ours, or already freed
  micron::atomic_token<u64> scope_blocks[__scope_count]{};
  micron::atomic_token<u64> scope_bytes[__scope_count]{};
  micron::atomic_token<u64> internal_allocs{ 0 };
  micron::atomic_token<u64> internal_alloc_bytes{ 0 };
  micron::atomic_token<u64> internal_frees{ 0 };
  micron::atomic_token<u64> internal_free_bytes{ 0 };
};

inline constinit __host_stats __stat{};
#endif

inline void
__stat_on_alloc([[maybe_unused]] usize size, [[maybe_unused]] VkSystemAllocationScope scope) noexcept
{
#if defined(MICRON_VK_HOST_STATS)
  __stat.allocs.fetch_add(1, micron::memory_order_relaxed);
  __stat.live_blocks.fetch_add(1, micron::memory_order_relaxed);
  const u64 now = __stat.live_bytes.add_fetch(static_cast<u64>(size), micron::memory_order_relaxed);

  u64 peak = __stat.peak_bytes.get(micron::memory_order_relaxed);
  while ( now > peak and !__stat.peak_bytes.compare_exchange_weak(peak, now, micron::memory_order_relaxed, micron::memory_order_relaxed) );

  const u32 i = static_cast<u32>(static_cast<i32>(scope));
  if ( i < __scope_count ) [[likely]] {
    __stat.scope_blocks[i].fetch_add(1, micron::memory_order_relaxed);
    __stat.scope_bytes[i].fetch_add(static_cast<u64>(size), micron::memory_order_relaxed);
  }
#endif
}

// reads the header, so it must run before the block goes back to abc
inline void
__stat_on_free([[maybe_unused]] byte *user) noexcept
{
#if defined(MICRON_VK_HOST_STATS)
  if ( *reinterpret_cast<usize *>(user - __off_magic) != __magic ) [[unlikely]] {
    __stat.foreign_frees.fetch_add(1, micron::memory_order_relaxed);
    return;
  }
  const u64 size = static_cast<u64>(*reinterpret_cast<usize *>(user - __off_size));
  const u32 i = static_cast<u32>(*reinterpret_cast<usize *>(user - __off_scope));
  *reinterpret_cast<usize *>(user - __off_magic) = 0;

  __stat.frees.fetch_add(1, micron::memory_order_relaxed);
  __stat.live_blocks.fetch_sub(1, micron::memory_order_relaxed);
  __stat.live_bytes.fetch_sub(size, micron::memory_order_relaxed);
  if ( i < __scope_count ) [[likely]] {
    __stat.scope_blocks[i].fetch_sub(1, micron::memory_order_relaxed);
    __stat.scope_bytes[i].fetch_sub(size, micron::memory_order_relaxed);
  }
#endif
}

inline void *
__alloc(usize size, usize align, VkSystemAllocationScope scope) noexcept
{
  if ( size == 0 ) return nullptr;
  // the mask below is only a rounding op for a power of two, and Vulkan promises one
  if ( align == 0 or (align & (align - 1)) != 0 ) [[unlikely]]
    return nullptr;

  const usize align_eff = align > __min_align ? align : __min_align;
  usize total;
  if ( abc::check_add_overflow(size, align_eff + __header_size, total) ) [[unlikely]]
    return nullptr;

  byte *raw = abc::alloc(total);
  if ( !raw ) return nullptr;
  const uintptr_t raw_addr = reinterpret_cast<uintptr_t>(raw);
  const uintptr_t user_addr = (raw_addr + __header_size + align_eff - 1) & ~(static_cast<uintptr_t>(align_eff) - 1);
  byte *user = reinterpret_cast<byte *>(user_addr);

  *reinterpret_cast<usize *>(user - __off_raw) = user_addr - raw_addr;
  *reinterpret_cast<usize *>(user - __off_size) = size;
  *reinterpret_cast<usize *>(user - __off_scope) = static_cast<usize>(static_cast<u32>(static_cast<i32>(scope)));
  *reinterpret_cast<usize *>(user - __off_magic) = __magic;

  __stat_on_alloc(size, scope);
  return user;
}

inline void
__free(void *user_ptr) noexcept
{
  if ( !user_ptr ) return;
  byte *user = reinterpret_cast<byte *>(user_ptr);
  __stat_on_free(user);
  const usize offset_to_raw = *reinterpret_cast<usize *>(user - __off_raw);
  abc::dealloc(user - offset_to_raw);
}

inline usize
__size_of(void *user_ptr) noexcept
{
  return *reinterpret_cast<usize *>(reinterpret_cast<byte *>(user_ptr) - __off_size);
}

inline VkSystemAllocationScope
__scope_of(void *user_ptr) noexcept
{
  return static_cast<VkSystemAllocationScope>(
      static_cast<i32>(*reinterpret_cast<usize *>(reinterpret_cast<byte *>(user_ptr) - __off_scope)));
}

inline void *
__realloc(void *original, usize size, usize align, VkSystemAllocationScope scope) noexcept
{
  if ( !original ) return __alloc(size, align, scope);
  if ( size == 0 ) {
    __free(original);
    return nullptr;
  }
  const usize old_size = __size_of(original);
  void *fresh = __alloc(size, align, scope);
  if ( !fresh ) return nullptr;
  const usize copy = old_size < size ? old_size : size;
  micron::memcpy(reinterpret_cast<byte *>(fresh), reinterpret_cast<byte *>(original), copy);
  __free(original);
#if defined(MICRON_VK_HOST_STATS)
  __stat.reallocs.fetch_add(1, micron::memory_order_relaxed);
#endif
  return fresh;
}

// PFN_* signatures emitted in __vk_protos.hpp have VKAPI_PTR stripped
inline void *
__pfn_alloc(void * /*user*/, usize size, usize align, VkSystemAllocationScope scope) noexcept
{
  return __alloc(size, align, scope);
}

inline void *
__pfn_realloc(void * /*user*/, void *original, usize size, usize align, VkSystemAllocationScope scope) noexcept
{
  return __realloc(original, size, align, scope);
}

inline void
__pfn_free(void * /*user*/, void *p) noexcept
{
  __free(p);
}

// the driver telling us it went around us and used its own malloc
inline void
__pfn_internal_alloc_notify(void * /*user*/, [[maybe_unused]] usize size, VkInternalAllocationType /*type*/,
                            VkSystemAllocationScope /*scope*/) noexcept
{
#if defined(MICRON_VK_HOST_STATS)
  __stat.internal_allocs.fetch_add(1, micron::memory_order_relaxed);
  __stat.internal_alloc_bytes.fetch_add(static_cast<u64>(size), micron::memory_order_relaxed);
#endif
}

inline void
__pfn_internal_free_notify(void * /*user*/, [[maybe_unused]] usize size, VkInternalAllocationType /*type*/,
                           VkSystemAllocationScope /*scope*/) noexcept
{
#if defined(MICRON_VK_HOST_STATS)
  __stat.internal_frees.fetch_add(1, micron::memory_order_relaxed);
  __stat.internal_free_bytes.fetch_add(static_cast<u64>(size), micron::memory_order_relaxed);
#endif
}

};      // namespace __vk_host

// %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
// host allocation accounting
// --def MICRON_VK_HOST_STATS (default off, zero cost when off)

struct host_alloc_stats_t {
  bool enabled = false;      // false => the counters were compiled out; the zeroes mean nothing
  u64 live_blocks = 0;
  u64 live_bytes = 0;
  u64 peak_bytes = 0;
  u64 allocs = 0;
  u64 frees = 0;
  u64 reallocs = 0;
  u64 foreign_frees = 0;
  u64 scope_blocks[__vk_host::__scope_count] = {};
  u64 scope_bytes[__vk_host::__scope_count] = {};
  u64 internal_allocs = 0;
  u64 internal_alloc_bytes = 0;
  u64 internal_frees = 0;
  u64 internal_free_bytes = 0;
};

[[nodiscard]] inline host_alloc_stats_t
host_alloc_stats() noexcept
{
  host_alloc_stats_t o{};
#if defined(MICRON_VK_HOST_STATS)
  o.enabled = true;
  o.live_blocks = __vk_host::__stat.live_blocks.get(micron::memory_order_relaxed);
  o.live_bytes = __vk_host::__stat.live_bytes.get(micron::memory_order_relaxed);
  o.peak_bytes = __vk_host::__stat.peak_bytes.get(micron::memory_order_relaxed);
  o.allocs = __vk_host::__stat.allocs.get(micron::memory_order_relaxed);
  o.frees = __vk_host::__stat.frees.get(micron::memory_order_relaxed);
  o.reallocs = __vk_host::__stat.reallocs.get(micron::memory_order_relaxed);
  o.foreign_frees = __vk_host::__stat.foreign_frees.get(micron::memory_order_relaxed);
  for ( u32 i = 0; i < __vk_host::__scope_count; ++i ) {
    o.scope_blocks[i] = __vk_host::__stat.scope_blocks[i].get(micron::memory_order_relaxed);
    o.scope_bytes[i] = __vk_host::__stat.scope_bytes[i].get(micron::memory_order_relaxed);
  }
  o.internal_allocs = __vk_host::__stat.internal_allocs.get(micron::memory_order_relaxed);
  o.internal_alloc_bytes = __vk_host::__stat.internal_alloc_bytes.get(micron::memory_order_relaxed);
  o.internal_frees = __vk_host::__stat.internal_frees.get(micron::memory_order_relaxed);
  o.internal_free_bytes = __vk_host::__stat.internal_free_bytes.get(micron::memory_order_relaxed);
#endif
  return o;
}

// only legal with no live blocks
inline void
host_alloc_stats_reset() noexcept
{
#if defined(MICRON_VK_HOST_STATS)
  __vk_host::__stat.live_blocks.store(0, micron::memory_order_relaxed);
  __vk_host::__stat.live_bytes.store(0, micron::memory_order_relaxed);
  __vk_host::__stat.peak_bytes.store(0, micron::memory_order_relaxed);
  __vk_host::__stat.allocs.store(0, micron::memory_order_relaxed);
  __vk_host::__stat.frees.store(0, micron::memory_order_relaxed);
  __vk_host::__stat.reallocs.store(0, micron::memory_order_relaxed);
  __vk_host::__stat.foreign_frees.store(0, micron::memory_order_relaxed);
  for ( u32 i = 0; i < __vk_host::__scope_count; ++i ) {
    __vk_host::__stat.scope_blocks[i].store(0, micron::memory_order_relaxed);
    __vk_host::__stat.scope_bytes[i].store(0, micron::memory_order_relaxed);
  }
  __vk_host::__stat.internal_allocs.store(0, micron::memory_order_relaxed);
  __vk_host::__stat.internal_alloc_bytes.store(0, micron::memory_order_relaxed);
  __vk_host::__stat.internal_frees.store(0, micron::memory_order_relaxed);
  __vk_host::__stat.internal_free_bytes.store(0, micron::memory_order_relaxed);
#endif
}

inline const VkAllocationCallbacks *
host_allocation_callbacks() noexcept
{
  static const VkAllocationCallbacks cb = {
    .pUserData = nullptr,
    .pfnAllocation = __vk_host::__pfn_alloc,
    .pfnReallocation = __vk_host::__pfn_realloc,
    .pfnFree = __vk_host::__pfn_free,
    .pfnInternalAllocation = __vk_host::__pfn_internal_alloc_notify,
    .pfnInternalFree = __vk_host::__pfn_internal_free_notify,
  };
  return &cb;
}

};      // namespace vk
};      // namespace gfx
};      // namespace micron
