//  Copyright (c) 2024- David Lucius Severus
//
//  Distributed under the Boost Software License, Version 1.0.
//  See accompanying file LICENSE_1_0.txt or copy at
//  http://www.boost.org/LICENSE_1_0.txt
//
//  *** AUTOGENERATED FILE; do not hand-edit; regenerate via:
//        python3 tools/vk_xml_gen/gen_vk.py ***

#pragma once

#include "__bits/__vk_enums.hpp"
#include "__bits/__vk_protos.hpp"
#include "__bits/__vk_table.hpp"
#include "__bits/__vk_types.hpp"

#include "__bits/__vk_core_supplement.hpp"

// main Vulkan fns

namespace micron { namespace gfx { namespace vk {

inline PFN_vkCreateInstance vkCreateInstance = nullptr;
inline PFN_vkDestroyInstance vkDestroyInstance = nullptr;
inline PFN_vkEnumeratePhysicalDevices vkEnumeratePhysicalDevices = nullptr;
inline PFN_vkGetPhysicalDeviceFeatures vkGetPhysicalDeviceFeatures = nullptr;
inline PFN_vkGetPhysicalDeviceFormatProperties vkGetPhysicalDeviceFormatProperties = nullptr;
inline PFN_vkGetPhysicalDeviceImageFormatProperties vkGetPhysicalDeviceImageFormatProperties = nullptr;
inline PFN_vkGetPhysicalDeviceProperties vkGetPhysicalDeviceProperties = nullptr;
inline PFN_vkGetPhysicalDeviceQueueFamilyProperties vkGetPhysicalDeviceQueueFamilyProperties = nullptr;
inline PFN_vkGetPhysicalDeviceMemoryProperties vkGetPhysicalDeviceMemoryProperties = nullptr;
inline PFN_vkGetInstanceProcAddr vkGetInstanceProcAddr = nullptr;
inline PFN_vkGetDeviceProcAddr vkGetDeviceProcAddr = nullptr;
inline PFN_vkCreateDevice vkCreateDevice = nullptr;
inline PFN_vkDestroyDevice vkDestroyDevice = nullptr;
inline PFN_vkEnumerateInstanceExtensionProperties vkEnumerateInstanceExtensionProperties = nullptr;
inline PFN_vkEnumerateDeviceExtensionProperties vkEnumerateDeviceExtensionProperties = nullptr;
inline PFN_vkEnumerateInstanceLayerProperties vkEnumerateInstanceLayerProperties = nullptr;
inline PFN_vkEnumerateDeviceLayerProperties vkEnumerateDeviceLayerProperties = nullptr;
inline PFN_vkGetDeviceQueue vkGetDeviceQueue = nullptr;
inline PFN_vkQueueSubmit vkQueueSubmit = nullptr;
inline PFN_vkQueueWaitIdle vkQueueWaitIdle = nullptr;
inline PFN_vkDeviceWaitIdle vkDeviceWaitIdle = nullptr;
inline PFN_vkAllocateMemory vkAllocateMemory = nullptr;
inline PFN_vkFreeMemory vkFreeMemory = nullptr;
inline PFN_vkMapMemory vkMapMemory = nullptr;
inline PFN_vkUnmapMemory vkUnmapMemory = nullptr;
inline PFN_vkFlushMappedMemoryRanges vkFlushMappedMemoryRanges = nullptr;
inline PFN_vkInvalidateMappedMemoryRanges vkInvalidateMappedMemoryRanges = nullptr;
inline PFN_vkGetDeviceMemoryCommitment vkGetDeviceMemoryCommitment = nullptr;
inline PFN_vkBindBufferMemory vkBindBufferMemory = nullptr;
inline PFN_vkBindImageMemory vkBindImageMemory = nullptr;
inline PFN_vkGetBufferMemoryRequirements vkGetBufferMemoryRequirements = nullptr;
inline PFN_vkGetImageMemoryRequirements vkGetImageMemoryRequirements = nullptr;
inline PFN_vkGetImageSparseMemoryRequirements vkGetImageSparseMemoryRequirements = nullptr;
inline PFN_vkGetPhysicalDeviceSparseImageFormatProperties vkGetPhysicalDeviceSparseImageFormatProperties = nullptr;
inline PFN_vkQueueBindSparse vkQueueBindSparse = nullptr;
inline PFN_vkCreateFence vkCreateFence = nullptr;
inline PFN_vkDestroyFence vkDestroyFence = nullptr;
inline PFN_vkResetFences vkResetFences = nullptr;
inline PFN_vkGetFenceStatus vkGetFenceStatus = nullptr;
inline PFN_vkWaitForFences vkWaitForFences = nullptr;
inline PFN_vkCreateSemaphore vkCreateSemaphore = nullptr;
inline PFN_vkDestroySemaphore vkDestroySemaphore = nullptr;
inline PFN_vkCreateEvent vkCreateEvent = nullptr;
inline PFN_vkDestroyEvent vkDestroyEvent = nullptr;
inline PFN_vkGetEventStatus vkGetEventStatus = nullptr;
inline PFN_vkSetEvent vkSetEvent = nullptr;
inline PFN_vkResetEvent vkResetEvent = nullptr;
inline PFN_vkCreateQueryPool vkCreateQueryPool = nullptr;
inline PFN_vkDestroyQueryPool vkDestroyQueryPool = nullptr;
inline PFN_vkGetQueryPoolResults vkGetQueryPoolResults = nullptr;
inline PFN_vkCreateBuffer vkCreateBuffer = nullptr;
inline PFN_vkDestroyBuffer vkDestroyBuffer = nullptr;
inline PFN_vkCreateBufferView vkCreateBufferView = nullptr;
inline PFN_vkDestroyBufferView vkDestroyBufferView = nullptr;
inline PFN_vkCreateImage vkCreateImage = nullptr;
inline PFN_vkDestroyImage vkDestroyImage = nullptr;
inline PFN_vkGetImageSubresourceLayout vkGetImageSubresourceLayout = nullptr;
inline PFN_vkCreateImageView vkCreateImageView = nullptr;
inline PFN_vkDestroyImageView vkDestroyImageView = nullptr;
inline PFN_vkCreateShaderModule vkCreateShaderModule = nullptr;
inline PFN_vkDestroyShaderModule vkDestroyShaderModule = nullptr;
inline PFN_vkCreatePipelineCache vkCreatePipelineCache = nullptr;
inline PFN_vkDestroyPipelineCache vkDestroyPipelineCache = nullptr;
inline PFN_vkGetPipelineCacheData vkGetPipelineCacheData = nullptr;
inline PFN_vkMergePipelineCaches vkMergePipelineCaches = nullptr;
inline PFN_vkCreateGraphicsPipelines vkCreateGraphicsPipelines = nullptr;
inline PFN_vkCreateComputePipelines vkCreateComputePipelines = nullptr;
inline PFN_vkDestroyPipeline vkDestroyPipeline = nullptr;
inline PFN_vkCreatePipelineLayout vkCreatePipelineLayout = nullptr;
inline PFN_vkDestroyPipelineLayout vkDestroyPipelineLayout = nullptr;
inline PFN_vkCreateSampler vkCreateSampler = nullptr;
inline PFN_vkDestroySampler vkDestroySampler = nullptr;
inline PFN_vkCreateDescriptorSetLayout vkCreateDescriptorSetLayout = nullptr;
inline PFN_vkDestroyDescriptorSetLayout vkDestroyDescriptorSetLayout = nullptr;
inline PFN_vkCreateDescriptorPool vkCreateDescriptorPool = nullptr;
inline PFN_vkDestroyDescriptorPool vkDestroyDescriptorPool = nullptr;
inline PFN_vkResetDescriptorPool vkResetDescriptorPool = nullptr;
inline PFN_vkAllocateDescriptorSets vkAllocateDescriptorSets = nullptr;
inline PFN_vkFreeDescriptorSets vkFreeDescriptorSets = nullptr;
inline PFN_vkUpdateDescriptorSets vkUpdateDescriptorSets = nullptr;
inline PFN_vkCreateFramebuffer vkCreateFramebuffer = nullptr;
inline PFN_vkDestroyFramebuffer vkDestroyFramebuffer = nullptr;
inline PFN_vkCreateRenderPass vkCreateRenderPass = nullptr;
inline PFN_vkDestroyRenderPass vkDestroyRenderPass = nullptr;
inline PFN_vkGetRenderAreaGranularity vkGetRenderAreaGranularity = nullptr;
inline PFN_vkCreateCommandPool vkCreateCommandPool = nullptr;
inline PFN_vkDestroyCommandPool vkDestroyCommandPool = nullptr;
inline PFN_vkResetCommandPool vkResetCommandPool = nullptr;
inline PFN_vkAllocateCommandBuffers vkAllocateCommandBuffers = nullptr;
inline PFN_vkFreeCommandBuffers vkFreeCommandBuffers = nullptr;
inline PFN_vkBeginCommandBuffer vkBeginCommandBuffer = nullptr;
inline PFN_vkEndCommandBuffer vkEndCommandBuffer = nullptr;
inline PFN_vkResetCommandBuffer vkResetCommandBuffer = nullptr;
inline PFN_vkCmdBindPipeline vkCmdBindPipeline = nullptr;
inline PFN_vkCmdSetViewport vkCmdSetViewport = nullptr;
inline PFN_vkCmdSetScissor vkCmdSetScissor = nullptr;
inline PFN_vkCmdSetLineWidth vkCmdSetLineWidth = nullptr;
inline PFN_vkCmdSetDepthBias vkCmdSetDepthBias = nullptr;
inline PFN_vkCmdSetBlendConstants vkCmdSetBlendConstants = nullptr;
inline PFN_vkCmdSetDepthBounds vkCmdSetDepthBounds = nullptr;
inline PFN_vkCmdSetStencilCompareMask vkCmdSetStencilCompareMask = nullptr;
inline PFN_vkCmdSetStencilWriteMask vkCmdSetStencilWriteMask = nullptr;
inline PFN_vkCmdSetStencilReference vkCmdSetStencilReference = nullptr;
inline PFN_vkCmdBindDescriptorSets vkCmdBindDescriptorSets = nullptr;
inline PFN_vkCmdBindIndexBuffer vkCmdBindIndexBuffer = nullptr;
inline PFN_vkCmdBindVertexBuffers vkCmdBindVertexBuffers = nullptr;
inline PFN_vkCmdDraw vkCmdDraw = nullptr;
inline PFN_vkCmdDrawIndexed vkCmdDrawIndexed = nullptr;
inline PFN_vkCmdDrawIndirect vkCmdDrawIndirect = nullptr;
inline PFN_vkCmdDrawIndexedIndirect vkCmdDrawIndexedIndirect = nullptr;
inline PFN_vkCmdDispatch vkCmdDispatch = nullptr;
inline PFN_vkCmdDispatchIndirect vkCmdDispatchIndirect = nullptr;
inline PFN_vkCmdCopyBuffer vkCmdCopyBuffer = nullptr;
inline PFN_vkCmdCopyImage vkCmdCopyImage = nullptr;
inline PFN_vkCmdBlitImage vkCmdBlitImage = nullptr;
inline PFN_vkCmdCopyBufferToImage vkCmdCopyBufferToImage = nullptr;
inline PFN_vkCmdCopyImageToBuffer vkCmdCopyImageToBuffer = nullptr;
inline PFN_vkCmdUpdateBuffer vkCmdUpdateBuffer = nullptr;
inline PFN_vkCmdFillBuffer vkCmdFillBuffer = nullptr;
inline PFN_vkCmdClearColorImage vkCmdClearColorImage = nullptr;
inline PFN_vkCmdClearDepthStencilImage vkCmdClearDepthStencilImage = nullptr;
inline PFN_vkCmdClearAttachments vkCmdClearAttachments = nullptr;
inline PFN_vkCmdResolveImage vkCmdResolveImage = nullptr;
inline PFN_vkCmdSetEvent vkCmdSetEvent = nullptr;
inline PFN_vkCmdResetEvent vkCmdResetEvent = nullptr;
inline PFN_vkCmdWaitEvents vkCmdWaitEvents = nullptr;
inline PFN_vkCmdPipelineBarrier vkCmdPipelineBarrier = nullptr;
inline PFN_vkCmdBeginQuery vkCmdBeginQuery = nullptr;
inline PFN_vkCmdEndQuery vkCmdEndQuery = nullptr;
inline PFN_vkCmdResetQueryPool vkCmdResetQueryPool = nullptr;
inline PFN_vkCmdWriteTimestamp vkCmdWriteTimestamp = nullptr;
inline PFN_vkCmdCopyQueryPoolResults vkCmdCopyQueryPoolResults = nullptr;
inline PFN_vkCmdPushConstants vkCmdPushConstants = nullptr;
inline PFN_vkCmdBeginRenderPass vkCmdBeginRenderPass = nullptr;
inline PFN_vkCmdNextSubpass vkCmdNextSubpass = nullptr;
inline PFN_vkCmdEndRenderPass vkCmdEndRenderPass = nullptr;
inline PFN_vkCmdExecuteCommands vkCmdExecuteCommands = nullptr;
inline PFN_vkEnumerateInstanceVersion vkEnumerateInstanceVersion = nullptr;
inline PFN_vkBindBufferMemory2 vkBindBufferMemory2 = nullptr;
inline PFN_vkBindImageMemory2 vkBindImageMemory2 = nullptr;
inline PFN_vkGetDeviceGroupPeerMemoryFeatures vkGetDeviceGroupPeerMemoryFeatures = nullptr;
inline PFN_vkCmdSetDeviceMask vkCmdSetDeviceMask = nullptr;
inline PFN_vkCmdDispatchBase vkCmdDispatchBase = nullptr;
inline PFN_vkEnumeratePhysicalDeviceGroups vkEnumeratePhysicalDeviceGroups = nullptr;
inline PFN_vkGetImageMemoryRequirements2 vkGetImageMemoryRequirements2 = nullptr;
inline PFN_vkGetBufferMemoryRequirements2 vkGetBufferMemoryRequirements2 = nullptr;
inline PFN_vkGetImageSparseMemoryRequirements2 vkGetImageSparseMemoryRequirements2 = nullptr;
inline PFN_vkGetPhysicalDeviceFeatures2 vkGetPhysicalDeviceFeatures2 = nullptr;
inline PFN_vkGetPhysicalDeviceProperties2 vkGetPhysicalDeviceProperties2 = nullptr;
inline PFN_vkGetPhysicalDeviceFormatProperties2 vkGetPhysicalDeviceFormatProperties2 = nullptr;
inline PFN_vkGetPhysicalDeviceImageFormatProperties2 vkGetPhysicalDeviceImageFormatProperties2 = nullptr;
inline PFN_vkGetPhysicalDeviceQueueFamilyProperties2 vkGetPhysicalDeviceQueueFamilyProperties2 = nullptr;
inline PFN_vkGetPhysicalDeviceMemoryProperties2 vkGetPhysicalDeviceMemoryProperties2 = nullptr;
inline PFN_vkGetPhysicalDeviceSparseImageFormatProperties2 vkGetPhysicalDeviceSparseImageFormatProperties2 = nullptr;
inline PFN_vkTrimCommandPool vkTrimCommandPool = nullptr;
inline PFN_vkGetDeviceQueue2 vkGetDeviceQueue2 = nullptr;
inline PFN_vkCreateSamplerYcbcrConversion vkCreateSamplerYcbcrConversion = nullptr;
inline PFN_vkDestroySamplerYcbcrConversion vkDestroySamplerYcbcrConversion = nullptr;
inline PFN_vkCreateDescriptorUpdateTemplate vkCreateDescriptorUpdateTemplate = nullptr;
inline PFN_vkDestroyDescriptorUpdateTemplate vkDestroyDescriptorUpdateTemplate = nullptr;
inline PFN_vkUpdateDescriptorSetWithTemplate vkUpdateDescriptorSetWithTemplate = nullptr;
inline PFN_vkGetPhysicalDeviceExternalBufferProperties vkGetPhysicalDeviceExternalBufferProperties = nullptr;
inline PFN_vkGetPhysicalDeviceExternalFenceProperties vkGetPhysicalDeviceExternalFenceProperties = nullptr;
inline PFN_vkGetPhysicalDeviceExternalSemaphoreProperties vkGetPhysicalDeviceExternalSemaphoreProperties = nullptr;
inline PFN_vkGetDescriptorSetLayoutSupport vkGetDescriptorSetLayoutSupport = nullptr;
inline PFN_vkCmdDrawIndirectCount vkCmdDrawIndirectCount = nullptr;
inline PFN_vkCmdDrawIndexedIndirectCount vkCmdDrawIndexedIndirectCount = nullptr;
inline PFN_vkCreateRenderPass2 vkCreateRenderPass2 = nullptr;
inline PFN_vkCmdBeginRenderPass2 vkCmdBeginRenderPass2 = nullptr;
inline PFN_vkCmdNextSubpass2 vkCmdNextSubpass2 = nullptr;
inline PFN_vkCmdEndRenderPass2 vkCmdEndRenderPass2 = nullptr;
inline PFN_vkResetQueryPool vkResetQueryPool = nullptr;
inline PFN_vkGetSemaphoreCounterValue vkGetSemaphoreCounterValue = nullptr;
inline PFN_vkWaitSemaphores vkWaitSemaphores = nullptr;
inline PFN_vkSignalSemaphore vkSignalSemaphore = nullptr;
inline PFN_vkGetBufferDeviceAddress vkGetBufferDeviceAddress = nullptr;
inline PFN_vkGetBufferOpaqueCaptureAddress vkGetBufferOpaqueCaptureAddress = nullptr;
inline PFN_vkGetDeviceMemoryOpaqueCaptureAddress vkGetDeviceMemoryOpaqueCaptureAddress = nullptr;
inline PFN_vkGetPhysicalDeviceToolProperties vkGetPhysicalDeviceToolProperties = nullptr;
inline PFN_vkCreatePrivateDataSlot vkCreatePrivateDataSlot = nullptr;
inline PFN_vkDestroyPrivateDataSlot vkDestroyPrivateDataSlot = nullptr;
inline PFN_vkSetPrivateData vkSetPrivateData = nullptr;
inline PFN_vkGetPrivateData vkGetPrivateData = nullptr;
inline PFN_vkCmdSetEvent2 vkCmdSetEvent2 = nullptr;
inline PFN_vkCmdResetEvent2 vkCmdResetEvent2 = nullptr;
inline PFN_vkCmdWaitEvents2 vkCmdWaitEvents2 = nullptr;
inline PFN_vkCmdPipelineBarrier2 vkCmdPipelineBarrier2 = nullptr;
inline PFN_vkCmdWriteTimestamp2 vkCmdWriteTimestamp2 = nullptr;
inline PFN_vkQueueSubmit2 vkQueueSubmit2 = nullptr;
inline PFN_vkCmdCopyBuffer2 vkCmdCopyBuffer2 = nullptr;
inline PFN_vkCmdCopyImage2 vkCmdCopyImage2 = nullptr;
inline PFN_vkCmdCopyBufferToImage2 vkCmdCopyBufferToImage2 = nullptr;
inline PFN_vkCmdCopyImageToBuffer2 vkCmdCopyImageToBuffer2 = nullptr;
inline PFN_vkCmdBlitImage2 vkCmdBlitImage2 = nullptr;
inline PFN_vkCmdResolveImage2 vkCmdResolveImage2 = nullptr;
inline PFN_vkCmdBeginRendering vkCmdBeginRendering = nullptr;
inline PFN_vkCmdEndRendering vkCmdEndRendering = nullptr;
inline PFN_vkCmdSetCullMode vkCmdSetCullMode = nullptr;
inline PFN_vkCmdSetFrontFace vkCmdSetFrontFace = nullptr;
inline PFN_vkCmdSetPrimitiveTopology vkCmdSetPrimitiveTopology = nullptr;
inline PFN_vkCmdSetViewportWithCount vkCmdSetViewportWithCount = nullptr;
inline PFN_vkCmdSetScissorWithCount vkCmdSetScissorWithCount = nullptr;
inline PFN_vkCmdBindVertexBuffers2 vkCmdBindVertexBuffers2 = nullptr;
inline PFN_vkCmdSetDepthTestEnable vkCmdSetDepthTestEnable = nullptr;
inline PFN_vkCmdSetDepthWriteEnable vkCmdSetDepthWriteEnable = nullptr;
inline PFN_vkCmdSetDepthCompareOp vkCmdSetDepthCompareOp = nullptr;
inline PFN_vkCmdSetDepthBoundsTestEnable vkCmdSetDepthBoundsTestEnable = nullptr;
inline PFN_vkCmdSetStencilTestEnable vkCmdSetStencilTestEnable = nullptr;
inline PFN_vkCmdSetStencilOp vkCmdSetStencilOp = nullptr;
inline PFN_vkCmdSetRasterizerDiscardEnable vkCmdSetRasterizerDiscardEnable = nullptr;
inline PFN_vkCmdSetDepthBiasEnable vkCmdSetDepthBiasEnable = nullptr;
inline PFN_vkCmdSetPrimitiveRestartEnable vkCmdSetPrimitiveRestartEnable = nullptr;
inline PFN_vkGetDeviceBufferMemoryRequirements vkGetDeviceBufferMemoryRequirements = nullptr;
inline PFN_vkGetDeviceImageMemoryRequirements vkGetDeviceImageMemoryRequirements = nullptr;
inline PFN_vkGetDeviceImageSparseMemoryRequirements vkGetDeviceImageSparseMemoryRequirements = nullptr;
inline PFN_vkDestroySurfaceKHR vkDestroySurfaceKHR = nullptr;
inline PFN_vkGetPhysicalDeviceSurfaceSupportKHR vkGetPhysicalDeviceSurfaceSupportKHR = nullptr;
inline PFN_vkGetPhysicalDeviceSurfaceCapabilitiesKHR vkGetPhysicalDeviceSurfaceCapabilitiesKHR = nullptr;
inline PFN_vkGetPhysicalDeviceSurfaceFormatsKHR vkGetPhysicalDeviceSurfaceFormatsKHR = nullptr;
inline PFN_vkGetPhysicalDeviceSurfacePresentModesKHR vkGetPhysicalDeviceSurfacePresentModesKHR = nullptr;
inline PFN_vkCreateSwapchainKHR vkCreateSwapchainKHR = nullptr;
inline PFN_vkDestroySwapchainKHR vkDestroySwapchainKHR = nullptr;
inline PFN_vkGetSwapchainImagesKHR vkGetSwapchainImagesKHR = nullptr;
inline PFN_vkAcquireNextImageKHR vkAcquireNextImageKHR = nullptr;
inline PFN_vkQueuePresentKHR vkQueuePresentKHR = nullptr;
inline PFN_vkGetDeviceGroupPresentCapabilitiesKHR vkGetDeviceGroupPresentCapabilitiesKHR = nullptr;
inline PFN_vkGetDeviceGroupSurfacePresentModesKHR vkGetDeviceGroupSurfacePresentModesKHR = nullptr;
inline PFN_vkGetPhysicalDevicePresentRectanglesKHR vkGetPhysicalDevicePresentRectanglesKHR = nullptr;
inline PFN_vkAcquireNextImage2KHR vkAcquireNextImage2KHR = nullptr;
inline PFN_vkCreateXlibSurfaceKHR vkCreateXlibSurfaceKHR = nullptr;
inline PFN_vkGetPhysicalDeviceXlibPresentationSupportKHR vkGetPhysicalDeviceXlibPresentationSupportKHR = nullptr;
inline PFN_vkCreateWaylandSurfaceKHR vkCreateWaylandSurfaceKHR = nullptr;
inline PFN_vkGetPhysicalDeviceWaylandPresentationSupportKHR vkGetPhysicalDeviceWaylandPresentationSupportKHR = nullptr;
inline PFN_vkSetDebugUtilsObjectNameEXT vkSetDebugUtilsObjectNameEXT = nullptr;
inline PFN_vkSetDebugUtilsObjectTagEXT vkSetDebugUtilsObjectTagEXT = nullptr;
inline PFN_vkQueueBeginDebugUtilsLabelEXT vkQueueBeginDebugUtilsLabelEXT = nullptr;
inline PFN_vkQueueEndDebugUtilsLabelEXT vkQueueEndDebugUtilsLabelEXT = nullptr;
inline PFN_vkQueueInsertDebugUtilsLabelEXT vkQueueInsertDebugUtilsLabelEXT = nullptr;
inline PFN_vkCmdBeginDebugUtilsLabelEXT vkCmdBeginDebugUtilsLabelEXT = nullptr;
inline PFN_vkCmdEndDebugUtilsLabelEXT vkCmdEndDebugUtilsLabelEXT = nullptr;
inline PFN_vkCmdInsertDebugUtilsLabelEXT vkCmdInsertDebugUtilsLabelEXT = nullptr;
inline PFN_vkCreateDebugUtilsMessengerEXT vkCreateDebugUtilsMessengerEXT = nullptr;
inline PFN_vkDestroyDebugUtilsMessengerEXT vkDestroyDebugUtilsMessengerEXT = nullptr;
inline PFN_vkSubmitDebugUtilsMessageEXT vkSubmitDebugUtilsMessageEXT = nullptr;
inline PFN_vkCmdSetEvent2KHR vkCmdSetEvent2KHR = nullptr;
inline PFN_vkCmdResetEvent2KHR vkCmdResetEvent2KHR = nullptr;
inline PFN_vkCmdWaitEvents2KHR vkCmdWaitEvents2KHR = nullptr;
inline PFN_vkCmdPipelineBarrier2KHR vkCmdPipelineBarrier2KHR = nullptr;
inline PFN_vkCmdWriteTimestamp2KHR vkCmdWriteTimestamp2KHR = nullptr;
inline PFN_vkQueueSubmit2KHR vkQueueSubmit2KHR = nullptr;
inline PFN_vkCmdWriteBufferMarker2AMD vkCmdWriteBufferMarker2AMD = nullptr;
inline PFN_vkGetQueueCheckpointData2NV vkGetQueueCheckpointData2NV = nullptr;

inline void **const __vk_fnptr_slots[] = {
  reinterpret_cast<void **>(&vkCreateInstance),
  reinterpret_cast<void **>(&vkDestroyInstance),
  reinterpret_cast<void **>(&vkEnumeratePhysicalDevices),
  reinterpret_cast<void **>(&vkGetPhysicalDeviceFeatures),
  reinterpret_cast<void **>(&vkGetPhysicalDeviceFormatProperties),
  reinterpret_cast<void **>(&vkGetPhysicalDeviceImageFormatProperties),
  reinterpret_cast<void **>(&vkGetPhysicalDeviceProperties),
  reinterpret_cast<void **>(&vkGetPhysicalDeviceQueueFamilyProperties),
  reinterpret_cast<void **>(&vkGetPhysicalDeviceMemoryProperties),
  reinterpret_cast<void **>(&vkGetInstanceProcAddr),
  reinterpret_cast<void **>(&vkGetDeviceProcAddr),
  reinterpret_cast<void **>(&vkCreateDevice),
  reinterpret_cast<void **>(&vkDestroyDevice),
  reinterpret_cast<void **>(&vkEnumerateInstanceExtensionProperties),
  reinterpret_cast<void **>(&vkEnumerateDeviceExtensionProperties),
  reinterpret_cast<void **>(&vkEnumerateInstanceLayerProperties),
  reinterpret_cast<void **>(&vkEnumerateDeviceLayerProperties),
  reinterpret_cast<void **>(&vkGetDeviceQueue),
  reinterpret_cast<void **>(&vkQueueSubmit),
  reinterpret_cast<void **>(&vkQueueWaitIdle),
  reinterpret_cast<void **>(&vkDeviceWaitIdle),
  reinterpret_cast<void **>(&vkAllocateMemory),
  reinterpret_cast<void **>(&vkFreeMemory),
  reinterpret_cast<void **>(&vkMapMemory),
  reinterpret_cast<void **>(&vkUnmapMemory),
  reinterpret_cast<void **>(&vkFlushMappedMemoryRanges),
  reinterpret_cast<void **>(&vkInvalidateMappedMemoryRanges),
  reinterpret_cast<void **>(&vkGetDeviceMemoryCommitment),
  reinterpret_cast<void **>(&vkBindBufferMemory),
  reinterpret_cast<void **>(&vkBindImageMemory),
  reinterpret_cast<void **>(&vkGetBufferMemoryRequirements),
  reinterpret_cast<void **>(&vkGetImageMemoryRequirements),
  reinterpret_cast<void **>(&vkGetImageSparseMemoryRequirements),
  reinterpret_cast<void **>(&vkGetPhysicalDeviceSparseImageFormatProperties),
  reinterpret_cast<void **>(&vkQueueBindSparse),
  reinterpret_cast<void **>(&vkCreateFence),
  reinterpret_cast<void **>(&vkDestroyFence),
  reinterpret_cast<void **>(&vkResetFences),
  reinterpret_cast<void **>(&vkGetFenceStatus),
  reinterpret_cast<void **>(&vkWaitForFences),
  reinterpret_cast<void **>(&vkCreateSemaphore),
  reinterpret_cast<void **>(&vkDestroySemaphore),
  reinterpret_cast<void **>(&vkCreateEvent),
  reinterpret_cast<void **>(&vkDestroyEvent),
  reinterpret_cast<void **>(&vkGetEventStatus),
  reinterpret_cast<void **>(&vkSetEvent),
  reinterpret_cast<void **>(&vkResetEvent),
  reinterpret_cast<void **>(&vkCreateQueryPool),
  reinterpret_cast<void **>(&vkDestroyQueryPool),
  reinterpret_cast<void **>(&vkGetQueryPoolResults),
  reinterpret_cast<void **>(&vkCreateBuffer),
  reinterpret_cast<void **>(&vkDestroyBuffer),
  reinterpret_cast<void **>(&vkCreateBufferView),
  reinterpret_cast<void **>(&vkDestroyBufferView),
  reinterpret_cast<void **>(&vkCreateImage),
  reinterpret_cast<void **>(&vkDestroyImage),
  reinterpret_cast<void **>(&vkGetImageSubresourceLayout),
  reinterpret_cast<void **>(&vkCreateImageView),
  reinterpret_cast<void **>(&vkDestroyImageView),
  reinterpret_cast<void **>(&vkCreateShaderModule),
  reinterpret_cast<void **>(&vkDestroyShaderModule),
  reinterpret_cast<void **>(&vkCreatePipelineCache),
  reinterpret_cast<void **>(&vkDestroyPipelineCache),
  reinterpret_cast<void **>(&vkGetPipelineCacheData),
  reinterpret_cast<void **>(&vkMergePipelineCaches),
  reinterpret_cast<void **>(&vkCreateGraphicsPipelines),
  reinterpret_cast<void **>(&vkCreateComputePipelines),
  reinterpret_cast<void **>(&vkDestroyPipeline),
  reinterpret_cast<void **>(&vkCreatePipelineLayout),
  reinterpret_cast<void **>(&vkDestroyPipelineLayout),
  reinterpret_cast<void **>(&vkCreateSampler),
  reinterpret_cast<void **>(&vkDestroySampler),
  reinterpret_cast<void **>(&vkCreateDescriptorSetLayout),
  reinterpret_cast<void **>(&vkDestroyDescriptorSetLayout),
  reinterpret_cast<void **>(&vkCreateDescriptorPool),
  reinterpret_cast<void **>(&vkDestroyDescriptorPool),
  reinterpret_cast<void **>(&vkResetDescriptorPool),
  reinterpret_cast<void **>(&vkAllocateDescriptorSets),
  reinterpret_cast<void **>(&vkFreeDescriptorSets),
  reinterpret_cast<void **>(&vkUpdateDescriptorSets),
  reinterpret_cast<void **>(&vkCreateFramebuffer),
  reinterpret_cast<void **>(&vkDestroyFramebuffer),
  reinterpret_cast<void **>(&vkCreateRenderPass),
  reinterpret_cast<void **>(&vkDestroyRenderPass),
  reinterpret_cast<void **>(&vkGetRenderAreaGranularity),
  reinterpret_cast<void **>(&vkCreateCommandPool),
  reinterpret_cast<void **>(&vkDestroyCommandPool),
  reinterpret_cast<void **>(&vkResetCommandPool),
  reinterpret_cast<void **>(&vkAllocateCommandBuffers),
  reinterpret_cast<void **>(&vkFreeCommandBuffers),
  reinterpret_cast<void **>(&vkBeginCommandBuffer),
  reinterpret_cast<void **>(&vkEndCommandBuffer),
  reinterpret_cast<void **>(&vkResetCommandBuffer),
  reinterpret_cast<void **>(&vkCmdBindPipeline),
  reinterpret_cast<void **>(&vkCmdSetViewport),
  reinterpret_cast<void **>(&vkCmdSetScissor),
  reinterpret_cast<void **>(&vkCmdSetLineWidth),
  reinterpret_cast<void **>(&vkCmdSetDepthBias),
  reinterpret_cast<void **>(&vkCmdSetBlendConstants),
  reinterpret_cast<void **>(&vkCmdSetDepthBounds),
  reinterpret_cast<void **>(&vkCmdSetStencilCompareMask),
  reinterpret_cast<void **>(&vkCmdSetStencilWriteMask),
  reinterpret_cast<void **>(&vkCmdSetStencilReference),
  reinterpret_cast<void **>(&vkCmdBindDescriptorSets),
  reinterpret_cast<void **>(&vkCmdBindIndexBuffer),
  reinterpret_cast<void **>(&vkCmdBindVertexBuffers),
  reinterpret_cast<void **>(&vkCmdDraw),
  reinterpret_cast<void **>(&vkCmdDrawIndexed),
  reinterpret_cast<void **>(&vkCmdDrawIndirect),
  reinterpret_cast<void **>(&vkCmdDrawIndexedIndirect),
  reinterpret_cast<void **>(&vkCmdDispatch),
  reinterpret_cast<void **>(&vkCmdDispatchIndirect),
  reinterpret_cast<void **>(&vkCmdCopyBuffer),
  reinterpret_cast<void **>(&vkCmdCopyImage),
  reinterpret_cast<void **>(&vkCmdBlitImage),
  reinterpret_cast<void **>(&vkCmdCopyBufferToImage),
  reinterpret_cast<void **>(&vkCmdCopyImageToBuffer),
  reinterpret_cast<void **>(&vkCmdUpdateBuffer),
  reinterpret_cast<void **>(&vkCmdFillBuffer),
  reinterpret_cast<void **>(&vkCmdClearColorImage),
  reinterpret_cast<void **>(&vkCmdClearDepthStencilImage),
  reinterpret_cast<void **>(&vkCmdClearAttachments),
  reinterpret_cast<void **>(&vkCmdResolveImage),
  reinterpret_cast<void **>(&vkCmdSetEvent),
  reinterpret_cast<void **>(&vkCmdResetEvent),
  reinterpret_cast<void **>(&vkCmdWaitEvents),
  reinterpret_cast<void **>(&vkCmdPipelineBarrier),
  reinterpret_cast<void **>(&vkCmdBeginQuery),
  reinterpret_cast<void **>(&vkCmdEndQuery),
  reinterpret_cast<void **>(&vkCmdResetQueryPool),
  reinterpret_cast<void **>(&vkCmdWriteTimestamp),
  reinterpret_cast<void **>(&vkCmdCopyQueryPoolResults),
  reinterpret_cast<void **>(&vkCmdPushConstants),
  reinterpret_cast<void **>(&vkCmdBeginRenderPass),
  reinterpret_cast<void **>(&vkCmdNextSubpass),
  reinterpret_cast<void **>(&vkCmdEndRenderPass),
  reinterpret_cast<void **>(&vkCmdExecuteCommands),
  reinterpret_cast<void **>(&vkEnumerateInstanceVersion),
  reinterpret_cast<void **>(&vkBindBufferMemory2),
  reinterpret_cast<void **>(&vkBindImageMemory2),
  reinterpret_cast<void **>(&vkGetDeviceGroupPeerMemoryFeatures),
  reinterpret_cast<void **>(&vkCmdSetDeviceMask),
  reinterpret_cast<void **>(&vkCmdDispatchBase),
  reinterpret_cast<void **>(&vkEnumeratePhysicalDeviceGroups),
  reinterpret_cast<void **>(&vkGetImageMemoryRequirements2),
  reinterpret_cast<void **>(&vkGetBufferMemoryRequirements2),
  reinterpret_cast<void **>(&vkGetImageSparseMemoryRequirements2),
  reinterpret_cast<void **>(&vkGetPhysicalDeviceFeatures2),
  reinterpret_cast<void **>(&vkGetPhysicalDeviceProperties2),
  reinterpret_cast<void **>(&vkGetPhysicalDeviceFormatProperties2),
  reinterpret_cast<void **>(&vkGetPhysicalDeviceImageFormatProperties2),
  reinterpret_cast<void **>(&vkGetPhysicalDeviceQueueFamilyProperties2),
  reinterpret_cast<void **>(&vkGetPhysicalDeviceMemoryProperties2),
  reinterpret_cast<void **>(&vkGetPhysicalDeviceSparseImageFormatProperties2),
  reinterpret_cast<void **>(&vkTrimCommandPool),
  reinterpret_cast<void **>(&vkGetDeviceQueue2),
  reinterpret_cast<void **>(&vkCreateSamplerYcbcrConversion),
  reinterpret_cast<void **>(&vkDestroySamplerYcbcrConversion),
  reinterpret_cast<void **>(&vkCreateDescriptorUpdateTemplate),
  reinterpret_cast<void **>(&vkDestroyDescriptorUpdateTemplate),
  reinterpret_cast<void **>(&vkUpdateDescriptorSetWithTemplate),
  reinterpret_cast<void **>(&vkGetPhysicalDeviceExternalBufferProperties),
  reinterpret_cast<void **>(&vkGetPhysicalDeviceExternalFenceProperties),
  reinterpret_cast<void **>(&vkGetPhysicalDeviceExternalSemaphoreProperties),
  reinterpret_cast<void **>(&vkGetDescriptorSetLayoutSupport),
  reinterpret_cast<void **>(&vkCmdDrawIndirectCount),
  reinterpret_cast<void **>(&vkCmdDrawIndexedIndirectCount),
  reinterpret_cast<void **>(&vkCreateRenderPass2),
  reinterpret_cast<void **>(&vkCmdBeginRenderPass2),
  reinterpret_cast<void **>(&vkCmdNextSubpass2),
  reinterpret_cast<void **>(&vkCmdEndRenderPass2),
  reinterpret_cast<void **>(&vkResetQueryPool),
  reinterpret_cast<void **>(&vkGetSemaphoreCounterValue),
  reinterpret_cast<void **>(&vkWaitSemaphores),
  reinterpret_cast<void **>(&vkSignalSemaphore),
  reinterpret_cast<void **>(&vkGetBufferDeviceAddress),
  reinterpret_cast<void **>(&vkGetBufferOpaqueCaptureAddress),
  reinterpret_cast<void **>(&vkGetDeviceMemoryOpaqueCaptureAddress),
  reinterpret_cast<void **>(&vkGetPhysicalDeviceToolProperties),
  reinterpret_cast<void **>(&vkCreatePrivateDataSlot),
  reinterpret_cast<void **>(&vkDestroyPrivateDataSlot),
  reinterpret_cast<void **>(&vkSetPrivateData),
  reinterpret_cast<void **>(&vkGetPrivateData),
  reinterpret_cast<void **>(&vkCmdSetEvent2),
  reinterpret_cast<void **>(&vkCmdResetEvent2),
  reinterpret_cast<void **>(&vkCmdWaitEvents2),
  reinterpret_cast<void **>(&vkCmdPipelineBarrier2),
  reinterpret_cast<void **>(&vkCmdWriteTimestamp2),
  reinterpret_cast<void **>(&vkQueueSubmit2),
  reinterpret_cast<void **>(&vkCmdCopyBuffer2),
  reinterpret_cast<void **>(&vkCmdCopyImage2),
  reinterpret_cast<void **>(&vkCmdCopyBufferToImage2),
  reinterpret_cast<void **>(&vkCmdCopyImageToBuffer2),
  reinterpret_cast<void **>(&vkCmdBlitImage2),
  reinterpret_cast<void **>(&vkCmdResolveImage2),
  reinterpret_cast<void **>(&vkCmdBeginRendering),
  reinterpret_cast<void **>(&vkCmdEndRendering),
  reinterpret_cast<void **>(&vkCmdSetCullMode),
  reinterpret_cast<void **>(&vkCmdSetFrontFace),
  reinterpret_cast<void **>(&vkCmdSetPrimitiveTopology),
  reinterpret_cast<void **>(&vkCmdSetViewportWithCount),
  reinterpret_cast<void **>(&vkCmdSetScissorWithCount),
  reinterpret_cast<void **>(&vkCmdBindVertexBuffers2),
  reinterpret_cast<void **>(&vkCmdSetDepthTestEnable),
  reinterpret_cast<void **>(&vkCmdSetDepthWriteEnable),
  reinterpret_cast<void **>(&vkCmdSetDepthCompareOp),
  reinterpret_cast<void **>(&vkCmdSetDepthBoundsTestEnable),
  reinterpret_cast<void **>(&vkCmdSetStencilTestEnable),
  reinterpret_cast<void **>(&vkCmdSetStencilOp),
  reinterpret_cast<void **>(&vkCmdSetRasterizerDiscardEnable),
  reinterpret_cast<void **>(&vkCmdSetDepthBiasEnable),
  reinterpret_cast<void **>(&vkCmdSetPrimitiveRestartEnable),
  reinterpret_cast<void **>(&vkGetDeviceBufferMemoryRequirements),
  reinterpret_cast<void **>(&vkGetDeviceImageMemoryRequirements),
  reinterpret_cast<void **>(&vkGetDeviceImageSparseMemoryRequirements),
  reinterpret_cast<void **>(&vkDestroySurfaceKHR),
  reinterpret_cast<void **>(&vkGetPhysicalDeviceSurfaceSupportKHR),
  reinterpret_cast<void **>(&vkGetPhysicalDeviceSurfaceCapabilitiesKHR),
  reinterpret_cast<void **>(&vkGetPhysicalDeviceSurfaceFormatsKHR),
  reinterpret_cast<void **>(&vkGetPhysicalDeviceSurfacePresentModesKHR),
  reinterpret_cast<void **>(&vkCreateSwapchainKHR),
  reinterpret_cast<void **>(&vkDestroySwapchainKHR),
  reinterpret_cast<void **>(&vkGetSwapchainImagesKHR),
  reinterpret_cast<void **>(&vkAcquireNextImageKHR),
  reinterpret_cast<void **>(&vkQueuePresentKHR),
  reinterpret_cast<void **>(&vkGetDeviceGroupPresentCapabilitiesKHR),
  reinterpret_cast<void **>(&vkGetDeviceGroupSurfacePresentModesKHR),
  reinterpret_cast<void **>(&vkGetPhysicalDevicePresentRectanglesKHR),
  reinterpret_cast<void **>(&vkAcquireNextImage2KHR),
  reinterpret_cast<void **>(&vkCreateXlibSurfaceKHR),
  reinterpret_cast<void **>(&vkGetPhysicalDeviceXlibPresentationSupportKHR),
  reinterpret_cast<void **>(&vkCreateWaylandSurfaceKHR),
  reinterpret_cast<void **>(&vkGetPhysicalDeviceWaylandPresentationSupportKHR),
  reinterpret_cast<void **>(&vkSetDebugUtilsObjectNameEXT),
  reinterpret_cast<void **>(&vkSetDebugUtilsObjectTagEXT),
  reinterpret_cast<void **>(&vkQueueBeginDebugUtilsLabelEXT),
  reinterpret_cast<void **>(&vkQueueEndDebugUtilsLabelEXT),
  reinterpret_cast<void **>(&vkQueueInsertDebugUtilsLabelEXT),
  reinterpret_cast<void **>(&vkCmdBeginDebugUtilsLabelEXT),
  reinterpret_cast<void **>(&vkCmdEndDebugUtilsLabelEXT),
  reinterpret_cast<void **>(&vkCmdInsertDebugUtilsLabelEXT),
  reinterpret_cast<void **>(&vkCreateDebugUtilsMessengerEXT),
  reinterpret_cast<void **>(&vkDestroyDebugUtilsMessengerEXT),
  reinterpret_cast<void **>(&vkSubmitDebugUtilsMessageEXT),
  reinterpret_cast<void **>(&vkCmdSetEvent2KHR),
  reinterpret_cast<void **>(&vkCmdResetEvent2KHR),
  reinterpret_cast<void **>(&vkCmdWaitEvents2KHR),
  reinterpret_cast<void **>(&vkCmdPipelineBarrier2KHR),
  reinterpret_cast<void **>(&vkCmdWriteTimestamp2KHR),
  reinterpret_cast<void **>(&vkQueueSubmit2KHR),
  reinterpret_cast<void **>(&vkCmdWriteBufferMarker2AMD),
  reinterpret_cast<void **>(&vkGetQueueCheckpointData2NV),
};

static_assert(sizeof(__vk_fnptr_slots) / sizeof(__vk_fnptr_slots[0]) == vk_table_size,
              "vulkan.hpp __vk_fnptr_slots must parallel __vk_table.hpp vk_table by index");

}; }; };      // namespace micron::gfx::vk

#include "__bits/__vk_flag_traits.hpp"
#include "__bits/__vk_structure_types.hpp"
#include "__bits/__vk_deleters.hpp"

namespace micron { namespace vk = ::micron::gfx::vk; }

#define MICRON_VK_SYM(name) (::micron::gfx::vk::sym_index_of(#name))
