#!/usr/bin/env python3
"""Generate deterministic fixed quadrature tables using only the stdlib."""

from __future__ import annotations

import argparse
import hashlib
import math
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "src/math/integrate/bits/coeff/generated_tables.hpp"


def literal(value: float) -> str:
    if value == 0.0:
        return "F(0.0L)"
    return f"F({value:.19e}L)"


def legendre_half(order: int) -> tuple[list[float], list[float]]:
    roots: list[tuple[float, float]] = []
    for i in range(1, order // 2 + 1):
        x = math.cos(math.pi * (i - 0.25) / (order + 0.5))
        for _ in range(32):
            p0, p1 = 1.0, x
            for degree in range(2, order + 1):
                p0, p1 = p1, ((2 * degree - 1) * x * p1 - (degree - 1) * p0) / degree
            derivative = order * (x * p1 - p0) / (x * x - 1.0)
            update = p1 / derivative
            x -= update
            if abs(update) <= 2.0e-17:
                break
        p0, p1 = 1.0, x
        for degree in range(2, order + 1):
            p0, p1 = p1, ((2 * degree - 1) * x * p1 - (degree - 1) * p0) / degree
        derivative = order * (x * p1 - p0) / (x * x - 1.0)
        weight = 2.0 / ((1.0 - x * x) * derivative * derivative)
        roots.append((x, weight))
    roots.sort()
    return [x for x, _ in roots], [w for _, w in roots]


def clenshaw_curtis(order: int) -> tuple[list[float], list[float]]:
    nodes = [math.cos(math.pi * k / order) for k in range(order + 1)]
    weights: list[float] = []
    half = order // 2
    for k in range(order + 1):
        angle = math.pi * k / order
        bracket = 1.0
        for j in range(1, half + 1):
            multiplier = 1.0 if 2 * j == order else 2.0
            bracket -= multiplier * math.cos(2.0 * j * angle) / (4.0 * j * j - 1.0)
        weight = 2.0 * bracket / order
        if k == 0 or k == order:
            weight *= 0.5
        weights.append(weight)
    return nodes, weights


def array(name: str, values: list[float], indent: str = "  ") -> list[str]:
    lines = [f"{indent}static constexpr F {name}[{len(values)}] = {{"]
    for start in range(0, len(values), 4):
        chunk = ", ".join(literal(value) for value in values[start : start + 4])
        lines.append(f"{indent}  {chunk},")
    lines.append(f"{indent}}};")
    return lines


def generate() -> str:
    nodes64, weights64 = legendre_half(64)
    lines = [
        "//  Copyright (c) 2024- David Lucius Severus",
        "//",
        "//  Distributed under the Boost Software License, Version 1.0.",
        "//  Generated by scripts/generate_integrate_tables.py; do not edit.",
        "#pragma once",
        "",
        "namespace micron",
        "{",
        "namespace math",
        "{",
        "namespace integrate",
        "{",
        "namespace coeff",
        "{",
        "namespace gl",
        "{",
        "",
        "template<ieee754_floating F> struct gl_table<F, 64> {",
    ]
    lines.extend(array("nodes", nodes64))
    lines.extend(array("weights", weights64))
    lines.extend([
        "  static constexpr usize half = 32;",
        "  static constexpr bool has_zero = false;",
        "};",
        "",
        "};      // namespace gl",
        "namespace cc",
        "{",
        "",
        "template<ieee754_floating F, usize N> struct cc_table { static constexpr bool available = false; };",
        "",
    ])
    for order in (8, 16, 32, 64):
        nodes, weights = clenshaw_curtis(order)
        lines.append(f"template<ieee754_floating F> struct cc_table<F, {order}> {{")
        lines.append("  static constexpr bool available = true;")
        lines.extend(array("nodes", nodes))
        lines.extend(array("weights", weights))
        lines.append("};")
        lines.append("")
    lines.extend([
        "};      // namespace cc",
        "};      // namespace coeff",
        "};      // namespace integrate",
        "};      // namespace math",
        "};      // namespace micron",
        "",
    ])
    body = "\n".join(lines)
    digest = hashlib.sha256(body.encode()).hexdigest()
    return body.replace("#pragma once\n", f"#pragma once\n\n// table checksum: {digest}\n", 1)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = generate()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != generated:
            print(f"out of date: {OUTPUT}")
            return 1
        print(f"up to date: {OUTPUT}")
        return 0
    OUTPUT.write_text(generated)
    print(f"generated: {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
