#!/usr/bin/env python3
"""Regenerate duck's complete Clang driver/diagnostic option catalog."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import re
import subprocess
import sys


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "tools/src/recipes/clang/all_flags.hh"
OPTION_RE = re.compile(r"^  (-\S+)")
DOC_URL = "https://releases.llvm.org/22.1.0/tools/clang/docs/ClangCommandLineReference.html"


def run(compiler: str, *args: str) -> str:
    return subprocess.run(
        [compiler, *args], check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True
    ).stdout


def option_names(output: str) -> set[str]:
    return {match.group(1) for line in output.splitlines() if (match := OPTION_RE.match(line))}


def catalog(compiler: str) -> str:
    version = run(compiler, "--version").splitlines()[0]
    driver = option_names(run(compiler, "--help-hidden"))
    diagnostics = option_names(run(compiler, "-print-diagnostic-options"))
    entries = sorted(driver | diagnostics)
    lines = [
        "// Generated by scripts/generate_clang_flags.py; do not edit.",
        f"// Compiler: {version}",
        f"// Documentation: {DOC_URL}",
        f"// Driver options: {len(driver)}",
        f"// Diagnostic options: {len(diagnostics)}",
        f"// Unique options: {len(entries)}",
        "//",
        "// The compiler is authoritative because --help-hidden includes public, hidden,",
        "// compatibility, target, and development options omitted from the web reference.",
        "#pragma once",
        "",
        "namespace clang_flags::catalog",
        "{",
        "inline constexpr const char *all[] = {",
        *(f"  {json.dumps(entry)}," for entry in entries),
        "};",
        "inline constexpr unsigned count = sizeof(all) / sizeof(*all);",
        "}      // namespace clang_flags::catalog",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--clang", default=os.environ.get("CLANGXX", "clang++"))
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    generated = catalog(args.clang)
    if args.check:
        if not args.output.exists() or args.output.read_text() != generated:
            print(f"stale Clang flag catalog: {args.output}", file=sys.stderr)
            return 1
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generated)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
