//  Copyright (c) 2026 David Lucius Severus
//
//  Distributed under the Boost Software License, Version 1.0.
//  See accompanying file LICENSE_1_0.txt or copy at
//  http://www.boost.org/LICENSE_1_0.txt
#pragma once

// %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
// micron::bb; the barebones allocator
//
// SOURCED FROM: bbmalloc, which is AUTOGENERATED

#include "../../../defs.hpp"

#include "../../../port/__backend.hpp"

#if !defined(__micron_port_kernel) && !defined(__micron_port_metal) && !defined(__micron_port_linux)
#error                                                                                                                                     \
    "bb_alloc.hpp: no port backend selector is visible. port/__backend.hpp must be included above this line, or every profile and pool default below silently takes its else branch."
#endif

#if defined(__micron_port_metal)

#if !defined(__BB_TINY) && !defined(__BB_SMALL) && !defined(__BB_KERNEL) && !defined(BBMALLOC_CONFIG_HEADER)
#define __BB_TINY 1
#endif

#if !defined(MICRON_BB_STATIC_POOL) && !defined(MICRON_BB_LINKER_POOL) && !defined(MICRON_BB_PORT_POOL) && !defined(BBMALLOC_CONFIG_HEADER)
#error                                                                                                                                     \
    "micron::bb on MICRON_PORT_METAL has no pool. Pick one: MICRON_BB_PORT_POOL=<bytes> takes it from port::page_alloc, which is recommended; MICRON_BB_STATIC_POOL=<bytes> puts it in .bss; MICRON_BB_LINKER_POOL takes __heap_start/__heap_end directly."
#endif

#if defined(MICRON_BB_LINKER_POOL) && !defined(MICRON_METAL_POOL_SPLIT_OK)
#error                                                                                                                                     \
    "micron::bb on MICRON_PORT_METAL with MICRON_BB_LINKER_POOL: bbmalloc's linker pool and micron's page source both claim __heap_start..__heap_end, so port::page_alloc would hand out memory the heap already owns and port::heap_extent() would report it free. Use MICRON_BB_PORT_POOL=<bytes> intead."
#endif

#else

#if !defined(__BB_TINY) && !defined(__BB_SMALL) && !defined(__BB_KERNEL) && !defined(BBMALLOC_CONFIG_HEADER)
#if defined(__micron_port_kernel)
#define __BB_KERNEL 1
#endif
#endif

#if !defined(MICRON_BB_STATIC_POOL) && !defined(MICRON_BB_LINKER_POOL) && !defined(MICRON_BB_PORT_POOL)
#if defined(__micron_port_kernel)
// kvmalloc, so this is one vmalloc of 4 MiB at first use rather than a contiguous physical block
#define MICRON_BB_PORT_POOL (4u << 20)
#else
#define MICRON_BB_PORT_POOL (8u << 20)
#endif
#endif

#if defined(MICRON_BB_PORT_POOL) && !defined(MICRON_BB_PORT_GROW) && !defined(MICRON_BB_NO_GROW)
#define MICRON_BB_PORT_GROW MICRON_BB_PORT_POOL
#endif

#if defined(MICRON_BB_PORT_GROW) && !defined(MICRON_BB_MAX_REGIONS) && !defined(__BB_TINY) && !defined(__BB_KERNEL)
#define MICRON_BB_MAX_REGIONS 8
#endif

#endif

#include "../bbmalloc/bbmalloc.hpp"

#if defined(__micron_port_kernel) && !defined(BBMALLOC_CONFIG_HEADER) && !defined(MICRON_BB_CLASS_SMALL)
static_assert(::bb::__class_small == 4096, "bb: the port selector was not visible when bb_alloc.hpp chose one");
#endif

#if defined(__micron_port_metal) && !defined(BBMALLOC_CONFIG_HEADER) && !defined(MICRON_BB_CLASS_SMALL)
static_assert(::bb::__class_small == 256, "bb: the port selector was not visible when bb_alloc.hpp chose one");
#endif

namespace micron
{

namespace bb = ::bb;

using bb_allocator = ::bb::bb_allocator;

};      // namespace micron
